version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  go: "1.23"

output:
  formats:
    text:
      print-linter-name: false
      print-issued-lines: true
      colors: true

linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gosec
    - govet
    - nilerr
    - nilnil
    - staticcheck
    - unused
    - whitespace

  exclusions:
    rules:   
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - errcheck
          - goconst
          - gosec

      # checking for errors in defers seldom makes sense...
      - source: "^\\s*defer\\s"
        linters:
          - errcheck
          - staticcheck