// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewHubInterface creates a new instance of HubInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHubInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HubInterface {
	mock := &HubInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HubInterface is an autogenerated mock type for the HubInterface type
type HubInterface struct {
	mock.Mock
}

type HubInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *HubInterface) EXPECT() *HubInterface_Expecter {
	return &HubInterface_Expecter{mock: &_m.Mock}
}

// CancelPairing provides a mock function for the type HubInterface
func (_mock *HubInterface) CancelPairing(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubInterface_CancelPairing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPairing'
type HubInterface_CancelPairing_Call struct {
	*mock.Call
}

// CancelPairing is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubInterface_Expecter) CancelPairing(identity interface{}) *HubInterface_CancelPairing_Call {
	return &HubInterface_CancelPairing_Call{Call: _e.mock.On("CancelPairing", identity)}
}

func (_c *HubInterface_CancelPairing_Call) Run(run func(identity api.ServiceIdentity)) *HubInterface_CancelPairing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubInterface_CancelPairing_Call) Return() *HubInterface_CancelPairing_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_CancelPairing_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubInterface_CancelPairing_Call {
	_c.Run(run)
	return _c
}

// DisconnectService provides a mock function for the type HubInterface
func (_mock *HubInterface) DisconnectService(identity api.ServiceIdentity, reason string) {
	_mock.Called(identity, reason)
	return
}

// HubInterface_DisconnectService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectService'
type HubInterface_DisconnectService_Call struct {
	*mock.Call
}

// DisconnectService is a helper method to define mock.On call
//   - identity api.ServiceIdentity
//   - reason string
func (_e *HubInterface_Expecter) DisconnectService(identity interface{}, reason interface{}) *HubInterface_DisconnectService_Call {
	return &HubInterface_DisconnectService_Call{Call: _e.mock.On("DisconnectService", identity, reason)}
}

func (_c *HubInterface_DisconnectService_Call) Run(run func(identity api.ServiceIdentity, reason string)) *HubInterface_DisconnectService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubInterface_DisconnectService_Call) Return() *HubInterface_DisconnectService_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_DisconnectService_Call) RunAndReturn(run func(identity api.ServiceIdentity, reason string)) *HubInterface_DisconnectService_Call {
	_c.Run(run)
	return _c
}

// PairingDetailFor provides a mock function for the type HubInterface
func (_mock *HubInterface) PairingDetailFor(identity api.ServiceIdentity) *api.ConnectionStateDetail {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for PairingDetailFor")
	}

	var r0 *api.ConnectionStateDetail
	if returnFunc, ok := ret.Get(0).(func(api.ServiceIdentity) *api.ConnectionStateDetail); ok {
		r0 = returnFunc(identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ConnectionStateDetail)
		}
	}
	return r0
}

// HubInterface_PairingDetailFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PairingDetailFor'
type HubInterface_PairingDetailFor_Call struct {
	*mock.Call
}

// PairingDetailFor is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubInterface_Expecter) PairingDetailFor(identity interface{}) *HubInterface_PairingDetailFor_Call {
	return &HubInterface_PairingDetailFor_Call{Call: _e.mock.On("PairingDetailFor", identity)}
}

func (_c *HubInterface_PairingDetailFor_Call) Run(run func(identity api.ServiceIdentity)) *HubInterface_PairingDetailFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubInterface_PairingDetailFor_Call) Return(connectionStateDetail *api.ConnectionStateDetail) *HubInterface_PairingDetailFor_Call {
	_c.Call.Return(connectionStateDetail)
	return _c
}

func (_c *HubInterface_PairingDetailFor_Call) RunAndReturn(run func(identity api.ServiceIdentity) *api.ConnectionStateDetail) *HubInterface_PairingDetailFor_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterRemoteService provides a mock function for the type HubInterface
func (_mock *HubInterface) RegisterRemoteService(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubInterface_RegisterRemoteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRemoteService'
type HubInterface_RegisterRemoteService_Call struct {
	*mock.Call
}

// RegisterRemoteService is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubInterface_Expecter) RegisterRemoteService(identity interface{}) *HubInterface_RegisterRemoteService_Call {
	return &HubInterface_RegisterRemoteService_Call{Call: _e.mock.On("RegisterRemoteService", identity)}
}

func (_c *HubInterface_RegisterRemoteService_Call) Run(run func(identity api.ServiceIdentity)) *HubInterface_RegisterRemoteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubInterface_RegisterRemoteService_Call) Return() *HubInterface_RegisterRemoteService_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_RegisterRemoteService_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubInterface_RegisterRemoteService_Call {
	_c.Run(run)
	return _c
}

// SetAutoAccept provides a mock function for the type HubInterface
func (_mock *HubInterface) SetAutoAccept(b bool) {
	_mock.Called(b)
	return
}

// HubInterface_SetAutoAccept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAutoAccept'
type HubInterface_SetAutoAccept_Call struct {
	*mock.Call
}

// SetAutoAccept is a helper method to define mock.On call
//   - b bool
func (_e *HubInterface_Expecter) SetAutoAccept(b interface{}) *HubInterface_SetAutoAccept_Call {
	return &HubInterface_SetAutoAccept_Call{Call: _e.mock.On("SetAutoAccept", b)}
}

func (_c *HubInterface_SetAutoAccept_Call) Run(run func(b bool)) *HubInterface_SetAutoAccept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubInterface_SetAutoAccept_Call) Return() *HubInterface_SetAutoAccept_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_SetAutoAccept_Call) RunAndReturn(run func(b bool)) *HubInterface_SetAutoAccept_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type HubInterface
func (_mock *HubInterface) Shutdown() {
	_mock.Called()
	return
}

// HubInterface_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type HubInterface_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *HubInterface_Expecter) Shutdown() *HubInterface_Shutdown_Call {
	return &HubInterface_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *HubInterface_Shutdown_Call) Run(run func()) *HubInterface_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HubInterface_Shutdown_Call) Return() *HubInterface_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_Shutdown_Call) RunAndReturn(run func()) *HubInterface_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type HubInterface
func (_mock *HubInterface) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HubInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type HubInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *HubInterface_Expecter) Start() *HubInterface_Start_Call {
	return &HubInterface_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *HubInterface_Start_Call) Run(run func()) *HubInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HubInterface_Start_Call) Return(err error) *HubInterface_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HubInterface_Start_Call) RunAndReturn(run func() error) *HubInterface_Start_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterRemoteService provides a mock function for the type HubInterface
func (_mock *HubInterface) UnregisterRemoteService(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubInterface_UnregisterRemoteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterRemoteService'
type HubInterface_UnregisterRemoteService_Call struct {
	*mock.Call
}

// UnregisterRemoteService is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubInterface_Expecter) UnregisterRemoteService(identity interface{}) *HubInterface_UnregisterRemoteService_Call {
	return &HubInterface_UnregisterRemoteService_Call{Call: _e.mock.On("UnregisterRemoteService", identity)}
}

func (_c *HubInterface_UnregisterRemoteService_Call) Run(run func(identity api.ServiceIdentity)) *HubInterface_UnregisterRemoteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubInterface_UnregisterRemoteService_Call) Return() *HubInterface_UnregisterRemoteService_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_UnregisterRemoteService_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubInterface_UnregisterRemoteService_Call {
	_c.Run(run)
	return _c
}
