// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewHubInterface creates a new instance of HubInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHubInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HubInterface {
	mock := &HubInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HubInterface is an autogenerated mock type for the HubInterface type
type HubInterface struct {
	mock.Mock
}

type HubInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *HubInterface) EXPECT() *HubInterface_Expecter {
	return &HubInterface_Expecter{mock: &_m.Mock}
}

// AddService provides a mock function for the type HubInterface
func (_mock *HubInterface) AddService(service *api.ServiceDetails) bool {
	ret := _mock.Called(service)

	if len(ret) == 0 {
		panic("no return value specified for AddService")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*api.ServiceDetails) bool); ok {
		r0 = returnFunc(service)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// HubInterface_AddService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddService'
type HubInterface_AddService_Call struct {
	*mock.Call
}

// AddService is a helper method to define mock.On call
//   - service *api.ServiceDetails
func (_e *HubInterface_Expecter) AddService(service interface{}) *HubInterface_AddService_Call {
	return &HubInterface_AddService_Call{Call: _e.mock.On("AddService", service)}
}

func (_c *HubInterface_AddService_Call) Run(run func(service *api.ServiceDetails)) *HubInterface_AddService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.ServiceDetails
		if args[0] != nil {
			arg0 = args[0].(*api.ServiceDetails)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubInterface_AddService_Call) Return(b bool) *HubInterface_AddService_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *HubInterface_AddService_Call) RunAndReturn(run func(service *api.ServiceDetails) bool) *HubInterface_AddService_Call {
	_c.Call.Return(run)
	return _c
}

// CancelPairingWithSKI provides a mock function for the type HubInterface
func (_mock *HubInterface) CancelPairingWithSKI(ski string) {
	_mock.Called(ski)
	return
}

// HubInterface_CancelPairingWithSKI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPairingWithSKI'
type HubInterface_CancelPairingWithSKI_Call struct {
	*mock.Call
}

// CancelPairingWithSKI is a helper method to define mock.On call
//   - ski string
func (_e *HubInterface_Expecter) CancelPairingWithSKI(ski interface{}) *HubInterface_CancelPairingWithSKI_Call {
	return &HubInterface_CancelPairingWithSKI_Call{Call: _e.mock.On("CancelPairingWithSKI", ski)}
}

func (_c *HubInterface_CancelPairingWithSKI_Call) Run(run func(ski string)) *HubInterface_CancelPairingWithSKI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubInterface_CancelPairingWithSKI_Call) Return() *HubInterface_CancelPairingWithSKI_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_CancelPairingWithSKI_Call) RunAndReturn(run func(ski string)) *HubInterface_CancelPairingWithSKI_Call {
	_c.Run(run)
	return _c
}

// DisconnectSKI provides a mock function for the type HubInterface
func (_mock *HubInterface) DisconnectSKI(ski string, reason string) {
	_mock.Called(ski, reason)
	return
}

// HubInterface_DisconnectSKI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectSKI'
type HubInterface_DisconnectSKI_Call struct {
	*mock.Call
}

// DisconnectSKI is a helper method to define mock.On call
//   - ski string
//   - reason string
func (_e *HubInterface_Expecter) DisconnectSKI(ski interface{}, reason interface{}) *HubInterface_DisconnectSKI_Call {
	return &HubInterface_DisconnectSKI_Call{Call: _e.mock.On("DisconnectSKI", ski, reason)}
}

func (_c *HubInterface_DisconnectSKI_Call) Run(run func(ski string, reason string)) *HubInterface_DisconnectSKI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubInterface_DisconnectSKI_Call) Return() *HubInterface_DisconnectSKI_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_DisconnectSKI_Call) RunAndReturn(run func(ski string, reason string)) *HubInterface_DisconnectSKI_Call {
	_c.Run(run)
	return _c
}

// PairingDetailForIdentifier provides a mock function for the type HubInterface
func (_mock *HubInterface) PairingDetailForIdentifier(ski string, fingerprint string) *api.ConnectionStateDetail {
	ret := _mock.Called(ski, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for PairingDetailForIdentifier")
	}

	var r0 *api.ConnectionStateDetail
	if returnFunc, ok := ret.Get(0).(func(string, string) *api.ConnectionStateDetail); ok {
		r0 = returnFunc(ski, fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ConnectionStateDetail)
		}
	}
	return r0
}

// HubInterface_PairingDetailForIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PairingDetailForIdentifier'
type HubInterface_PairingDetailForIdentifier_Call struct {
	*mock.Call
}

// PairingDetailForIdentifier is a helper method to define mock.On call
//   - ski string
//   - fingerprint string
func (_e *HubInterface_Expecter) PairingDetailForIdentifier(ski interface{}, fingerprint interface{}) *HubInterface_PairingDetailForIdentifier_Call {
	return &HubInterface_PairingDetailForIdentifier_Call{Call: _e.mock.On("PairingDetailForIdentifier", ski, fingerprint)}
}

func (_c *HubInterface_PairingDetailForIdentifier_Call) Run(run func(ski string, fingerprint string)) *HubInterface_PairingDetailForIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubInterface_PairingDetailForIdentifier_Call) Return(connectionStateDetail *api.ConnectionStateDetail) *HubInterface_PairingDetailForIdentifier_Call {
	_c.Call.Return(connectionStateDetail)
	return _c
}

func (_c *HubInterface_PairingDetailForIdentifier_Call) RunAndReturn(run func(ski string, fingerprint string) *api.ConnectionStateDetail) *HubInterface_PairingDetailForIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterRemoteService provides a mock function for the type HubInterface
func (_mock *HubInterface) RegisterRemoteService(ski string, fingerprint string, shipID string) {
	_mock.Called(ski, fingerprint, shipID)
	return
}

// HubInterface_RegisterRemoteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRemoteService'
type HubInterface_RegisterRemoteService_Call struct {
	*mock.Call
}

// RegisterRemoteService is a helper method to define mock.On call
//   - ski string
//   - fingerprint string
//   - shipID string
func (_e *HubInterface_Expecter) RegisterRemoteService(ski interface{}, fingerprint interface{}, shipID interface{}) *HubInterface_RegisterRemoteService_Call {
	return &HubInterface_RegisterRemoteService_Call{Call: _e.mock.On("RegisterRemoteService", ski, fingerprint, shipID)}
}

func (_c *HubInterface_RegisterRemoteService_Call) Run(run func(ski string, fingerprint string, shipID string)) *HubInterface_RegisterRemoteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *HubInterface_RegisterRemoteService_Call) Return() *HubInterface_RegisterRemoteService_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_RegisterRemoteService_Call) RunAndReturn(run func(ski string, fingerprint string, shipID string)) *HubInterface_RegisterRemoteService_Call {
	_c.Run(run)
	return _c
}

// RemoveService provides a mock function for the type HubInterface
func (_mock *HubInterface) RemoveService(ski string, fingerprint string) {
	_mock.Called(ski, fingerprint)
	return
}

// HubInterface_RemoveService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveService'
type HubInterface_RemoveService_Call struct {
	*mock.Call
}

// RemoveService is a helper method to define mock.On call
//   - ski string
//   - fingerprint string
func (_e *HubInterface_Expecter) RemoveService(ski interface{}, fingerprint interface{}) *HubInterface_RemoveService_Call {
	return &HubInterface_RemoveService_Call{Call: _e.mock.On("RemoveService", ski, fingerprint)}
}

func (_c *HubInterface_RemoveService_Call) Run(run func(ski string, fingerprint string)) *HubInterface_RemoveService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubInterface_RemoveService_Call) Return() *HubInterface_RemoveService_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_RemoveService_Call) RunAndReturn(run func(ski string, fingerprint string)) *HubInterface_RemoveService_Call {
	_c.Run(run)
	return _c
}

// ServiceForIdentifier provides a mock function for the type HubInterface
func (_mock *HubInterface) ServiceForIdentifier(ski string, fingerprint string) *api.ServiceDetails {
	ret := _mock.Called(ski, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for ServiceForIdentifier")
	}

	var r0 *api.ServiceDetails
	if returnFunc, ok := ret.Get(0).(func(string, string) *api.ServiceDetails); ok {
		r0 = returnFunc(ski, fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ServiceDetails)
		}
	}
	return r0
}

// HubInterface_ServiceForIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceForIdentifier'
type HubInterface_ServiceForIdentifier_Call struct {
	*mock.Call
}

// ServiceForIdentifier is a helper method to define mock.On call
//   - ski string
//   - fingerprint string
func (_e *HubInterface_Expecter) ServiceForIdentifier(ski interface{}, fingerprint interface{}) *HubInterface_ServiceForIdentifier_Call {
	return &HubInterface_ServiceForIdentifier_Call{Call: _e.mock.On("ServiceForIdentifier", ski, fingerprint)}
}

func (_c *HubInterface_ServiceForIdentifier_Call) Run(run func(ski string, fingerprint string)) *HubInterface_ServiceForIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubInterface_ServiceForIdentifier_Call) Return(serviceDetails *api.ServiceDetails) *HubInterface_ServiceForIdentifier_Call {
	_c.Call.Return(serviceDetails)
	return _c
}

func (_c *HubInterface_ServiceForIdentifier_Call) RunAndReturn(run func(ski string, fingerprint string) *api.ServiceDetails) *HubInterface_ServiceForIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// SetAutoAccept provides a mock function for the type HubInterface
func (_mock *HubInterface) SetAutoAccept(b bool) {
	_mock.Called(b)
	return
}

// HubInterface_SetAutoAccept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAutoAccept'
type HubInterface_SetAutoAccept_Call struct {
	*mock.Call
}

// SetAutoAccept is a helper method to define mock.On call
//   - b bool
func (_e *HubInterface_Expecter) SetAutoAccept(b interface{}) *HubInterface_SetAutoAccept_Call {
	return &HubInterface_SetAutoAccept_Call{Call: _e.mock.On("SetAutoAccept", b)}
}

func (_c *HubInterface_SetAutoAccept_Call) Run(run func(b bool)) *HubInterface_SetAutoAccept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubInterface_SetAutoAccept_Call) Return() *HubInterface_SetAutoAccept_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_SetAutoAccept_Call) RunAndReturn(run func(b bool)) *HubInterface_SetAutoAccept_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type HubInterface
func (_mock *HubInterface) Shutdown() {
	_mock.Called()
	return
}

// HubInterface_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type HubInterface_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *HubInterface_Expecter) Shutdown() *HubInterface_Shutdown_Call {
	return &HubInterface_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *HubInterface_Shutdown_Call) Run(run func()) *HubInterface_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HubInterface_Shutdown_Call) Return() *HubInterface_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_Shutdown_Call) RunAndReturn(run func()) *HubInterface_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type HubInterface
func (_mock *HubInterface) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HubInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type HubInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *HubInterface_Expecter) Start() *HubInterface_Start_Call {
	return &HubInterface_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *HubInterface_Start_Call) Run(run func()) *HubInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HubInterface_Start_Call) Return(err error) *HubInterface_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HubInterface_Start_Call) RunAndReturn(run func() error) *HubInterface_Start_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterRemoteService provides a mock function for the type HubInterface
func (_mock *HubInterface) UnregisterRemoteService(ski string, fingerprint string) {
	_mock.Called(ski, fingerprint)
	return
}

// HubInterface_UnregisterRemoteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterRemoteService'
type HubInterface_UnregisterRemoteService_Call struct {
	*mock.Call
}

// UnregisterRemoteService is a helper method to define mock.On call
//   - ski string
//   - fingerprint string
func (_e *HubInterface_Expecter) UnregisterRemoteService(ski interface{}, fingerprint interface{}) *HubInterface_UnregisterRemoteService_Call {
	return &HubInterface_UnregisterRemoteService_Call{Call: _e.mock.On("UnregisterRemoteService", ski, fingerprint)}
}

func (_c *HubInterface_UnregisterRemoteService_Call) Run(run func(ski string, fingerprint string)) *HubInterface_UnregisterRemoteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubInterface_UnregisterRemoteService_Call) Return() *HubInterface_UnregisterRemoteService_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubInterface_UnregisterRemoteService_Call) RunAndReturn(run func(ski string, fingerprint string)) *HubInterface_UnregisterRemoteService_Call {
	_c.Run(run)
	return _c
}
