// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewHubReaderServiceIdentityInterface creates a new instance of HubReaderServiceIdentityInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHubReaderServiceIdentityInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HubReaderServiceIdentityInterface {
	mock := &HubReaderServiceIdentityInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HubReaderServiceIdentityInterface is an autogenerated mock type for the HubReaderServiceIdentityInterface type
type HubReaderServiceIdentityInterface struct {
	mock.Mock
}

type HubReaderServiceIdentityInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *HubReaderServiceIdentityInterface) EXPECT() *HubReaderServiceIdentityInterface_Expecter {
	return &HubReaderServiceIdentityInterface_Expecter{mock: &_m.Mock}
}

// AllowWaitingForTrust provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) AllowWaitingForTrust(ski string) bool {
	ret := _mock.Called(ski)

	if len(ret) == 0 {
		panic("no return value specified for AllowWaitingForTrust")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(ski)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// HubReaderServiceIdentityInterface_AllowWaitingForTrust_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowWaitingForTrust'
type HubReaderServiceIdentityInterface_AllowWaitingForTrust_Call struct {
	*mock.Call
}

// AllowWaitingForTrust is a helper method to define mock.On call
//   - ski string
func (_e *HubReaderServiceIdentityInterface_Expecter) AllowWaitingForTrust(ski interface{}) *HubReaderServiceIdentityInterface_AllowWaitingForTrust_Call {
	return &HubReaderServiceIdentityInterface_AllowWaitingForTrust_Call{Call: _e.mock.On("AllowWaitingForTrust", ski)}
}

func (_c *HubReaderServiceIdentityInterface_AllowWaitingForTrust_Call) Run(run func(ski string)) *HubReaderServiceIdentityInterface_AllowWaitingForTrust_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_AllowWaitingForTrust_Call) Return(b bool) *HubReaderServiceIdentityInterface_AllowWaitingForTrust_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *HubReaderServiceIdentityInterface_AllowWaitingForTrust_Call) RunAndReturn(run func(ski string) bool) *HubReaderServiceIdentityInterface_AllowWaitingForTrust_Call {
	_c.Call.Return(run)
	return _c
}

// AllowWaitingForTrustIdentity provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) AllowWaitingForTrustIdentity(identity api.ServiceIdentity) bool {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for AllowWaitingForTrustIdentity")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.ServiceIdentity) bool); ok {
		r0 = returnFunc(identity)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// HubReaderServiceIdentityInterface_AllowWaitingForTrustIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowWaitingForTrustIdentity'
type HubReaderServiceIdentityInterface_AllowWaitingForTrustIdentity_Call struct {
	*mock.Call
}

// AllowWaitingForTrustIdentity is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubReaderServiceIdentityInterface_Expecter) AllowWaitingForTrustIdentity(identity interface{}) *HubReaderServiceIdentityInterface_AllowWaitingForTrustIdentity_Call {
	return &HubReaderServiceIdentityInterface_AllowWaitingForTrustIdentity_Call{Call: _e.mock.On("AllowWaitingForTrustIdentity", identity)}
}

func (_c *HubReaderServiceIdentityInterface_AllowWaitingForTrustIdentity_Call) Run(run func(identity api.ServiceIdentity)) *HubReaderServiceIdentityInterface_AllowWaitingForTrustIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_AllowWaitingForTrustIdentity_Call) Return(b bool) *HubReaderServiceIdentityInterface_AllowWaitingForTrustIdentity_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *HubReaderServiceIdentityInterface_AllowWaitingForTrustIdentity_Call) RunAndReturn(run func(identity api.ServiceIdentity) bool) *HubReaderServiceIdentityInterface_AllowWaitingForTrustIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteSKIConnected provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) RemoteSKIConnected(ski string) {
	_mock.Called(ski)
	return
}

// HubReaderServiceIdentityInterface_RemoteSKIConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteSKIConnected'
type HubReaderServiceIdentityInterface_RemoteSKIConnected_Call struct {
	*mock.Call
}

// RemoteSKIConnected is a helper method to define mock.On call
//   - ski string
func (_e *HubReaderServiceIdentityInterface_Expecter) RemoteSKIConnected(ski interface{}) *HubReaderServiceIdentityInterface_RemoteSKIConnected_Call {
	return &HubReaderServiceIdentityInterface_RemoteSKIConnected_Call{Call: _e.mock.On("RemoteSKIConnected", ski)}
}

func (_c *HubReaderServiceIdentityInterface_RemoteSKIConnected_Call) Run(run func(ski string)) *HubReaderServiceIdentityInterface_RemoteSKIConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_RemoteSKIConnected_Call) Return() *HubReaderServiceIdentityInterface_RemoteSKIConnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderServiceIdentityInterface_RemoteSKIConnected_Call) RunAndReturn(run func(ski string)) *HubReaderServiceIdentityInterface_RemoteSKIConnected_Call {
	_c.Run(run)
	return _c
}

// RemoteSKIDisconnected provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) RemoteSKIDisconnected(ski string) {
	_mock.Called(ski)
	return
}

// HubReaderServiceIdentityInterface_RemoteSKIDisconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteSKIDisconnected'
type HubReaderServiceIdentityInterface_RemoteSKIDisconnected_Call struct {
	*mock.Call
}

// RemoteSKIDisconnected is a helper method to define mock.On call
//   - ski string
func (_e *HubReaderServiceIdentityInterface_Expecter) RemoteSKIDisconnected(ski interface{}) *HubReaderServiceIdentityInterface_RemoteSKIDisconnected_Call {
	return &HubReaderServiceIdentityInterface_RemoteSKIDisconnected_Call{Call: _e.mock.On("RemoteSKIDisconnected", ski)}
}

func (_c *HubReaderServiceIdentityInterface_RemoteSKIDisconnected_Call) Run(run func(ski string)) *HubReaderServiceIdentityInterface_RemoteSKIDisconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_RemoteSKIDisconnected_Call) Return() *HubReaderServiceIdentityInterface_RemoteSKIDisconnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderServiceIdentityInterface_RemoteSKIDisconnected_Call) RunAndReturn(run func(ski string)) *HubReaderServiceIdentityInterface_RemoteSKIDisconnected_Call {
	_c.Run(run)
	return _c
}

// RemoteServiceConnected provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) RemoteServiceConnected(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubReaderServiceIdentityInterface_RemoteServiceConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteServiceConnected'
type HubReaderServiceIdentityInterface_RemoteServiceConnected_Call struct {
	*mock.Call
}

// RemoteServiceConnected is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubReaderServiceIdentityInterface_Expecter) RemoteServiceConnected(identity interface{}) *HubReaderServiceIdentityInterface_RemoteServiceConnected_Call {
	return &HubReaderServiceIdentityInterface_RemoteServiceConnected_Call{Call: _e.mock.On("RemoteServiceConnected", identity)}
}

func (_c *HubReaderServiceIdentityInterface_RemoteServiceConnected_Call) Run(run func(identity api.ServiceIdentity)) *HubReaderServiceIdentityInterface_RemoteServiceConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_RemoteServiceConnected_Call) Return() *HubReaderServiceIdentityInterface_RemoteServiceConnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderServiceIdentityInterface_RemoteServiceConnected_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubReaderServiceIdentityInterface_RemoteServiceConnected_Call {
	_c.Run(run)
	return _c
}

// RemoteServiceDisconnected provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) RemoteServiceDisconnected(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubReaderServiceIdentityInterface_RemoteServiceDisconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteServiceDisconnected'
type HubReaderServiceIdentityInterface_RemoteServiceDisconnected_Call struct {
	*mock.Call
}

// RemoteServiceDisconnected is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubReaderServiceIdentityInterface_Expecter) RemoteServiceDisconnected(identity interface{}) *HubReaderServiceIdentityInterface_RemoteServiceDisconnected_Call {
	return &HubReaderServiceIdentityInterface_RemoteServiceDisconnected_Call{Call: _e.mock.On("RemoteServiceDisconnected", identity)}
}

func (_c *HubReaderServiceIdentityInterface_RemoteServiceDisconnected_Call) Run(run func(identity api.ServiceIdentity)) *HubReaderServiceIdentityInterface_RemoteServiceDisconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_RemoteServiceDisconnected_Call) Return() *HubReaderServiceIdentityInterface_RemoteServiceDisconnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderServiceIdentityInterface_RemoteServiceDisconnected_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubReaderServiceIdentityInterface_RemoteServiceDisconnected_Call {
	_c.Run(run)
	return _c
}

// ServicePairingDetailUpdate provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) ServicePairingDetailUpdate(ski string, detail *api.ConnectionStateDetail) {
	_mock.Called(ski, detail)
	return
}

// HubReaderServiceIdentityInterface_ServicePairingDetailUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServicePairingDetailUpdate'
type HubReaderServiceIdentityInterface_ServicePairingDetailUpdate_Call struct {
	*mock.Call
}

// ServicePairingDetailUpdate is a helper method to define mock.On call
//   - ski string
//   - detail *api.ConnectionStateDetail
func (_e *HubReaderServiceIdentityInterface_Expecter) ServicePairingDetailUpdate(ski interface{}, detail interface{}) *HubReaderServiceIdentityInterface_ServicePairingDetailUpdate_Call {
	return &HubReaderServiceIdentityInterface_ServicePairingDetailUpdate_Call{Call: _e.mock.On("ServicePairingDetailUpdate", ski, detail)}
}

func (_c *HubReaderServiceIdentityInterface_ServicePairingDetailUpdate_Call) Run(run func(ski string, detail *api.ConnectionStateDetail)) *HubReaderServiceIdentityInterface_ServicePairingDetailUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *api.ConnectionStateDetail
		if args[1] != nil {
			arg1 = args[1].(*api.ConnectionStateDetail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_ServicePairingDetailUpdate_Call) Return() *HubReaderServiceIdentityInterface_ServicePairingDetailUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderServiceIdentityInterface_ServicePairingDetailUpdate_Call) RunAndReturn(run func(ski string, detail *api.ConnectionStateDetail)) *HubReaderServiceIdentityInterface_ServicePairingDetailUpdate_Call {
	_c.Run(run)
	return _c
}

// ServicePairingDetailUpdateIdentity provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) ServicePairingDetailUpdateIdentity(identity api.ServiceIdentity, detail *api.ConnectionStateDetail) {
	_mock.Called(identity, detail)
	return
}

// HubReaderServiceIdentityInterface_ServicePairingDetailUpdateIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServicePairingDetailUpdateIdentity'
type HubReaderServiceIdentityInterface_ServicePairingDetailUpdateIdentity_Call struct {
	*mock.Call
}

// ServicePairingDetailUpdateIdentity is a helper method to define mock.On call
//   - identity api.ServiceIdentity
//   - detail *api.ConnectionStateDetail
func (_e *HubReaderServiceIdentityInterface_Expecter) ServicePairingDetailUpdateIdentity(identity interface{}, detail interface{}) *HubReaderServiceIdentityInterface_ServicePairingDetailUpdateIdentity_Call {
	return &HubReaderServiceIdentityInterface_ServicePairingDetailUpdateIdentity_Call{Call: _e.mock.On("ServicePairingDetailUpdateIdentity", identity, detail)}
}

func (_c *HubReaderServiceIdentityInterface_ServicePairingDetailUpdateIdentity_Call) Run(run func(identity api.ServiceIdentity, detail *api.ConnectionStateDetail)) *HubReaderServiceIdentityInterface_ServicePairingDetailUpdateIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		var arg1 *api.ConnectionStateDetail
		if args[1] != nil {
			arg1 = args[1].(*api.ConnectionStateDetail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_ServicePairingDetailUpdateIdentity_Call) Return() *HubReaderServiceIdentityInterface_ServicePairingDetailUpdateIdentity_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderServiceIdentityInterface_ServicePairingDetailUpdateIdentity_Call) RunAndReturn(run func(identity api.ServiceIdentity, detail *api.ConnectionStateDetail)) *HubReaderServiceIdentityInterface_ServicePairingDetailUpdateIdentity_Call {
	_c.Run(run)
	return _c
}

// ServiceShipIDUpdate provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) ServiceShipIDUpdate(ski string, shipdID string) {
	_mock.Called(ski, shipdID)
	return
}

// HubReaderServiceIdentityInterface_ServiceShipIDUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceShipIDUpdate'
type HubReaderServiceIdentityInterface_ServiceShipIDUpdate_Call struct {
	*mock.Call
}

// ServiceShipIDUpdate is a helper method to define mock.On call
//   - ski string
//   - shipdID string
func (_e *HubReaderServiceIdentityInterface_Expecter) ServiceShipIDUpdate(ski interface{}, shipdID interface{}) *HubReaderServiceIdentityInterface_ServiceShipIDUpdate_Call {
	return &HubReaderServiceIdentityInterface_ServiceShipIDUpdate_Call{Call: _e.mock.On("ServiceShipIDUpdate", ski, shipdID)}
}

func (_c *HubReaderServiceIdentityInterface_ServiceShipIDUpdate_Call) Run(run func(ski string, shipdID string)) *HubReaderServiceIdentityInterface_ServiceShipIDUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_ServiceShipIDUpdate_Call) Return() *HubReaderServiceIdentityInterface_ServiceShipIDUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderServiceIdentityInterface_ServiceShipIDUpdate_Call) RunAndReturn(run func(ski string, shipdID string)) *HubReaderServiceIdentityInterface_ServiceShipIDUpdate_Call {
	_c.Run(run)
	return _c
}

// ServiceUpdated provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) ServiceUpdated(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubReaderServiceIdentityInterface_ServiceUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceUpdated'
type HubReaderServiceIdentityInterface_ServiceUpdated_Call struct {
	*mock.Call
}

// ServiceUpdated is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubReaderServiceIdentityInterface_Expecter) ServiceUpdated(identity interface{}) *HubReaderServiceIdentityInterface_ServiceUpdated_Call {
	return &HubReaderServiceIdentityInterface_ServiceUpdated_Call{Call: _e.mock.On("ServiceUpdated", identity)}
}

func (_c *HubReaderServiceIdentityInterface_ServiceUpdated_Call) Run(run func(identity api.ServiceIdentity)) *HubReaderServiceIdentityInterface_ServiceUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_ServiceUpdated_Call) Return() *HubReaderServiceIdentityInterface_ServiceUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderServiceIdentityInterface_ServiceUpdated_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubReaderServiceIdentityInterface_ServiceUpdated_Call {
	_c.Run(run)
	return _c
}

// SetupRemoteDevice provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) SetupRemoteDevice(ski string, writeI api.ShipConnectionDataWriterInterface) api.ShipConnectionDataReaderInterface {
	ret := _mock.Called(ski, writeI)

	if len(ret) == 0 {
		panic("no return value specified for SetupRemoteDevice")
	}

	var r0 api.ShipConnectionDataReaderInterface
	if returnFunc, ok := ret.Get(0).(func(string, api.ShipConnectionDataWriterInterface) api.ShipConnectionDataReaderInterface); ok {
		r0 = returnFunc(ski, writeI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.ShipConnectionDataReaderInterface)
		}
	}
	return r0
}

// HubReaderServiceIdentityInterface_SetupRemoteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupRemoteDevice'
type HubReaderServiceIdentityInterface_SetupRemoteDevice_Call struct {
	*mock.Call
}

// SetupRemoteDevice is a helper method to define mock.On call
//   - ski string
//   - writeI api.ShipConnectionDataWriterInterface
func (_e *HubReaderServiceIdentityInterface_Expecter) SetupRemoteDevice(ski interface{}, writeI interface{}) *HubReaderServiceIdentityInterface_SetupRemoteDevice_Call {
	return &HubReaderServiceIdentityInterface_SetupRemoteDevice_Call{Call: _e.mock.On("SetupRemoteDevice", ski, writeI)}
}

func (_c *HubReaderServiceIdentityInterface_SetupRemoteDevice_Call) Run(run func(ski string, writeI api.ShipConnectionDataWriterInterface)) *HubReaderServiceIdentityInterface_SetupRemoteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 api.ShipConnectionDataWriterInterface
		if args[1] != nil {
			arg1 = args[1].(api.ShipConnectionDataWriterInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_SetupRemoteDevice_Call) Return(shipConnectionDataReaderInterface api.ShipConnectionDataReaderInterface) *HubReaderServiceIdentityInterface_SetupRemoteDevice_Call {
	_c.Call.Return(shipConnectionDataReaderInterface)
	return _c
}

func (_c *HubReaderServiceIdentityInterface_SetupRemoteDevice_Call) RunAndReturn(run func(ski string, writeI api.ShipConnectionDataWriterInterface) api.ShipConnectionDataReaderInterface) *HubReaderServiceIdentityInterface_SetupRemoteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// VisibleRemoteMdnsServicesUpdated provides a mock function for the type HubReaderServiceIdentityInterface
func (_mock *HubReaderServiceIdentityInterface) VisibleRemoteMdnsServicesUpdated(entries []api.RemoteMdnsService) {
	_mock.Called(entries)
	return
}

// HubReaderServiceIdentityInterface_VisibleRemoteMdnsServicesUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisibleRemoteMdnsServicesUpdated'
type HubReaderServiceIdentityInterface_VisibleRemoteMdnsServicesUpdated_Call struct {
	*mock.Call
}

// VisibleRemoteMdnsServicesUpdated is a helper method to define mock.On call
//   - entries []api.RemoteMdnsService
func (_e *HubReaderServiceIdentityInterface_Expecter) VisibleRemoteMdnsServicesUpdated(entries interface{}) *HubReaderServiceIdentityInterface_VisibleRemoteMdnsServicesUpdated_Call {
	return &HubReaderServiceIdentityInterface_VisibleRemoteMdnsServicesUpdated_Call{Call: _e.mock.On("VisibleRemoteMdnsServicesUpdated", entries)}
}

func (_c *HubReaderServiceIdentityInterface_VisibleRemoteMdnsServicesUpdated_Call) Run(run func(entries []api.RemoteMdnsService)) *HubReaderServiceIdentityInterface_VisibleRemoteMdnsServicesUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []api.RemoteMdnsService
		if args[0] != nil {
			arg0 = args[0].([]api.RemoteMdnsService)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderServiceIdentityInterface_VisibleRemoteMdnsServicesUpdated_Call) Return() *HubReaderServiceIdentityInterface_VisibleRemoteMdnsServicesUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderServiceIdentityInterface_VisibleRemoteMdnsServicesUpdated_Call) RunAndReturn(run func(entries []api.RemoteMdnsService)) *HubReaderServiceIdentityInterface_VisibleRemoteMdnsServicesUpdated_Call {
	_c.Run(run)
	return _c
}
