// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewHubReaderInterface creates a new instance of HubReaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHubReaderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HubReaderInterface {
	mock := &HubReaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HubReaderInterface is an autogenerated mock type for the HubReaderInterface type
type HubReaderInterface struct {
	mock.Mock
}

type HubReaderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *HubReaderInterface) EXPECT() *HubReaderInterface_Expecter {
	return &HubReaderInterface_Expecter{mock: &_m.Mock}
}

// AllowWaitingForTrust provides a mock function for the type HubReaderInterface
func (_mock *HubReaderInterface) AllowWaitingForTrust(identity api.ServiceIdentity) bool {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for AllowWaitingForTrust")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.ServiceIdentity) bool); ok {
		r0 = returnFunc(identity)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// HubReaderInterface_AllowWaitingForTrust_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowWaitingForTrust'
type HubReaderInterface_AllowWaitingForTrust_Call struct {
	*mock.Call
}

// AllowWaitingForTrust is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubReaderInterface_Expecter) AllowWaitingForTrust(identity interface{}) *HubReaderInterface_AllowWaitingForTrust_Call {
	return &HubReaderInterface_AllowWaitingForTrust_Call{Call: _e.mock.On("AllowWaitingForTrust", identity)}
}

func (_c *HubReaderInterface_AllowWaitingForTrust_Call) Run(run func(identity api.ServiceIdentity)) *HubReaderInterface_AllowWaitingForTrust_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderInterface_AllowWaitingForTrust_Call) Return(b bool) *HubReaderInterface_AllowWaitingForTrust_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *HubReaderInterface_AllowWaitingForTrust_Call) RunAndReturn(run func(identity api.ServiceIdentity) bool) *HubReaderInterface_AllowWaitingForTrust_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteServiceConnected provides a mock function for the type HubReaderInterface
func (_mock *HubReaderInterface) RemoteServiceConnected(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubReaderInterface_RemoteServiceConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteServiceConnected'
type HubReaderInterface_RemoteServiceConnected_Call struct {
	*mock.Call
}

// RemoteServiceConnected is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubReaderInterface_Expecter) RemoteServiceConnected(identity interface{}) *HubReaderInterface_RemoteServiceConnected_Call {
	return &HubReaderInterface_RemoteServiceConnected_Call{Call: _e.mock.On("RemoteServiceConnected", identity)}
}

func (_c *HubReaderInterface_RemoteServiceConnected_Call) Run(run func(identity api.ServiceIdentity)) *HubReaderInterface_RemoteServiceConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderInterface_RemoteServiceConnected_Call) Return() *HubReaderInterface_RemoteServiceConnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderInterface_RemoteServiceConnected_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubReaderInterface_RemoteServiceConnected_Call {
	_c.Run(run)
	return _c
}

// RemoteServiceDisconnected provides a mock function for the type HubReaderInterface
func (_mock *HubReaderInterface) RemoteServiceDisconnected(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubReaderInterface_RemoteServiceDisconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteServiceDisconnected'
type HubReaderInterface_RemoteServiceDisconnected_Call struct {
	*mock.Call
}

// RemoteServiceDisconnected is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubReaderInterface_Expecter) RemoteServiceDisconnected(identity interface{}) *HubReaderInterface_RemoteServiceDisconnected_Call {
	return &HubReaderInterface_RemoteServiceDisconnected_Call{Call: _e.mock.On("RemoteServiceDisconnected", identity)}
}

func (_c *HubReaderInterface_RemoteServiceDisconnected_Call) Run(run func(identity api.ServiceIdentity)) *HubReaderInterface_RemoteServiceDisconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderInterface_RemoteServiceDisconnected_Call) Return() *HubReaderInterface_RemoteServiceDisconnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderInterface_RemoteServiceDisconnected_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubReaderInterface_RemoteServiceDisconnected_Call {
	_c.Run(run)
	return _c
}

// ServicePairingDetailUpdate provides a mock function for the type HubReaderInterface
func (_mock *HubReaderInterface) ServicePairingDetailUpdate(identity api.ServiceIdentity, detail *api.ConnectionStateDetail) {
	_mock.Called(identity, detail)
	return
}

// HubReaderInterface_ServicePairingDetailUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServicePairingDetailUpdate'
type HubReaderInterface_ServicePairingDetailUpdate_Call struct {
	*mock.Call
}

// ServicePairingDetailUpdate is a helper method to define mock.On call
//   - identity api.ServiceIdentity
//   - detail *api.ConnectionStateDetail
func (_e *HubReaderInterface_Expecter) ServicePairingDetailUpdate(identity interface{}, detail interface{}) *HubReaderInterface_ServicePairingDetailUpdate_Call {
	return &HubReaderInterface_ServicePairingDetailUpdate_Call{Call: _e.mock.On("ServicePairingDetailUpdate", identity, detail)}
}

func (_c *HubReaderInterface_ServicePairingDetailUpdate_Call) Run(run func(identity api.ServiceIdentity, detail *api.ConnectionStateDetail)) *HubReaderInterface_ServicePairingDetailUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		var arg1 *api.ConnectionStateDetail
		if args[1] != nil {
			arg1 = args[1].(*api.ConnectionStateDetail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubReaderInterface_ServicePairingDetailUpdate_Call) Return() *HubReaderInterface_ServicePairingDetailUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderInterface_ServicePairingDetailUpdate_Call) RunAndReturn(run func(identity api.ServiceIdentity, detail *api.ConnectionStateDetail)) *HubReaderInterface_ServicePairingDetailUpdate_Call {
	_c.Run(run)
	return _c
}

// ServiceUpdated provides a mock function for the type HubReaderInterface
func (_mock *HubReaderInterface) ServiceUpdated(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubReaderInterface_ServiceUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceUpdated'
type HubReaderInterface_ServiceUpdated_Call struct {
	*mock.Call
}

// ServiceUpdated is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubReaderInterface_Expecter) ServiceUpdated(identity interface{}) *HubReaderInterface_ServiceUpdated_Call {
	return &HubReaderInterface_ServiceUpdated_Call{Call: _e.mock.On("ServiceUpdated", identity)}
}

func (_c *HubReaderInterface_ServiceUpdated_Call) Run(run func(identity api.ServiceIdentity)) *HubReaderInterface_ServiceUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderInterface_ServiceUpdated_Call) Return() *HubReaderInterface_ServiceUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderInterface_ServiceUpdated_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubReaderInterface_ServiceUpdated_Call {
	_c.Run(run)
	return _c
}

// SetupRemoteService provides a mock function for the type HubReaderInterface
func (_mock *HubReaderInterface) SetupRemoteService(identity api.ServiceIdentity, writeI api.ShipConnectionDataWriterInterface) api.ShipConnectionDataReaderInterface {
	ret := _mock.Called(identity, writeI)

	if len(ret) == 0 {
		panic("no return value specified for SetupRemoteService")
	}

	var r0 api.ShipConnectionDataReaderInterface
	if returnFunc, ok := ret.Get(0).(func(api.ServiceIdentity, api.ShipConnectionDataWriterInterface) api.ShipConnectionDataReaderInterface); ok {
		r0 = returnFunc(identity, writeI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.ShipConnectionDataReaderInterface)
		}
	}
	return r0
}

// HubReaderInterface_SetupRemoteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupRemoteService'
type HubReaderInterface_SetupRemoteService_Call struct {
	*mock.Call
}

// SetupRemoteService is a helper method to define mock.On call
//   - identity api.ServiceIdentity
//   - writeI api.ShipConnectionDataWriterInterface
func (_e *HubReaderInterface_Expecter) SetupRemoteService(identity interface{}, writeI interface{}) *HubReaderInterface_SetupRemoteService_Call {
	return &HubReaderInterface_SetupRemoteService_Call{Call: _e.mock.On("SetupRemoteService", identity, writeI)}
}

func (_c *HubReaderInterface_SetupRemoteService_Call) Run(run func(identity api.ServiceIdentity, writeI api.ShipConnectionDataWriterInterface)) *HubReaderInterface_SetupRemoteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		var arg1 api.ShipConnectionDataWriterInterface
		if args[1] != nil {
			arg1 = args[1].(api.ShipConnectionDataWriterInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubReaderInterface_SetupRemoteService_Call) Return(shipConnectionDataReaderInterface api.ShipConnectionDataReaderInterface) *HubReaderInterface_SetupRemoteService_Call {
	_c.Call.Return(shipConnectionDataReaderInterface)
	return _c
}

func (_c *HubReaderInterface_SetupRemoteService_Call) RunAndReturn(run func(identity api.ServiceIdentity, writeI api.ShipConnectionDataWriterInterface) api.ShipConnectionDataReaderInterface) *HubReaderInterface_SetupRemoteService_Call {
	_c.Call.Return(run)
	return _c
}

// VisibleRemoteMdnsServicesUpdated provides a mock function for the type HubReaderInterface
func (_mock *HubReaderInterface) VisibleRemoteMdnsServicesUpdated(entries []api.RemoteMdnsService) {
	_mock.Called(entries)
	return
}

// HubReaderInterface_VisibleRemoteMdnsServicesUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisibleRemoteMdnsServicesUpdated'
type HubReaderInterface_VisibleRemoteMdnsServicesUpdated_Call struct {
	*mock.Call
}

// VisibleRemoteMdnsServicesUpdated is a helper method to define mock.On call
//   - entries []api.RemoteMdnsService
func (_e *HubReaderInterface_Expecter) VisibleRemoteMdnsServicesUpdated(entries interface{}) *HubReaderInterface_VisibleRemoteMdnsServicesUpdated_Call {
	return &HubReaderInterface_VisibleRemoteMdnsServicesUpdated_Call{Call: _e.mock.On("VisibleRemoteMdnsServicesUpdated", entries)}
}

func (_c *HubReaderInterface_VisibleRemoteMdnsServicesUpdated_Call) Run(run func(entries []api.RemoteMdnsService)) *HubReaderInterface_VisibleRemoteMdnsServicesUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []api.RemoteMdnsService
		if args[0] != nil {
			arg0 = args[0].([]api.RemoteMdnsService)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubReaderInterface_VisibleRemoteMdnsServicesUpdated_Call) Return() *HubReaderInterface_VisibleRemoteMdnsServicesUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubReaderInterface_VisibleRemoteMdnsServicesUpdated_Call) RunAndReturn(run func(entries []api.RemoteMdnsService)) *HubReaderInterface_VisibleRemoteMdnsServicesUpdated_Call {
	_c.Run(run)
	return _c
}
