// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewHubServiceIdentityInterface creates a new instance of HubServiceIdentityInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHubServiceIdentityInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HubServiceIdentityInterface {
	mock := &HubServiceIdentityInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HubServiceIdentityInterface is an autogenerated mock type for the HubServiceIdentityInterface type
type HubServiceIdentityInterface struct {
	mock.Mock
}

type HubServiceIdentityInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *HubServiceIdentityInterface) EXPECT() *HubServiceIdentityInterface_Expecter {
	return &HubServiceIdentityInterface_Expecter{mock: &_m.Mock}
}

// CancelPairingWithSKI provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) CancelPairingWithSKI(ski string) {
	_mock.Called(ski)
	return
}

// HubServiceIdentityInterface_CancelPairingWithSKI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPairingWithSKI'
type HubServiceIdentityInterface_CancelPairingWithSKI_Call struct {
	*mock.Call
}

// CancelPairingWithSKI is a helper method to define mock.On call
//   - ski string
func (_e *HubServiceIdentityInterface_Expecter) CancelPairingWithSKI(ski interface{}) *HubServiceIdentityInterface_CancelPairingWithSKI_Call {
	return &HubServiceIdentityInterface_CancelPairingWithSKI_Call{Call: _e.mock.On("CancelPairingWithSKI", ski)}
}

func (_c *HubServiceIdentityInterface_CancelPairingWithSKI_Call) Run(run func(ski string)) *HubServiceIdentityInterface_CancelPairingWithSKI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_CancelPairingWithSKI_Call) Return() *HubServiceIdentityInterface_CancelPairingWithSKI_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubServiceIdentityInterface_CancelPairingWithSKI_Call) RunAndReturn(run func(ski string)) *HubServiceIdentityInterface_CancelPairingWithSKI_Call {
	_c.Run(run)
	return _c
}

// CancelPairingWithServiceIdentity provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) CancelPairingWithServiceIdentity(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubServiceIdentityInterface_CancelPairingWithServiceIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPairingWithServiceIdentity'
type HubServiceIdentityInterface_CancelPairingWithServiceIdentity_Call struct {
	*mock.Call
}

// CancelPairingWithServiceIdentity is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubServiceIdentityInterface_Expecter) CancelPairingWithServiceIdentity(identity interface{}) *HubServiceIdentityInterface_CancelPairingWithServiceIdentity_Call {
	return &HubServiceIdentityInterface_CancelPairingWithServiceIdentity_Call{Call: _e.mock.On("CancelPairingWithServiceIdentity", identity)}
}

func (_c *HubServiceIdentityInterface_CancelPairingWithServiceIdentity_Call) Run(run func(identity api.ServiceIdentity)) *HubServiceIdentityInterface_CancelPairingWithServiceIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_CancelPairingWithServiceIdentity_Call) Return() *HubServiceIdentityInterface_CancelPairingWithServiceIdentity_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubServiceIdentityInterface_CancelPairingWithServiceIdentity_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubServiceIdentityInterface_CancelPairingWithServiceIdentity_Call {
	_c.Run(run)
	return _c
}

// DisconnectSKI provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) DisconnectSKI(ski string, reason string) {
	_mock.Called(ski, reason)
	return
}

// HubServiceIdentityInterface_DisconnectSKI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectSKI'
type HubServiceIdentityInterface_DisconnectSKI_Call struct {
	*mock.Call
}

// DisconnectSKI is a helper method to define mock.On call
//   - ski string
//   - reason string
func (_e *HubServiceIdentityInterface_Expecter) DisconnectSKI(ski interface{}, reason interface{}) *HubServiceIdentityInterface_DisconnectSKI_Call {
	return &HubServiceIdentityInterface_DisconnectSKI_Call{Call: _e.mock.On("DisconnectSKI", ski, reason)}
}

func (_c *HubServiceIdentityInterface_DisconnectSKI_Call) Run(run func(ski string, reason string)) *HubServiceIdentityInterface_DisconnectSKI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_DisconnectSKI_Call) Return() *HubServiceIdentityInterface_DisconnectSKI_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubServiceIdentityInterface_DisconnectSKI_Call) RunAndReturn(run func(ski string, reason string)) *HubServiceIdentityInterface_DisconnectSKI_Call {
	_c.Run(run)
	return _c
}

// DisconnectServiceIdentity provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) DisconnectServiceIdentity(identity api.ServiceIdentity, reason string) {
	_mock.Called(identity, reason)
	return
}

// HubServiceIdentityInterface_DisconnectServiceIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectServiceIdentity'
type HubServiceIdentityInterface_DisconnectServiceIdentity_Call struct {
	*mock.Call
}

// DisconnectServiceIdentity is a helper method to define mock.On call
//   - identity api.ServiceIdentity
//   - reason string
func (_e *HubServiceIdentityInterface_Expecter) DisconnectServiceIdentity(identity interface{}, reason interface{}) *HubServiceIdentityInterface_DisconnectServiceIdentity_Call {
	return &HubServiceIdentityInterface_DisconnectServiceIdentity_Call{Call: _e.mock.On("DisconnectServiceIdentity", identity, reason)}
}

func (_c *HubServiceIdentityInterface_DisconnectServiceIdentity_Call) Run(run func(identity api.ServiceIdentity, reason string)) *HubServiceIdentityInterface_DisconnectServiceIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_DisconnectServiceIdentity_Call) Return() *HubServiceIdentityInterface_DisconnectServiceIdentity_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubServiceIdentityInterface_DisconnectServiceIdentity_Call) RunAndReturn(run func(identity api.ServiceIdentity, reason string)) *HubServiceIdentityInterface_DisconnectServiceIdentity_Call {
	_c.Run(run)
	return _c
}

// PairingDetailFor provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) PairingDetailFor(identity api.ServiceIdentity) *api.ConnectionStateDetail {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for PairingDetailFor")
	}

	var r0 *api.ConnectionStateDetail
	if returnFunc, ok := ret.Get(0).(func(api.ServiceIdentity) *api.ConnectionStateDetail); ok {
		r0 = returnFunc(identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ConnectionStateDetail)
		}
	}
	return r0
}

// HubServiceIdentityInterface_PairingDetailFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PairingDetailFor'
type HubServiceIdentityInterface_PairingDetailFor_Call struct {
	*mock.Call
}

// PairingDetailFor is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubServiceIdentityInterface_Expecter) PairingDetailFor(identity interface{}) *HubServiceIdentityInterface_PairingDetailFor_Call {
	return &HubServiceIdentityInterface_PairingDetailFor_Call{Call: _e.mock.On("PairingDetailFor", identity)}
}

func (_c *HubServiceIdentityInterface_PairingDetailFor_Call) Run(run func(identity api.ServiceIdentity)) *HubServiceIdentityInterface_PairingDetailFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_PairingDetailFor_Call) Return(connectionStateDetail *api.ConnectionStateDetail) *HubServiceIdentityInterface_PairingDetailFor_Call {
	_c.Call.Return(connectionStateDetail)
	return _c
}

func (_c *HubServiceIdentityInterface_PairingDetailFor_Call) RunAndReturn(run func(identity api.ServiceIdentity) *api.ConnectionStateDetail) *HubServiceIdentityInterface_PairingDetailFor_Call {
	_c.Call.Return(run)
	return _c
}

// PairingDetailForIdentifier provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) PairingDetailForIdentifier(ski string, fingerprint string) *api.ConnectionStateDetail {
	ret := _mock.Called(ski, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for PairingDetailForIdentifier")
	}

	var r0 *api.ConnectionStateDetail
	if returnFunc, ok := ret.Get(0).(func(string, string) *api.ConnectionStateDetail); ok {
		r0 = returnFunc(ski, fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ConnectionStateDetail)
		}
	}
	return r0
}

// HubServiceIdentityInterface_PairingDetailForIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PairingDetailForIdentifier'
type HubServiceIdentityInterface_PairingDetailForIdentifier_Call struct {
	*mock.Call
}

// PairingDetailForIdentifier is a helper method to define mock.On call
//   - ski string
//   - fingerprint string
func (_e *HubServiceIdentityInterface_Expecter) PairingDetailForIdentifier(ski interface{}, fingerprint interface{}) *HubServiceIdentityInterface_PairingDetailForIdentifier_Call {
	return &HubServiceIdentityInterface_PairingDetailForIdentifier_Call{Call: _e.mock.On("PairingDetailForIdentifier", ski, fingerprint)}
}

func (_c *HubServiceIdentityInterface_PairingDetailForIdentifier_Call) Run(run func(ski string, fingerprint string)) *HubServiceIdentityInterface_PairingDetailForIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_PairingDetailForIdentifier_Call) Return(connectionStateDetail *api.ConnectionStateDetail) *HubServiceIdentityInterface_PairingDetailForIdentifier_Call {
	_c.Call.Return(connectionStateDetail)
	return _c
}

func (_c *HubServiceIdentityInterface_PairingDetailForIdentifier_Call) RunAndReturn(run func(ski string, fingerprint string) *api.ConnectionStateDetail) *HubServiceIdentityInterface_PairingDetailForIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterRemoteService provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) RegisterRemoteService(ski string, fingerprint string, shipID string) {
	_mock.Called(ski, fingerprint, shipID)
	return
}

// HubServiceIdentityInterface_RegisterRemoteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRemoteService'
type HubServiceIdentityInterface_RegisterRemoteService_Call struct {
	*mock.Call
}

// RegisterRemoteService is a helper method to define mock.On call
//   - ski string
//   - fingerprint string
//   - shipID string
func (_e *HubServiceIdentityInterface_Expecter) RegisterRemoteService(ski interface{}, fingerprint interface{}, shipID interface{}) *HubServiceIdentityInterface_RegisterRemoteService_Call {
	return &HubServiceIdentityInterface_RegisterRemoteService_Call{Call: _e.mock.On("RegisterRemoteService", ski, fingerprint, shipID)}
}

func (_c *HubServiceIdentityInterface_RegisterRemoteService_Call) Run(run func(ski string, fingerprint string, shipID string)) *HubServiceIdentityInterface_RegisterRemoteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_RegisterRemoteService_Call) Return() *HubServiceIdentityInterface_RegisterRemoteService_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubServiceIdentityInterface_RegisterRemoteService_Call) RunAndReturn(run func(ski string, fingerprint string, shipID string)) *HubServiceIdentityInterface_RegisterRemoteService_Call {
	_c.Run(run)
	return _c
}

// RegisterRemoteServiceIdentity provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) RegisterRemoteServiceIdentity(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubServiceIdentityInterface_RegisterRemoteServiceIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRemoteServiceIdentity'
type HubServiceIdentityInterface_RegisterRemoteServiceIdentity_Call struct {
	*mock.Call
}

// RegisterRemoteServiceIdentity is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubServiceIdentityInterface_Expecter) RegisterRemoteServiceIdentity(identity interface{}) *HubServiceIdentityInterface_RegisterRemoteServiceIdentity_Call {
	return &HubServiceIdentityInterface_RegisterRemoteServiceIdentity_Call{Call: _e.mock.On("RegisterRemoteServiceIdentity", identity)}
}

func (_c *HubServiceIdentityInterface_RegisterRemoteServiceIdentity_Call) Run(run func(identity api.ServiceIdentity)) *HubServiceIdentityInterface_RegisterRemoteServiceIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_RegisterRemoteServiceIdentity_Call) Return() *HubServiceIdentityInterface_RegisterRemoteServiceIdentity_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubServiceIdentityInterface_RegisterRemoteServiceIdentity_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubServiceIdentityInterface_RegisterRemoteServiceIdentity_Call {
	_c.Run(run)
	return _c
}

// ServiceFor provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) ServiceFor(identity api.ServiceIdentity) *api.ServiceDetails {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for ServiceFor")
	}

	var r0 *api.ServiceDetails
	if returnFunc, ok := ret.Get(0).(func(api.ServiceIdentity) *api.ServiceDetails); ok {
		r0 = returnFunc(identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ServiceDetails)
		}
	}
	return r0
}

// HubServiceIdentityInterface_ServiceFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceFor'
type HubServiceIdentityInterface_ServiceFor_Call struct {
	*mock.Call
}

// ServiceFor is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubServiceIdentityInterface_Expecter) ServiceFor(identity interface{}) *HubServiceIdentityInterface_ServiceFor_Call {
	return &HubServiceIdentityInterface_ServiceFor_Call{Call: _e.mock.On("ServiceFor", identity)}
}

func (_c *HubServiceIdentityInterface_ServiceFor_Call) Run(run func(identity api.ServiceIdentity)) *HubServiceIdentityInterface_ServiceFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_ServiceFor_Call) Return(serviceDetails *api.ServiceDetails) *HubServiceIdentityInterface_ServiceFor_Call {
	_c.Call.Return(serviceDetails)
	return _c
}

func (_c *HubServiceIdentityInterface_ServiceFor_Call) RunAndReturn(run func(identity api.ServiceIdentity) *api.ServiceDetails) *HubServiceIdentityInterface_ServiceFor_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceForIdentifier provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) ServiceForIdentifier(ski string, fingerprint string) *api.ServiceDetails {
	ret := _mock.Called(ski, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for ServiceForIdentifier")
	}

	var r0 *api.ServiceDetails
	if returnFunc, ok := ret.Get(0).(func(string, string) *api.ServiceDetails); ok {
		r0 = returnFunc(ski, fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ServiceDetails)
		}
	}
	return r0
}

// HubServiceIdentityInterface_ServiceForIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceForIdentifier'
type HubServiceIdentityInterface_ServiceForIdentifier_Call struct {
	*mock.Call
}

// ServiceForIdentifier is a helper method to define mock.On call
//   - ski string
//   - fingerprint string
func (_e *HubServiceIdentityInterface_Expecter) ServiceForIdentifier(ski interface{}, fingerprint interface{}) *HubServiceIdentityInterface_ServiceForIdentifier_Call {
	return &HubServiceIdentityInterface_ServiceForIdentifier_Call{Call: _e.mock.On("ServiceForIdentifier", ski, fingerprint)}
}

func (_c *HubServiceIdentityInterface_ServiceForIdentifier_Call) Run(run func(ski string, fingerprint string)) *HubServiceIdentityInterface_ServiceForIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_ServiceForIdentifier_Call) Return(serviceDetails *api.ServiceDetails) *HubServiceIdentityInterface_ServiceForIdentifier_Call {
	_c.Call.Return(serviceDetails)
	return _c
}

func (_c *HubServiceIdentityInterface_ServiceForIdentifier_Call) RunAndReturn(run func(ski string, fingerprint string) *api.ServiceDetails) *HubServiceIdentityInterface_ServiceForIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// SetAutoAccept provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) SetAutoAccept(b bool) {
	_mock.Called(b)
	return
}

// HubServiceIdentityInterface_SetAutoAccept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAutoAccept'
type HubServiceIdentityInterface_SetAutoAccept_Call struct {
	*mock.Call
}

// SetAutoAccept is a helper method to define mock.On call
//   - b bool
func (_e *HubServiceIdentityInterface_Expecter) SetAutoAccept(b interface{}) *HubServiceIdentityInterface_SetAutoAccept_Call {
	return &HubServiceIdentityInterface_SetAutoAccept_Call{Call: _e.mock.On("SetAutoAccept", b)}
}

func (_c *HubServiceIdentityInterface_SetAutoAccept_Call) Run(run func(b bool)) *HubServiceIdentityInterface_SetAutoAccept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_SetAutoAccept_Call) Return() *HubServiceIdentityInterface_SetAutoAccept_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubServiceIdentityInterface_SetAutoAccept_Call) RunAndReturn(run func(b bool)) *HubServiceIdentityInterface_SetAutoAccept_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) Shutdown() {
	_mock.Called()
	return
}

// HubServiceIdentityInterface_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type HubServiceIdentityInterface_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *HubServiceIdentityInterface_Expecter) Shutdown() *HubServiceIdentityInterface_Shutdown_Call {
	return &HubServiceIdentityInterface_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *HubServiceIdentityInterface_Shutdown_Call) Run(run func()) *HubServiceIdentityInterface_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HubServiceIdentityInterface_Shutdown_Call) Return() *HubServiceIdentityInterface_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubServiceIdentityInterface_Shutdown_Call) RunAndReturn(run func()) *HubServiceIdentityInterface_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HubServiceIdentityInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type HubServiceIdentityInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *HubServiceIdentityInterface_Expecter) Start() *HubServiceIdentityInterface_Start_Call {
	return &HubServiceIdentityInterface_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *HubServiceIdentityInterface_Start_Call) Run(run func()) *HubServiceIdentityInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HubServiceIdentityInterface_Start_Call) Return(err error) *HubServiceIdentityInterface_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HubServiceIdentityInterface_Start_Call) RunAndReturn(run func() error) *HubServiceIdentityInterface_Start_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterRemoteService provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) UnregisterRemoteService(ski string, fingerprint string) {
	_mock.Called(ski, fingerprint)
	return
}

// HubServiceIdentityInterface_UnregisterRemoteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterRemoteService'
type HubServiceIdentityInterface_UnregisterRemoteService_Call struct {
	*mock.Call
}

// UnregisterRemoteService is a helper method to define mock.On call
//   - ski string
//   - fingerprint string
func (_e *HubServiceIdentityInterface_Expecter) UnregisterRemoteService(ski interface{}, fingerprint interface{}) *HubServiceIdentityInterface_UnregisterRemoteService_Call {
	return &HubServiceIdentityInterface_UnregisterRemoteService_Call{Call: _e.mock.On("UnregisterRemoteService", ski, fingerprint)}
}

func (_c *HubServiceIdentityInterface_UnregisterRemoteService_Call) Run(run func(ski string, fingerprint string)) *HubServiceIdentityInterface_UnregisterRemoteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_UnregisterRemoteService_Call) Return() *HubServiceIdentityInterface_UnregisterRemoteService_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubServiceIdentityInterface_UnregisterRemoteService_Call) RunAndReturn(run func(ski string, fingerprint string)) *HubServiceIdentityInterface_UnregisterRemoteService_Call {
	_c.Run(run)
	return _c
}

// UnregisterRemoteServiceIdentity provides a mock function for the type HubServiceIdentityInterface
func (_mock *HubServiceIdentityInterface) UnregisterRemoteServiceIdentity(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// HubServiceIdentityInterface_UnregisterRemoteServiceIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterRemoteServiceIdentity'
type HubServiceIdentityInterface_UnregisterRemoteServiceIdentity_Call struct {
	*mock.Call
}

// UnregisterRemoteServiceIdentity is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *HubServiceIdentityInterface_Expecter) UnregisterRemoteServiceIdentity(identity interface{}) *HubServiceIdentityInterface_UnregisterRemoteServiceIdentity_Call {
	return &HubServiceIdentityInterface_UnregisterRemoteServiceIdentity_Call{Call: _e.mock.On("UnregisterRemoteServiceIdentity", identity)}
}

func (_c *HubServiceIdentityInterface_UnregisterRemoteServiceIdentity_Call) Run(run func(identity api.ServiceIdentity)) *HubServiceIdentityInterface_UnregisterRemoteServiceIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HubServiceIdentityInterface_UnregisterRemoteServiceIdentity_Call) Return() *HubServiceIdentityInterface_UnregisterRemoteServiceIdentity_Call {
	_c.Call.Return()
	return _c
}

func (_c *HubServiceIdentityInterface_UnregisterRemoteServiceIdentity_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *HubServiceIdentityInterface_UnregisterRemoteServiceIdentity_Call {
	_c.Run(run)
	return _c
}
