// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logging is an autogenerated mock type for the Logging type
type Logging struct {
	mock.Mock
}

type Logging_Expecter struct {
	mock *mock.Mock
}

func (_m *Logging) EXPECT() *Logging_Expecter {
	return &Logging_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: args
func (_m *Logging) Debug(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Logging_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type Logging_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - args ...interface{}
func (_e *Logging_Expecter) Debug(args ...interface{}) *Logging_Debug_Call {
	return &Logging_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{}, args...)...)}
}

func (_c *Logging_Debug_Call) Run(run func(args ...interface{})) *Logging_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Logging_Debug_Call) Return() *Logging_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logging_Debug_Call) RunAndReturn(run func(...interface{})) *Logging_Debug_Call {
	_c.Call.Return(run)
	return _c
}

// Debugf provides a mock function with given fields: format, args
func (_m *Logging) Debugf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Logging_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type Logging_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *Logging_Expecter) Debugf(format interface{}, args ...interface{}) *Logging_Debugf_Call {
	return &Logging_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{format}, args...)...)}
}

func (_c *Logging_Debugf_Call) Run(run func(format string, args ...interface{})) *Logging_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Logging_Debugf_Call) Return() *Logging_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logging_Debugf_Call) RunAndReturn(run func(string, ...interface{})) *Logging_Debugf_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields: args
func (_m *Logging) Error(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Logging_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type Logging_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - args ...interface{}
func (_e *Logging_Expecter) Error(args ...interface{}) *Logging_Error_Call {
	return &Logging_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{}, args...)...)}
}

func (_c *Logging_Error_Call) Run(run func(args ...interface{})) *Logging_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Logging_Error_Call) Return() *Logging_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logging_Error_Call) RunAndReturn(run func(...interface{})) *Logging_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Errorf provides a mock function with given fields: format, args
func (_m *Logging) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Logging_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type Logging_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *Logging_Expecter) Errorf(format interface{}, args ...interface{}) *Logging_Errorf_Call {
	return &Logging_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *Logging_Errorf_Call) Run(run func(format string, args ...interface{})) *Logging_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Logging_Errorf_Call) Return() *Logging_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logging_Errorf_Call) RunAndReturn(run func(string, ...interface{})) *Logging_Errorf_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: args
func (_m *Logging) Info(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Logging_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type Logging_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - args ...interface{}
func (_e *Logging_Expecter) Info(args ...interface{}) *Logging_Info_Call {
	return &Logging_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{}, args...)...)}
}

func (_c *Logging_Info_Call) Run(run func(args ...interface{})) *Logging_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Logging_Info_Call) Return() *Logging_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logging_Info_Call) RunAndReturn(run func(...interface{})) *Logging_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Infof provides a mock function with given fields: format, args
func (_m *Logging) Infof(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Logging_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type Logging_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *Logging_Expecter) Infof(format interface{}, args ...interface{}) *Logging_Infof_Call {
	return &Logging_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{format}, args...)...)}
}

func (_c *Logging_Infof_Call) Run(run func(format string, args ...interface{})) *Logging_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Logging_Infof_Call) Return() *Logging_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logging_Infof_Call) RunAndReturn(run func(string, ...interface{})) *Logging_Infof_Call {
	_c.Call.Return(run)
	return _c
}

// Trace provides a mock function with given fields: args
func (_m *Logging) Trace(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Logging_Trace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trace'
type Logging_Trace_Call struct {
	*mock.Call
}

// Trace is a helper method to define mock.On call
//   - args ...interface{}
func (_e *Logging_Expecter) Trace(args ...interface{}) *Logging_Trace_Call {
	return &Logging_Trace_Call{Call: _e.mock.On("Trace",
		append([]interface{}{}, args...)...)}
}

func (_c *Logging_Trace_Call) Run(run func(args ...interface{})) *Logging_Trace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Logging_Trace_Call) Return() *Logging_Trace_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logging_Trace_Call) RunAndReturn(run func(...interface{})) *Logging_Trace_Call {
	_c.Call.Return(run)
	return _c
}

// Tracef provides a mock function with given fields: format, args
func (_m *Logging) Tracef(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Logging_Tracef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tracef'
type Logging_Tracef_Call struct {
	*mock.Call
}

// Tracef is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *Logging_Expecter) Tracef(format interface{}, args ...interface{}) *Logging_Tracef_Call {
	return &Logging_Tracef_Call{Call: _e.mock.On("Tracef",
		append([]interface{}{format}, args...)...)}
}

func (_c *Logging_Tracef_Call) Run(run func(format string, args ...interface{})) *Logging_Tracef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Logging_Tracef_Call) Return() *Logging_Tracef_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logging_Tracef_Call) RunAndReturn(run func(string, ...interface{})) *Logging_Tracef_Call {
	_c.Call.Return(run)
	return _c
}

// NewLogging creates a new instance of Logging. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogging(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logging {
	mock := &Logging{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
