// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewMdnsReportInterface creates a new instance of MdnsReportInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMdnsReportInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MdnsReportInterface {
	mock := &MdnsReportInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MdnsReportInterface is an autogenerated mock type for the MdnsReportInterface type
type MdnsReportInterface struct {
	mock.Mock
}

type MdnsReportInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MdnsReportInterface) EXPECT() *MdnsReportInterface_Expecter {
	return &MdnsReportInterface_Expecter{mock: &_m.Mock}
}

// ReportMdnsEntries provides a mock function for the type MdnsReportInterface
func (_mock *MdnsReportInterface) ReportMdnsEntries(entries map[string]*api.MdnsEntry, newEntries bool) {
	_mock.Called(entries, newEntries)
	return
}

// MdnsReportInterface_ReportMdnsEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportMdnsEntries'
type MdnsReportInterface_ReportMdnsEntries_Call struct {
	*mock.Call
}

// ReportMdnsEntries is a helper method to define mock.On call
//   - entries map[string]*api.MdnsEntry
//   - newEntries bool
func (_e *MdnsReportInterface_Expecter) ReportMdnsEntries(entries interface{}, newEntries interface{}) *MdnsReportInterface_ReportMdnsEntries_Call {
	return &MdnsReportInterface_ReportMdnsEntries_Call{Call: _e.mock.On("ReportMdnsEntries", entries, newEntries)}
}

func (_c *MdnsReportInterface_ReportMdnsEntries_Call) Run(run func(entries map[string]*api.MdnsEntry, newEntries bool)) *MdnsReportInterface_ReportMdnsEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]*api.MdnsEntry
		if args[0] != nil {
			arg0 = args[0].(map[string]*api.MdnsEntry)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MdnsReportInterface_ReportMdnsEntries_Call) Return() *MdnsReportInterface_ReportMdnsEntries_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsReportInterface_ReportMdnsEntries_Call) RunAndReturn(run func(entries map[string]*api.MdnsEntry, newEntries bool)) *MdnsReportInterface_ReportMdnsEntries_Call {
	_c.Run(run)
	return _c
}
