// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewMdnsPairingInterface creates a new instance of MdnsPairingInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMdnsPairingInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MdnsPairingInterface {
	mock := &MdnsPairingInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MdnsPairingInterface is an autogenerated mock type for the MdnsPairingInterface type
type MdnsPairingInterface struct {
	mock.Mock
}

type MdnsPairingInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MdnsPairingInterface) EXPECT() *MdnsPairingInterface_Expecter {
	return &MdnsPairingInterface_Expecter{mock: &_m.Mock}
}

// AnnouncePairingService provides a mock function for the type MdnsPairingInterface
func (_mock *MdnsPairingInterface) AnnouncePairingService(txtRecord *api.ShipPairingTXT) (string, error) {
	ret := _mock.Called(txtRecord)

	if len(ret) == 0 {
		panic("no return value specified for AnnouncePairingService")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*api.ShipPairingTXT) (string, error)); ok {
		return returnFunc(txtRecord)
	}
	if returnFunc, ok := ret.Get(0).(func(*api.ShipPairingTXT) string); ok {
		r0 = returnFunc(txtRecord)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*api.ShipPairingTXT) error); ok {
		r1 = returnFunc(txtRecord)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MdnsPairingInterface_AnnouncePairingService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnnouncePairingService'
type MdnsPairingInterface_AnnouncePairingService_Call struct {
	*mock.Call
}

// AnnouncePairingService is a helper method to define mock.On call
//   - txtRecord *api.ShipPairingTXT
func (_e *MdnsPairingInterface_Expecter) AnnouncePairingService(txtRecord interface{}) *MdnsPairingInterface_AnnouncePairingService_Call {
	return &MdnsPairingInterface_AnnouncePairingService_Call{Call: _e.mock.On("AnnouncePairingService", txtRecord)}
}

func (_c *MdnsPairingInterface_AnnouncePairingService_Call) Run(run func(txtRecord *api.ShipPairingTXT)) *MdnsPairingInterface_AnnouncePairingService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.ShipPairingTXT
		if args[0] != nil {
			arg0 = args[0].(*api.ShipPairingTXT)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MdnsPairingInterface_AnnouncePairingService_Call) Return(s string, err error) *MdnsPairingInterface_AnnouncePairingService_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MdnsPairingInterface_AnnouncePairingService_Call) RunAndReturn(run func(txtRecord *api.ShipPairingTXT) (string, error)) *MdnsPairingInterface_AnnouncePairingService_Call {
	_c.Call.Return(run)
	return _c
}

// IsPairingServiceAnnounced provides a mock function for the type MdnsPairingInterface
func (_mock *MdnsPairingInterface) IsPairingServiceAnnounced() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsPairingServiceAnnounced")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MdnsPairingInterface_IsPairingServiceAnnounced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPairingServiceAnnounced'
type MdnsPairingInterface_IsPairingServiceAnnounced_Call struct {
	*mock.Call
}

// IsPairingServiceAnnounced is a helper method to define mock.On call
func (_e *MdnsPairingInterface_Expecter) IsPairingServiceAnnounced() *MdnsPairingInterface_IsPairingServiceAnnounced_Call {
	return &MdnsPairingInterface_IsPairingServiceAnnounced_Call{Call: _e.mock.On("IsPairingServiceAnnounced")}
}

func (_c *MdnsPairingInterface_IsPairingServiceAnnounced_Call) Run(run func()) *MdnsPairingInterface_IsPairingServiceAnnounced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsPairingInterface_IsPairingServiceAnnounced_Call) Return(b bool) *MdnsPairingInterface_IsPairingServiceAnnounced_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MdnsPairingInterface_IsPairingServiceAnnounced_Call) RunAndReturn(run func() bool) *MdnsPairingInterface_IsPairingServiceAnnounced_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPairingEntries provides a mock function for the type MdnsPairingInterface
func (_mock *MdnsPairingInterface) RequestPairingEntries() (map[string]*api.ShipPairingTXT, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestPairingEntries")
	}

	var r0 map[string]*api.ShipPairingTXT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]*api.ShipPairingTXT, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]*api.ShipPairingTXT); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*api.ShipPairingTXT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MdnsPairingInterface_RequestPairingEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPairingEntries'
type MdnsPairingInterface_RequestPairingEntries_Call struct {
	*mock.Call
}

// RequestPairingEntries is a helper method to define mock.On call
func (_e *MdnsPairingInterface_Expecter) RequestPairingEntries() *MdnsPairingInterface_RequestPairingEntries_Call {
	return &MdnsPairingInterface_RequestPairingEntries_Call{Call: _e.mock.On("RequestPairingEntries")}
}

func (_c *MdnsPairingInterface_RequestPairingEntries_Call) Run(run func()) *MdnsPairingInterface_RequestPairingEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsPairingInterface_RequestPairingEntries_Call) Return(stringToShipPairingTXT map[string]*api.ShipPairingTXT, err error) *MdnsPairingInterface_RequestPairingEntries_Call {
	_c.Call.Return(stringToShipPairingTXT, err)
	return _c
}

func (_c *MdnsPairingInterface_RequestPairingEntries_Call) RunAndReturn(run func() (map[string]*api.ShipPairingTXT, error)) *MdnsPairingInterface_RequestPairingEntries_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPairingServices provides a mock function for the type MdnsPairingInterface
func (_mock *MdnsPairingInterface) SearchPairingServices(callback func(*api.ShipPairingTXT) bool) error {
	ret := _mock.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for SearchPairingServices")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(*api.ShipPairingTXT) bool) error); ok {
		r0 = returnFunc(callback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MdnsPairingInterface_SearchPairingServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPairingServices'
type MdnsPairingInterface_SearchPairingServices_Call struct {
	*mock.Call
}

// SearchPairingServices is a helper method to define mock.On call
//   - callback func(*api.ShipPairingTXT) bool
func (_e *MdnsPairingInterface_Expecter) SearchPairingServices(callback interface{}) *MdnsPairingInterface_SearchPairingServices_Call {
	return &MdnsPairingInterface_SearchPairingServices_Call{Call: _e.mock.On("SearchPairingServices", callback)}
}

func (_c *MdnsPairingInterface_SearchPairingServices_Call) Run(run func(callback func(*api.ShipPairingTXT) bool)) *MdnsPairingInterface_SearchPairingServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(*api.ShipPairingTXT) bool
		if args[0] != nil {
			arg0 = args[0].(func(*api.ShipPairingTXT) bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MdnsPairingInterface_SearchPairingServices_Call) Return(err error) *MdnsPairingInterface_SearchPairingServices_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MdnsPairingInterface_SearchPairingServices_Call) RunAndReturn(run func(callback func(*api.ShipPairingTXT) bool) error) *MdnsPairingInterface_SearchPairingServices_Call {
	_c.Call.Return(run)
	return _c
}

// UnannouncePairingService provides a mock function for the type MdnsPairingInterface
func (_mock *MdnsPairingInterface) UnannouncePairingService(instanceID string) error {
	ret := _mock.Called(instanceID)

	if len(ret) == 0 {
		panic("no return value specified for UnannouncePairingService")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(instanceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MdnsPairingInterface_UnannouncePairingService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnannouncePairingService'
type MdnsPairingInterface_UnannouncePairingService_Call struct {
	*mock.Call
}

// UnannouncePairingService is a helper method to define mock.On call
//   - instanceID string
func (_e *MdnsPairingInterface_Expecter) UnannouncePairingService(instanceID interface{}) *MdnsPairingInterface_UnannouncePairingService_Call {
	return &MdnsPairingInterface_UnannouncePairingService_Call{Call: _e.mock.On("UnannouncePairingService", instanceID)}
}

func (_c *MdnsPairingInterface_UnannouncePairingService_Call) Run(run func(instanceID string)) *MdnsPairingInterface_UnannouncePairingService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MdnsPairingInterface_UnannouncePairingService_Call) Return(err error) *MdnsPairingInterface_UnannouncePairingService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MdnsPairingInterface_UnannouncePairingService_Call) RunAndReturn(run func(instanceID string) error) *MdnsPairingInterface_UnannouncePairingService_Call {
	_c.Call.Return(run)
	return _c
}
