// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewMdnsInterface creates a new instance of MdnsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMdnsInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MdnsInterface {
	mock := &MdnsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MdnsInterface is an autogenerated mock type for the MdnsInterface type
type MdnsInterface struct {
	mock.Mock
}

type MdnsInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MdnsInterface) EXPECT() *MdnsInterface_Expecter {
	return &MdnsInterface_Expecter{mock: &_m.Mock}
}

// AnnounceMdnsEntry provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) AnnounceMdnsEntry() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AnnounceMdnsEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MdnsInterface_AnnounceMdnsEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnnounceMdnsEntry'
type MdnsInterface_AnnounceMdnsEntry_Call struct {
	*mock.Call
}

// AnnounceMdnsEntry is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) AnnounceMdnsEntry() *MdnsInterface_AnnounceMdnsEntry_Call {
	return &MdnsInterface_AnnounceMdnsEntry_Call{Call: _e.mock.On("AnnounceMdnsEntry")}
}

func (_c *MdnsInterface_AnnounceMdnsEntry_Call) Run(run func()) *MdnsInterface_AnnounceMdnsEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_AnnounceMdnsEntry_Call) Return(err error) *MdnsInterface_AnnounceMdnsEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MdnsInterface_AnnounceMdnsEntry_Call) RunAndReturn(run func() error) *MdnsInterface_AnnounceMdnsEntry_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceBrand provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) DeviceBrand() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeviceBrand")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MdnsInterface_DeviceBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceBrand'
type MdnsInterface_DeviceBrand_Call struct {
	*mock.Call
}

// DeviceBrand is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) DeviceBrand() *MdnsInterface_DeviceBrand_Call {
	return &MdnsInterface_DeviceBrand_Call{Call: _e.mock.On("DeviceBrand")}
}

func (_c *MdnsInterface_DeviceBrand_Call) Run(run func()) *MdnsInterface_DeviceBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_DeviceBrand_Call) Return(s string) *MdnsInterface_DeviceBrand_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MdnsInterface_DeviceBrand_Call) RunAndReturn(run func() string) *MdnsInterface_DeviceBrand_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceCategories provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) DeviceCategories() []api.DeviceCategoryType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeviceCategories")
	}

	var r0 []api.DeviceCategoryType
	if returnFunc, ok := ret.Get(0).(func() []api.DeviceCategoryType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.DeviceCategoryType)
		}
	}
	return r0
}

// MdnsInterface_DeviceCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceCategories'
type MdnsInterface_DeviceCategories_Call struct {
	*mock.Call
}

// DeviceCategories is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) DeviceCategories() *MdnsInterface_DeviceCategories_Call {
	return &MdnsInterface_DeviceCategories_Call{Call: _e.mock.On("DeviceCategories")}
}

func (_c *MdnsInterface_DeviceCategories_Call) Run(run func()) *MdnsInterface_DeviceCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_DeviceCategories_Call) Return(deviceCategoryTypes []api.DeviceCategoryType) *MdnsInterface_DeviceCategories_Call {
	_c.Call.Return(deviceCategoryTypes)
	return _c
}

func (_c *MdnsInterface_DeviceCategories_Call) RunAndReturn(run func() []api.DeviceCategoryType) *MdnsInterface_DeviceCategories_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceModel provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) DeviceModel() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeviceModel")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MdnsInterface_DeviceModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceModel'
type MdnsInterface_DeviceModel_Call struct {
	*mock.Call
}

// DeviceModel is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) DeviceModel() *MdnsInterface_DeviceModel_Call {
	return &MdnsInterface_DeviceModel_Call{Call: _e.mock.On("DeviceModel")}
}

func (_c *MdnsInterface_DeviceModel_Call) Run(run func()) *MdnsInterface_DeviceModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_DeviceModel_Call) Return(s string) *MdnsInterface_DeviceModel_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MdnsInterface_DeviceModel_Call) RunAndReturn(run func() string) *MdnsInterface_DeviceModel_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceSerial provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) DeviceSerial() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeviceSerial")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MdnsInterface_DeviceSerial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceSerial'
type MdnsInterface_DeviceSerial_Call struct {
	*mock.Call
}

// DeviceSerial is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) DeviceSerial() *MdnsInterface_DeviceSerial_Call {
	return &MdnsInterface_DeviceSerial_Call{Call: _e.mock.On("DeviceSerial")}
}

func (_c *MdnsInterface_DeviceSerial_Call) Run(run func()) *MdnsInterface_DeviceSerial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_DeviceSerial_Call) Return(s string) *MdnsInterface_DeviceSerial_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MdnsInterface_DeviceSerial_Call) RunAndReturn(run func() string) *MdnsInterface_DeviceSerial_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceType provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) DeviceType() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeviceType")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MdnsInterface_DeviceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceType'
type MdnsInterface_DeviceType_Call struct {
	*mock.Call
}

// DeviceType is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) DeviceType() *MdnsInterface_DeviceType_Call {
	return &MdnsInterface_DeviceType_Call{Call: _e.mock.On("DeviceType")}
}

func (_c *MdnsInterface_DeviceType_Call) Run(run func()) *MdnsInterface_DeviceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_DeviceType_Call) Return(s string) *MdnsInterface_DeviceType_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MdnsInterface_DeviceType_Call) RunAndReturn(run func() string) *MdnsInterface_DeviceType_Call {
	_c.Call.Return(run)
	return _c
}

// RequestMdnsEntries provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) RequestMdnsEntries() {
	_mock.Called()
	return
}

// MdnsInterface_RequestMdnsEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestMdnsEntries'
type MdnsInterface_RequestMdnsEntries_Call struct {
	*mock.Call
}

// RequestMdnsEntries is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) RequestMdnsEntries() *MdnsInterface_RequestMdnsEntries_Call {
	return &MdnsInterface_RequestMdnsEntries_Call{Call: _e.mock.On("RequestMdnsEntries")}
}

func (_c *MdnsInterface_RequestMdnsEntries_Call) Run(run func()) *MdnsInterface_RequestMdnsEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_RequestMdnsEntries_Call) Return() *MdnsInterface_RequestMdnsEntries_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsInterface_RequestMdnsEntries_Call) RunAndReturn(run func()) *MdnsInterface_RequestMdnsEntries_Call {
	_c.Run(run)
	return _c
}

// SetAutoAccept provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) SetAutoAccept(b bool) {
	_mock.Called(b)
	return
}

// MdnsInterface_SetAutoAccept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAutoAccept'
type MdnsInterface_SetAutoAccept_Call struct {
	*mock.Call
}

// SetAutoAccept is a helper method to define mock.On call
//   - b bool
func (_e *MdnsInterface_Expecter) SetAutoAccept(b interface{}) *MdnsInterface_SetAutoAccept_Call {
	return &MdnsInterface_SetAutoAccept_Call{Call: _e.mock.On("SetAutoAccept", b)}
}

func (_c *MdnsInterface_SetAutoAccept_Call) Run(run func(b bool)) *MdnsInterface_SetAutoAccept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MdnsInterface_SetAutoAccept_Call) Return() *MdnsInterface_SetAutoAccept_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsInterface_SetAutoAccept_Call) RunAndReturn(run func(b bool)) *MdnsInterface_SetAutoAccept_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) Shutdown() {
	_mock.Called()
	return
}

// MdnsInterface_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MdnsInterface_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) Shutdown() *MdnsInterface_Shutdown_Call {
	return &MdnsInterface_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MdnsInterface_Shutdown_Call) Run(run func()) *MdnsInterface_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_Shutdown_Call) Return() *MdnsInterface_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsInterface_Shutdown_Call) RunAndReturn(run func()) *MdnsInterface_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) Start(pairingMode api.PairingMode, cb api.MdnsReportInterface) error {
	ret := _mock.Called(pairingMode, cb)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(api.PairingMode, api.MdnsReportInterface) error); ok {
		r0 = returnFunc(pairingMode, cb)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MdnsInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MdnsInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - pairingMode api.PairingMode
//   - cb api.MdnsReportInterface
func (_e *MdnsInterface_Expecter) Start(pairingMode interface{}, cb interface{}) *MdnsInterface_Start_Call {
	return &MdnsInterface_Start_Call{Call: _e.mock.On("Start", pairingMode, cb)}
}

func (_c *MdnsInterface_Start_Call) Run(run func(pairingMode api.PairingMode, cb api.MdnsReportInterface)) *MdnsInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.PairingMode
		if args[0] != nil {
			arg0 = args[0].(api.PairingMode)
		}
		var arg1 api.MdnsReportInterface
		if args[1] != nil {
			arg1 = args[1].(api.MdnsReportInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MdnsInterface_Start_Call) Return(err error) *MdnsInterface_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MdnsInterface_Start_Call) RunAndReturn(run func(pairingMode api.PairingMode, cb api.MdnsReportInterface) error) *MdnsInterface_Start_Call {
	_c.Call.Return(run)
	return _c
}

// UnannounceMdnsEntry provides a mock function for the type MdnsInterface
func (_mock *MdnsInterface) UnannounceMdnsEntry() {
	_mock.Called()
	return
}

// MdnsInterface_UnannounceMdnsEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnannounceMdnsEntry'
type MdnsInterface_UnannounceMdnsEntry_Call struct {
	*mock.Call
}

// UnannounceMdnsEntry is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) UnannounceMdnsEntry() *MdnsInterface_UnannounceMdnsEntry_Call {
	return &MdnsInterface_UnannounceMdnsEntry_Call{Call: _e.mock.On("UnannounceMdnsEntry")}
}

func (_c *MdnsInterface_UnannounceMdnsEntry_Call) Run(run func()) *MdnsInterface_UnannounceMdnsEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_UnannounceMdnsEntry_Call) Return() *MdnsInterface_UnannounceMdnsEntry_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsInterface_UnannounceMdnsEntry_Call) RunAndReturn(run func()) *MdnsInterface_UnannounceMdnsEntry_Call {
	_c.Run(run)
	return _c
}
