// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewMdnsProviderInterface creates a new instance of MdnsProviderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMdnsProviderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MdnsProviderInterface {
	mock := &MdnsProviderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MdnsProviderInterface is an autogenerated mock type for the MdnsProviderInterface type
type MdnsProviderInterface struct {
	mock.Mock
}

type MdnsProviderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MdnsProviderInterface) EXPECT() *MdnsProviderInterface_Expecter {
	return &MdnsProviderInterface_Expecter{mock: &_m.Mock}
}

// Announce provides a mock function for the type MdnsProviderInterface
func (_mock *MdnsProviderInterface) Announce(serviceName string, port int, txt []string) error {
	ret := _mock.Called(serviceName, port, txt)

	if len(ret) == 0 {
		panic("no return value specified for Announce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int, []string) error); ok {
		r0 = returnFunc(serviceName, port, txt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MdnsProviderInterface_Announce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Announce'
type MdnsProviderInterface_Announce_Call struct {
	*mock.Call
}

// Announce is a helper method to define mock.On call
//   - serviceName string
//   - port int
//   - txt []string
func (_e *MdnsProviderInterface_Expecter) Announce(serviceName interface{}, port interface{}, txt interface{}) *MdnsProviderInterface_Announce_Call {
	return &MdnsProviderInterface_Announce_Call{Call: _e.mock.On("Announce", serviceName, port, txt)}
}

func (_c *MdnsProviderInterface_Announce_Call) Run(run func(serviceName string, port int, txt []string)) *MdnsProviderInterface_Announce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MdnsProviderInterface_Announce_Call) Return(err error) *MdnsProviderInterface_Announce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MdnsProviderInterface_Announce_Call) RunAndReturn(run func(serviceName string, port int, txt []string) error) *MdnsProviderInterface_Announce_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MdnsProviderInterface
func (_mock *MdnsProviderInterface) Shutdown() {
	_mock.Called()
	return
}

// MdnsProviderInterface_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MdnsProviderInterface_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MdnsProviderInterface_Expecter) Shutdown() *MdnsProviderInterface_Shutdown_Call {
	return &MdnsProviderInterface_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MdnsProviderInterface_Shutdown_Call) Run(run func()) *MdnsProviderInterface_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsProviderInterface_Shutdown_Call) Return() *MdnsProviderInterface_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsProviderInterface_Shutdown_Call) RunAndReturn(run func()) *MdnsProviderInterface_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MdnsProviderInterface
func (_mock *MdnsProviderInterface) Start(autoReconnect bool, cb api.MdnsResolveCB) bool {
	ret := _mock.Called(autoReconnect, cb)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(bool, api.MdnsResolveCB) bool); ok {
		r0 = returnFunc(autoReconnect, cb)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MdnsProviderInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MdnsProviderInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - autoReconnect bool
//   - cb api.MdnsResolveCB
func (_e *MdnsProviderInterface_Expecter) Start(autoReconnect interface{}, cb interface{}) *MdnsProviderInterface_Start_Call {
	return &MdnsProviderInterface_Start_Call{Call: _e.mock.On("Start", autoReconnect, cb)}
}

func (_c *MdnsProviderInterface_Start_Call) Run(run func(autoReconnect bool, cb api.MdnsResolveCB)) *MdnsProviderInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		var arg1 api.MdnsResolveCB
		if args[1] != nil {
			arg1 = args[1].(api.MdnsResolveCB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MdnsProviderInterface_Start_Call) Return(b bool) *MdnsProviderInterface_Start_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MdnsProviderInterface_Start_Call) RunAndReturn(run func(autoReconnect bool, cb api.MdnsResolveCB) bool) *MdnsProviderInterface_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Unannounce provides a mock function for the type MdnsProviderInterface
func (_mock *MdnsProviderInterface) Unannounce() {
	_mock.Called()
	return
}

// MdnsProviderInterface_Unannounce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unannounce'
type MdnsProviderInterface_Unannounce_Call struct {
	*mock.Call
}

// Unannounce is a helper method to define mock.On call
func (_e *MdnsProviderInterface_Expecter) Unannounce() *MdnsProviderInterface_Unannounce_Call {
	return &MdnsProviderInterface_Unannounce_Call{Call: _e.mock.On("Unannounce")}
}

func (_c *MdnsProviderInterface_Unannounce_Call) Run(run func()) *MdnsProviderInterface_Unannounce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsProviderInterface_Unannounce_Call) Return() *MdnsProviderInterface_Unannounce_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsProviderInterface_Unannounce_Call) RunAndReturn(run func()) *MdnsProviderInterface_Unannounce_Call {
	_c.Run(run)
	return _c
}
