// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// MdnsInterface is an autogenerated mock type for the MdnsInterface type
type MdnsInterface struct {
	mock.Mock
}

type MdnsInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MdnsInterface) EXPECT() *MdnsInterface_Expecter {
	return &MdnsInterface_Expecter{mock: &_m.Mock}
}

// AnnounceMdnsEntry provides a mock function with given fields:
func (_m *MdnsInterface) AnnounceMdnsEntry() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AnnounceMdnsEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MdnsInterface_AnnounceMdnsEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnnounceMdnsEntry'
type MdnsInterface_AnnounceMdnsEntry_Call struct {
	*mock.Call
}

// AnnounceMdnsEntry is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) AnnounceMdnsEntry() *MdnsInterface_AnnounceMdnsEntry_Call {
	return &MdnsInterface_AnnounceMdnsEntry_Call{Call: _e.mock.On("AnnounceMdnsEntry")}
}

func (_c *MdnsInterface_AnnounceMdnsEntry_Call) Run(run func()) *MdnsInterface_AnnounceMdnsEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_AnnounceMdnsEntry_Call) Return(_a0 error) *MdnsInterface_AnnounceMdnsEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MdnsInterface_AnnounceMdnsEntry_Call) RunAndReturn(run func() error) *MdnsInterface_AnnounceMdnsEntry_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterMdnsSearch provides a mock function with given fields: cb
func (_m *MdnsInterface) RegisterMdnsSearch(cb api.MdnsSearchInterface) {
	_m.Called(cb)
}

// MdnsInterface_RegisterMdnsSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterMdnsSearch'
type MdnsInterface_RegisterMdnsSearch_Call struct {
	*mock.Call
}

// RegisterMdnsSearch is a helper method to define mock.On call
//   - cb api.MdnsSearchInterface
func (_e *MdnsInterface_Expecter) RegisterMdnsSearch(cb interface{}) *MdnsInterface_RegisterMdnsSearch_Call {
	return &MdnsInterface_RegisterMdnsSearch_Call{Call: _e.mock.On("RegisterMdnsSearch", cb)}
}

func (_c *MdnsInterface_RegisterMdnsSearch_Call) Run(run func(cb api.MdnsSearchInterface)) *MdnsInterface_RegisterMdnsSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.MdnsSearchInterface))
	})
	return _c
}

func (_c *MdnsInterface_RegisterMdnsSearch_Call) Return() *MdnsInterface_RegisterMdnsSearch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsInterface_RegisterMdnsSearch_Call) RunAndReturn(run func(api.MdnsSearchInterface)) *MdnsInterface_RegisterMdnsSearch_Call {
	_c.Call.Return(run)
	return _c
}

// SetAutoAccept provides a mock function with given fields: _a0
func (_m *MdnsInterface) SetAutoAccept(_a0 bool) {
	_m.Called(_a0)
}

// MdnsInterface_SetAutoAccept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAutoAccept'
type MdnsInterface_SetAutoAccept_Call struct {
	*mock.Call
}

// SetAutoAccept is a helper method to define mock.On call
//   - _a0 bool
func (_e *MdnsInterface_Expecter) SetAutoAccept(_a0 interface{}) *MdnsInterface_SetAutoAccept_Call {
	return &MdnsInterface_SetAutoAccept_Call{Call: _e.mock.On("SetAutoAccept", _a0)}
}

func (_c *MdnsInterface_SetAutoAccept_Call) Run(run func(_a0 bool)) *MdnsInterface_SetAutoAccept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MdnsInterface_SetAutoAccept_Call) Return() *MdnsInterface_SetAutoAccept_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsInterface_SetAutoAccept_Call) RunAndReturn(run func(bool)) *MdnsInterface_SetAutoAccept_Call {
	_c.Call.Return(run)
	return _c
}

// SetupMdnsService provides a mock function with given fields:
func (_m *MdnsInterface) SetupMdnsService() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SetupMdnsService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MdnsInterface_SetupMdnsService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupMdnsService'
type MdnsInterface_SetupMdnsService_Call struct {
	*mock.Call
}

// SetupMdnsService is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) SetupMdnsService() *MdnsInterface_SetupMdnsService_Call {
	return &MdnsInterface_SetupMdnsService_Call{Call: _e.mock.On("SetupMdnsService")}
}

func (_c *MdnsInterface_SetupMdnsService_Call) Run(run func()) *MdnsInterface_SetupMdnsService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_SetupMdnsService_Call) Return(_a0 error) *MdnsInterface_SetupMdnsService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MdnsInterface_SetupMdnsService_Call) RunAndReturn(run func() error) *MdnsInterface_SetupMdnsService_Call {
	_c.Call.Return(run)
	return _c
}

// ShutdownMdnsService provides a mock function with given fields:
func (_m *MdnsInterface) ShutdownMdnsService() {
	_m.Called()
}

// MdnsInterface_ShutdownMdnsService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShutdownMdnsService'
type MdnsInterface_ShutdownMdnsService_Call struct {
	*mock.Call
}

// ShutdownMdnsService is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) ShutdownMdnsService() *MdnsInterface_ShutdownMdnsService_Call {
	return &MdnsInterface_ShutdownMdnsService_Call{Call: _e.mock.On("ShutdownMdnsService")}
}

func (_c *MdnsInterface_ShutdownMdnsService_Call) Run(run func()) *MdnsInterface_ShutdownMdnsService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_ShutdownMdnsService_Call) Return() *MdnsInterface_ShutdownMdnsService_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsInterface_ShutdownMdnsService_Call) RunAndReturn(run func()) *MdnsInterface_ShutdownMdnsService_Call {
	_c.Call.Return(run)
	return _c
}

// UnannounceMdnsEntry provides a mock function with given fields:
func (_m *MdnsInterface) UnannounceMdnsEntry() {
	_m.Called()
}

// MdnsInterface_UnannounceMdnsEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnannounceMdnsEntry'
type MdnsInterface_UnannounceMdnsEntry_Call struct {
	*mock.Call
}

// UnannounceMdnsEntry is a helper method to define mock.On call
func (_e *MdnsInterface_Expecter) UnannounceMdnsEntry() *MdnsInterface_UnannounceMdnsEntry_Call {
	return &MdnsInterface_UnannounceMdnsEntry_Call{Call: _e.mock.On("UnannounceMdnsEntry")}
}

func (_c *MdnsInterface_UnannounceMdnsEntry_Call) Run(run func()) *MdnsInterface_UnannounceMdnsEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MdnsInterface_UnannounceMdnsEntry_Call) Return() *MdnsInterface_UnannounceMdnsEntry_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsInterface_UnannounceMdnsEntry_Call) RunAndReturn(run func()) *MdnsInterface_UnannounceMdnsEntry_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterMdnsSearch provides a mock function with given fields: cb
func (_m *MdnsInterface) UnregisterMdnsSearch(cb api.MdnsSearchInterface) {
	_m.Called(cb)
}

// MdnsInterface_UnregisterMdnsSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterMdnsSearch'
type MdnsInterface_UnregisterMdnsSearch_Call struct {
	*mock.Call
}

// UnregisterMdnsSearch is a helper method to define mock.On call
//   - cb api.MdnsSearchInterface
func (_e *MdnsInterface_Expecter) UnregisterMdnsSearch(cb interface{}) *MdnsInterface_UnregisterMdnsSearch_Call {
	return &MdnsInterface_UnregisterMdnsSearch_Call{Call: _e.mock.On("UnregisterMdnsSearch", cb)}
}

func (_c *MdnsInterface_UnregisterMdnsSearch_Call) Run(run func(cb api.MdnsSearchInterface)) *MdnsInterface_UnregisterMdnsSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.MdnsSearchInterface))
	})
	return _c
}

func (_c *MdnsInterface_UnregisterMdnsSearch_Call) Return() *MdnsInterface_UnregisterMdnsSearch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MdnsInterface_UnregisterMdnsSearch_Call) RunAndReturn(run func(api.MdnsSearchInterface)) *MdnsInterface_UnregisterMdnsSearch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMdnsInterface creates a new instance of MdnsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMdnsInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MdnsInterface {
	mock := &MdnsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
