// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/enbility/ship-go/api (interfaces: MdnsInterface,HubReaderInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mockgen_api.go -package=mocks github.com/enbility/ship-go/api MdnsInterface,HubReaderInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	api "github.com/enbility/ship-go/api"
	gomock "go.uber.org/mock/gomock"
)

// MockMdnsInterface is a mock of MdnsInterface interface.
type MockMdnsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMdnsInterfaceMockRecorder
}

// MockMdnsInterfaceMockRecorder is the mock recorder for MockMdnsInterface.
type MockMdnsInterfaceMockRecorder struct {
	mock *MockMdnsInterface
}

// NewMockMdnsInterface creates a new mock instance.
func NewMockMdnsInterface(ctrl *gomock.Controller) *MockMdnsInterface {
	mock := &MockMdnsInterface{ctrl: ctrl}
	mock.recorder = &MockMdnsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMdnsInterface) EXPECT() *MockMdnsInterfaceMockRecorder {
	return m.recorder
}

// AnnounceMdnsEntry mocks base method.
func (m *MockMdnsInterface) AnnounceMdnsEntry() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnnounceMdnsEntry")
	ret0, _ := ret[0].(error)
	return ret0
}

// AnnounceMdnsEntry indicates an expected call of AnnounceMdnsEntry.
func (mr *MockMdnsInterfaceMockRecorder) AnnounceMdnsEntry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnnounceMdnsEntry", reflect.TypeOf((*MockMdnsInterface)(nil).AnnounceMdnsEntry))
}

// DeviceBrand mocks base method.
func (m *MockMdnsInterface) DeviceBrand() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceBrand")
	ret0, _ := ret[0].(string)
	return ret0
}

// DeviceBrand indicates an expected call of DeviceBrand.
func (mr *MockMdnsInterfaceMockRecorder) DeviceBrand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceBrand", reflect.TypeOf((*MockMdnsInterface)(nil).DeviceBrand))
}

// DeviceCategories mocks base method.
func (m *MockMdnsInterface) DeviceCategories() []api.DeviceCategoryType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceCategories")
	ret0, _ := ret[0].([]api.DeviceCategoryType)
	return ret0
}

// DeviceCategories indicates an expected call of DeviceCategories.
func (mr *MockMdnsInterfaceMockRecorder) DeviceCategories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceCategories", reflect.TypeOf((*MockMdnsInterface)(nil).DeviceCategories))
}

// DeviceModel mocks base method.
func (m *MockMdnsInterface) DeviceModel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceModel")
	ret0, _ := ret[0].(string)
	return ret0
}

// DeviceModel indicates an expected call of DeviceModel.
func (mr *MockMdnsInterfaceMockRecorder) DeviceModel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceModel", reflect.TypeOf((*MockMdnsInterface)(nil).DeviceModel))
}

// DeviceSerial mocks base method.
func (m *MockMdnsInterface) DeviceSerial() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceSerial")
	ret0, _ := ret[0].(string)
	return ret0
}

// DeviceSerial indicates an expected call of DeviceSerial.
func (mr *MockMdnsInterfaceMockRecorder) DeviceSerial() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceSerial", reflect.TypeOf((*MockMdnsInterface)(nil).DeviceSerial))
}

// DeviceType mocks base method.
func (m *MockMdnsInterface) DeviceType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceType")
	ret0, _ := ret[0].(string)
	return ret0
}

// DeviceType indicates an expected call of DeviceType.
func (mr *MockMdnsInterfaceMockRecorder) DeviceType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceType", reflect.TypeOf((*MockMdnsInterface)(nil).DeviceType))
}

// RequestMdnsEntries mocks base method.
func (m *MockMdnsInterface) RequestMdnsEntries() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestMdnsEntries")
}

// RequestMdnsEntries indicates an expected call of RequestMdnsEntries.
func (mr *MockMdnsInterfaceMockRecorder) RequestMdnsEntries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestMdnsEntries", reflect.TypeOf((*MockMdnsInterface)(nil).RequestMdnsEntries))
}

// SetAutoAccept mocks base method.
func (m *MockMdnsInterface) SetAutoAccept(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAutoAccept", arg0)
}

// SetAutoAccept indicates an expected call of SetAutoAccept.
func (mr *MockMdnsInterfaceMockRecorder) SetAutoAccept(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAutoAccept", reflect.TypeOf((*MockMdnsInterface)(nil).SetAutoAccept), arg0)
}

// SetPort mocks base method.
func (m *MockMdnsInterface) SetPort(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPort", arg0)
}

// SetPort indicates an expected call of SetPort.
func (mr *MockMdnsInterfaceMockRecorder) SetPort(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPort", reflect.TypeOf((*MockMdnsInterface)(nil).SetPort), arg0)
}

// Shutdown mocks base method.
func (m *MockMdnsInterface) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockMdnsInterfaceMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockMdnsInterface)(nil).Shutdown))
}

// Start mocks base method.
func (m *MockMdnsInterface) Start(arg0 api.PairingMode, arg1 api.MdnsReportInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockMdnsInterfaceMockRecorder) Start(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockMdnsInterface)(nil).Start), arg0, arg1)
}

// UnannounceMdnsEntry mocks base method.
func (m *MockMdnsInterface) UnannounceMdnsEntry() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnannounceMdnsEntry")
}

// UnannounceMdnsEntry indicates an expected call of UnannounceMdnsEntry.
func (mr *MockMdnsInterfaceMockRecorder) UnannounceMdnsEntry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnannounceMdnsEntry", reflect.TypeOf((*MockMdnsInterface)(nil).UnannounceMdnsEntry))
}

// MockHubReaderInterface is a mock of HubReaderInterface interface.
type MockHubReaderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHubReaderInterfaceMockRecorder
}

// MockHubReaderInterfaceMockRecorder is the mock recorder for MockHubReaderInterface.
type MockHubReaderInterfaceMockRecorder struct {
	mock *MockHubReaderInterface
}

// NewMockHubReaderInterface creates a new mock instance.
func NewMockHubReaderInterface(ctrl *gomock.Controller) *MockHubReaderInterface {
	mock := &MockHubReaderInterface{ctrl: ctrl}
	mock.recorder = &MockHubReaderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHubReaderInterface) EXPECT() *MockHubReaderInterfaceMockRecorder {
	return m.recorder
}

// AllowWaitingForTrust mocks base method.
func (m *MockHubReaderInterface) AllowWaitingForTrust(arg0 api.ServiceIdentity) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowWaitingForTrust", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllowWaitingForTrust indicates an expected call of AllowWaitingForTrust.
func (mr *MockHubReaderInterfaceMockRecorder) AllowWaitingForTrust(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowWaitingForTrust", reflect.TypeOf((*MockHubReaderInterface)(nil).AllowWaitingForTrust), arg0)
}

// RemoteServiceConnected mocks base method.
func (m *MockHubReaderInterface) RemoteServiceConnected(arg0 api.ServiceIdentity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoteServiceConnected", arg0)
}

// RemoteServiceConnected indicates an expected call of RemoteServiceConnected.
func (mr *MockHubReaderInterfaceMockRecorder) RemoteServiceConnected(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteServiceConnected", reflect.TypeOf((*MockHubReaderInterface)(nil).RemoteServiceConnected), arg0)
}

// RemoteServiceDisconnected mocks base method.
func (m *MockHubReaderInterface) RemoteServiceDisconnected(arg0 api.ServiceIdentity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoteServiceDisconnected", arg0)
}

// RemoteServiceDisconnected indicates an expected call of RemoteServiceDisconnected.
func (mr *MockHubReaderInterfaceMockRecorder) RemoteServiceDisconnected(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteServiceDisconnected", reflect.TypeOf((*MockHubReaderInterface)(nil).RemoteServiceDisconnected), arg0)
}

// ServicePairingDetailUpdate mocks base method.
func (m *MockHubReaderInterface) ServicePairingDetailUpdate(arg0 api.ServiceIdentity, arg1 *api.ConnectionStateDetail) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServicePairingDetailUpdate", arg0, arg1)
}

// ServicePairingDetailUpdate indicates an expected call of ServicePairingDetailUpdate.
func (mr *MockHubReaderInterfaceMockRecorder) ServicePairingDetailUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServicePairingDetailUpdate", reflect.TypeOf((*MockHubReaderInterface)(nil).ServicePairingDetailUpdate), arg0, arg1)
}

// ServiceUpdated mocks base method.
func (m *MockHubReaderInterface) ServiceUpdated(arg0 api.ServiceIdentity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServiceUpdated", arg0)
}

// ServiceUpdated indicates an expected call of ServiceUpdated.
func (mr *MockHubReaderInterfaceMockRecorder) ServiceUpdated(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceUpdated", reflect.TypeOf((*MockHubReaderInterface)(nil).ServiceUpdated), arg0)
}

// SetupRemoteService mocks base method.
func (m *MockHubReaderInterface) SetupRemoteService(arg0 api.ServiceIdentity, arg1 api.ShipConnectionDataWriterInterface) api.ShipConnectionDataReaderInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupRemoteService", arg0, arg1)
	ret0, _ := ret[0].(api.ShipConnectionDataReaderInterface)
	return ret0
}

// SetupRemoteService indicates an expected call of SetupRemoteService.
func (mr *MockHubReaderInterfaceMockRecorder) SetupRemoteService(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupRemoteService", reflect.TypeOf((*MockHubReaderInterface)(nil).SetupRemoteService), arg0, arg1)
}

// VisibleRemoteMdnsServicesUpdated mocks base method.
func (m *MockHubReaderInterface) VisibleRemoteMdnsServicesUpdated(arg0 []api.RemoteMdnsService) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VisibleRemoteMdnsServicesUpdated", arg0)
}

// VisibleRemoteMdnsServicesUpdated indicates an expected call of VisibleRemoteMdnsServicesUpdated.
func (mr *MockHubReaderInterfaceMockRecorder) VisibleRemoteMdnsServicesUpdated(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisibleRemoteMdnsServicesUpdated", reflect.TypeOf((*MockHubReaderInterface)(nil).VisibleRemoteMdnsServicesUpdated), arg0)
}
