// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPairingHistoryProviderInterface creates a new instance of PairingHistoryProviderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPairingHistoryProviderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PairingHistoryProviderInterface {
	mock := &PairingHistoryProviderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PairingHistoryProviderInterface is an autogenerated mock type for the PairingHistoryProviderInterface type
type PairingHistoryProviderInterface struct {
	mock.Mock
}

type PairingHistoryProviderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *PairingHistoryProviderInterface) EXPECT() *PairingHistoryProviderInterface_Expecter {
	return &PairingHistoryProviderInterface_Expecter{mock: &_m.Mock}
}

// HasSeenDigest provides a mock function for the type PairingHistoryProviderInterface
func (_mock *PairingHistoryProviderInterface) HasSeenDigest(alg string, digest string) bool {
	ret := _mock.Called(alg, digest)

	if len(ret) == 0 {
		panic("no return value specified for HasSeenDigest")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(alg, digest)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// PairingHistoryProviderInterface_HasSeenDigest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasSeenDigest'
type PairingHistoryProviderInterface_HasSeenDigest_Call struct {
	*mock.Call
}

// HasSeenDigest is a helper method to define mock.On call
//   - alg string
//   - digest string
func (_e *PairingHistoryProviderInterface_Expecter) HasSeenDigest(alg interface{}, digest interface{}) *PairingHistoryProviderInterface_HasSeenDigest_Call {
	return &PairingHistoryProviderInterface_HasSeenDigest_Call{Call: _e.mock.On("HasSeenDigest", alg, digest)}
}

func (_c *PairingHistoryProviderInterface_HasSeenDigest_Call) Run(run func(alg string, digest string)) *PairingHistoryProviderInterface_HasSeenDigest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PairingHistoryProviderInterface_HasSeenDigest_Call) Return(b bool) *PairingHistoryProviderInterface_HasSeenDigest_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *PairingHistoryProviderInterface_HasSeenDigest_Call) RunAndReturn(run func(alg string, digest string) bool) *PairingHistoryProviderInterface_HasSeenDigest_Call {
	_c.Call.Return(run)
	return _c
}

// RecordPairing provides a mock function for the type PairingHistoryProviderInterface
func (_mock *PairingHistoryProviderInterface) RecordPairing(alg string, digest string) {
	_mock.Called(alg, digest)
	return
}

// PairingHistoryProviderInterface_RecordPairing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordPairing'
type PairingHistoryProviderInterface_RecordPairing_Call struct {
	*mock.Call
}

// RecordPairing is a helper method to define mock.On call
//   - alg string
//   - digest string
func (_e *PairingHistoryProviderInterface_Expecter) RecordPairing(alg interface{}, digest interface{}) *PairingHistoryProviderInterface_RecordPairing_Call {
	return &PairingHistoryProviderInterface_RecordPairing_Call{Call: _e.mock.On("RecordPairing", alg, digest)}
}

func (_c *PairingHistoryProviderInterface_RecordPairing_Call) Run(run func(alg string, digest string)) *PairingHistoryProviderInterface_RecordPairing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PairingHistoryProviderInterface_RecordPairing_Call) Return() *PairingHistoryProviderInterface_RecordPairing_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingHistoryProviderInterface_RecordPairing_Call) RunAndReturn(run func(alg string, digest string)) *PairingHistoryProviderInterface_RecordPairing_Call {
	_c.Run(run)
	return _c
}
