// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewPairingAnnouncerInterface creates a new instance of PairingAnnouncerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPairingAnnouncerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PairingAnnouncerInterface {
	mock := &PairingAnnouncerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PairingAnnouncerInterface is an autogenerated mock type for the PairingAnnouncerInterface type
type PairingAnnouncerInterface struct {
	mock.Mock
}

type PairingAnnouncerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *PairingAnnouncerInterface) EXPECT() *PairingAnnouncerInterface_Expecter {
	return &PairingAnnouncerInterface_Expecter{mock: &_m.Mock}
}

// Announce provides a mock function for the type PairingAnnouncerInterface
func (_mock *PairingAnnouncerInterface) Announce(target *api.PairingTarget) error {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for Announce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*api.PairingTarget) error); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PairingAnnouncerInterface_Announce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Announce'
type PairingAnnouncerInterface_Announce_Call struct {
	*mock.Call
}

// Announce is a helper method to define mock.On call
//   - target *api.PairingTarget
func (_e *PairingAnnouncerInterface_Expecter) Announce(target interface{}) *PairingAnnouncerInterface_Announce_Call {
	return &PairingAnnouncerInterface_Announce_Call{Call: _e.mock.On("Announce", target)}
}

func (_c *PairingAnnouncerInterface_Announce_Call) Run(run func(target *api.PairingTarget)) *PairingAnnouncerInterface_Announce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.PairingTarget
		if args[0] != nil {
			arg0 = args[0].(*api.PairingTarget)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PairingAnnouncerInterface_Announce_Call) Return(err error) *PairingAnnouncerInterface_Announce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PairingAnnouncerInterface_Announce_Call) RunAndReturn(run func(target *api.PairingTarget) error) *PairingAnnouncerInterface_Announce_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnnouncementStatus provides a mock function for the type PairingAnnouncerInterface
func (_mock *PairingAnnouncerInterface) GetAnnouncementStatus() *api.AnnouncementStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAnnouncementStatus")
	}

	var r0 *api.AnnouncementStatus
	if returnFunc, ok := ret.Get(0).(func() *api.AnnouncementStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.AnnouncementStatus)
		}
	}
	return r0
}

// PairingAnnouncerInterface_GetAnnouncementStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnnouncementStatus'
type PairingAnnouncerInterface_GetAnnouncementStatus_Call struct {
	*mock.Call
}

// GetAnnouncementStatus is a helper method to define mock.On call
func (_e *PairingAnnouncerInterface_Expecter) GetAnnouncementStatus() *PairingAnnouncerInterface_GetAnnouncementStatus_Call {
	return &PairingAnnouncerInterface_GetAnnouncementStatus_Call{Call: _e.mock.On("GetAnnouncementStatus")}
}

func (_c *PairingAnnouncerInterface_GetAnnouncementStatus_Call) Run(run func()) *PairingAnnouncerInterface_GetAnnouncementStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PairingAnnouncerInterface_GetAnnouncementStatus_Call) Return(announcementStatus *api.AnnouncementStatus) *PairingAnnouncerInterface_GetAnnouncementStatus_Call {
	_c.Call.Return(announcementStatus)
	return _c
}

func (_c *PairingAnnouncerInterface_GetAnnouncementStatus_Call) RunAndReturn(run func() *api.AnnouncementStatus) *PairingAnnouncerInterface_GetAnnouncementStatus_Call {
	_c.Call.Return(run)
	return _c
}

// StopAnnouncement provides a mock function for the type PairingAnnouncerInterface
func (_mock *PairingAnnouncerInterface) StopAnnouncement() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopAnnouncement")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PairingAnnouncerInterface_StopAnnouncement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAnnouncement'
type PairingAnnouncerInterface_StopAnnouncement_Call struct {
	*mock.Call
}

// StopAnnouncement is a helper method to define mock.On call
func (_e *PairingAnnouncerInterface_Expecter) StopAnnouncement() *PairingAnnouncerInterface_StopAnnouncement_Call {
	return &PairingAnnouncerInterface_StopAnnouncement_Call{Call: _e.mock.On("StopAnnouncement")}
}

func (_c *PairingAnnouncerInterface_StopAnnouncement_Call) Run(run func()) *PairingAnnouncerInterface_StopAnnouncement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PairingAnnouncerInterface_StopAnnouncement_Call) Return(err error) *PairingAnnouncerInterface_StopAnnouncement_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PairingAnnouncerInterface_StopAnnouncement_Call) RunAndReturn(run func() error) *PairingAnnouncerInterface_StopAnnouncement_Call {
	_c.Call.Return(run)
	return _c
}
