// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPairingHubInterface creates a new instance of PairingHubInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPairingHubInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PairingHubInterface {
	mock := &PairingHubInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PairingHubInterface is an autogenerated mock type for the PairingHubInterface type
type PairingHubInterface struct {
	mock.Mock
}

type PairingHubInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *PairingHubInterface) EXPECT() *PairingHubInterface_Expecter {
	return &PairingHubInterface_Expecter{mock: &_m.Mock}
}

// HasTrustedAddCuDevice provides a mock function for the type PairingHubInterface
func (_mock *PairingHubInterface) HasTrustedAddCuDevice() (string, string) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasTrustedAddCuDevice")
	}

	var r0 string
	var r1 string
	if returnFunc, ok := ret.Get(0).(func() (string, string)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// PairingHubInterface_HasTrustedAddCuDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasTrustedAddCuDevice'
type PairingHubInterface_HasTrustedAddCuDevice_Call struct {
	*mock.Call
}

// HasTrustedAddCuDevice is a helper method to define mock.On call
func (_e *PairingHubInterface_Expecter) HasTrustedAddCuDevice() *PairingHubInterface_HasTrustedAddCuDevice_Call {
	return &PairingHubInterface_HasTrustedAddCuDevice_Call{Call: _e.mock.On("HasTrustedAddCuDevice")}
}

func (_c *PairingHubInterface_HasTrustedAddCuDevice_Call) Run(run func()) *PairingHubInterface_HasTrustedAddCuDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PairingHubInterface_HasTrustedAddCuDevice_Call) Return(fingerprint string, shipID string) *PairingHubInterface_HasTrustedAddCuDevice_Call {
	_c.Call.Return(fingerprint, shipID)
	return _c
}

func (_c *PairingHubInterface_HasTrustedAddCuDevice_Call) RunAndReturn(run func() (string, string)) *PairingHubInterface_HasTrustedAddCuDevice_Call {
	_c.Call.Return(run)
	return _c
}

// OnPairingFailure provides a mock function for the type PairingHubInterface
func (_mock *PairingHubInterface) OnPairingFailure(remoteShipID string, remoteFingerprint string, reason error) {
	_mock.Called(remoteShipID, remoteFingerprint, reason)
	return
}

// PairingHubInterface_OnPairingFailure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPairingFailure'
type PairingHubInterface_OnPairingFailure_Call struct {
	*mock.Call
}

// OnPairingFailure is a helper method to define mock.On call
//   - remoteShipID string
//   - remoteFingerprint string
//   - reason error
func (_e *PairingHubInterface_Expecter) OnPairingFailure(remoteShipID interface{}, remoteFingerprint interface{}, reason interface{}) *PairingHubInterface_OnPairingFailure_Call {
	return &PairingHubInterface_OnPairingFailure_Call{Call: _e.mock.On("OnPairingFailure", remoteShipID, remoteFingerprint, reason)}
}

func (_c *PairingHubInterface_OnPairingFailure_Call) Run(run func(remoteShipID string, remoteFingerprint string, reason error)) *PairingHubInterface_OnPairingFailure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PairingHubInterface_OnPairingFailure_Call) Return() *PairingHubInterface_OnPairingFailure_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingHubInterface_OnPairingFailure_Call) RunAndReturn(run func(remoteShipID string, remoteFingerprint string, reason error)) *PairingHubInterface_OnPairingFailure_Call {
	_c.Run(run)
	return _c
}

// OnPairingSuccess provides a mock function for the type PairingHubInterface
func (_mock *PairingHubInterface) OnPairingSuccess(remoteShipID string, remoteFingerprint string) {
	_mock.Called(remoteShipID, remoteFingerprint)
	return
}

// PairingHubInterface_OnPairingSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPairingSuccess'
type PairingHubInterface_OnPairingSuccess_Call struct {
	*mock.Call
}

// OnPairingSuccess is a helper method to define mock.On call
//   - remoteShipID string
//   - remoteFingerprint string
func (_e *PairingHubInterface_Expecter) OnPairingSuccess(remoteShipID interface{}, remoteFingerprint interface{}) *PairingHubInterface_OnPairingSuccess_Call {
	return &PairingHubInterface_OnPairingSuccess_Call{Call: _e.mock.On("OnPairingSuccess", remoteShipID, remoteFingerprint)}
}

func (_c *PairingHubInterface_OnPairingSuccess_Call) Run(run func(remoteShipID string, remoteFingerprint string)) *PairingHubInterface_OnPairingSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PairingHubInterface_OnPairingSuccess_Call) Return() *PairingHubInterface_OnPairingSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingHubInterface_OnPairingSuccess_Call) RunAndReturn(run func(remoteShipID string, remoteFingerprint string)) *PairingHubInterface_OnPairingSuccess_Call {
	_c.Run(run)
	return _c
}
