// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewPairingHubInterface creates a new instance of PairingHubInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPairingHubInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PairingHubInterface {
	mock := &PairingHubInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PairingHubInterface is an autogenerated mock type for the PairingHubInterface type
type PairingHubInterface struct {
	mock.Mock
}

type PairingHubInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *PairingHubInterface) EXPECT() *PairingHubInterface_Expecter {
	return &PairingHubInterface_Expecter{mock: &_m.Mock}
}

// IsRemoteServicePaired provides a mock function for the type PairingHubInterface
func (_mock *PairingHubInterface) IsRemoteServicePaired(ski string, fingerprint string) bool {
	ret := _mock.Called(ski, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for IsRemoteServicePaired")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(ski, fingerprint)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// PairingHubInterface_IsRemoteServicePaired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRemoteServicePaired'
type PairingHubInterface_IsRemoteServicePaired_Call struct {
	*mock.Call
}

// IsRemoteServicePaired is a helper method to define mock.On call
//   - ski string
//   - fingerprint string
func (_e *PairingHubInterface_Expecter) IsRemoteServicePaired(ski interface{}, fingerprint interface{}) *PairingHubInterface_IsRemoteServicePaired_Call {
	return &PairingHubInterface_IsRemoteServicePaired_Call{Call: _e.mock.On("IsRemoteServicePaired", ski, fingerprint)}
}

func (_c *PairingHubInterface_IsRemoteServicePaired_Call) Run(run func(ski string, fingerprint string)) *PairingHubInterface_IsRemoteServicePaired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PairingHubInterface_IsRemoteServicePaired_Call) Return(b bool) *PairingHubInterface_IsRemoteServicePaired_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *PairingHubInterface_IsRemoteServicePaired_Call) RunAndReturn(run func(ski string, fingerprint string) bool) *PairingHubInterface_IsRemoteServicePaired_Call {
	_c.Call.Return(run)
	return _c
}

// OnPairingFailure provides a mock function for the type PairingHubInterface
func (_mock *PairingHubInterface) OnPairingFailure(remoteShipID string, remoteFingerprint string, reason error) {
	_mock.Called(remoteShipID, remoteFingerprint, reason)
	return
}

// PairingHubInterface_OnPairingFailure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPairingFailure'
type PairingHubInterface_OnPairingFailure_Call struct {
	*mock.Call
}

// OnPairingFailure is a helper method to define mock.On call
//   - remoteShipID string
//   - remoteFingerprint string
//   - reason error
func (_e *PairingHubInterface_Expecter) OnPairingFailure(remoteShipID interface{}, remoteFingerprint interface{}, reason interface{}) *PairingHubInterface_OnPairingFailure_Call {
	return &PairingHubInterface_OnPairingFailure_Call{Call: _e.mock.On("OnPairingFailure", remoteShipID, remoteFingerprint, reason)}
}

func (_c *PairingHubInterface_OnPairingFailure_Call) Run(run func(remoteShipID string, remoteFingerprint string, reason error)) *PairingHubInterface_OnPairingFailure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PairingHubInterface_OnPairingFailure_Call) Return() *PairingHubInterface_OnPairingFailure_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingHubInterface_OnPairingFailure_Call) RunAndReturn(run func(remoteShipID string, remoteFingerprint string, reason error)) *PairingHubInterface_OnPairingFailure_Call {
	_c.Run(run)
	return _c
}

// OnPairingSuccess provides a mock function for the type PairingHubInterface
func (_mock *PairingHubInterface) OnPairingSuccess(remoteShipID string, remoteFingerprint string) {
	_mock.Called(remoteShipID, remoteFingerprint)
	return
}

// PairingHubInterface_OnPairingSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPairingSuccess'
type PairingHubInterface_OnPairingSuccess_Call struct {
	*mock.Call
}

// OnPairingSuccess is a helper method to define mock.On call
//   - remoteShipID string
//   - remoteFingerprint string
func (_e *PairingHubInterface_Expecter) OnPairingSuccess(remoteShipID interface{}, remoteFingerprint interface{}) *PairingHubInterface_OnPairingSuccess_Call {
	return &PairingHubInterface_OnPairingSuccess_Call{Call: _e.mock.On("OnPairingSuccess", remoteShipID, remoteFingerprint)}
}

func (_c *PairingHubInterface_OnPairingSuccess_Call) Run(run func(remoteShipID string, remoteFingerprint string)) *PairingHubInterface_OnPairingSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PairingHubInterface_OnPairingSuccess_Call) Return() *PairingHubInterface_OnPairingSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingHubInterface_OnPairingSuccess_Call) RunAndReturn(run func(remoteShipID string, remoteFingerprint string)) *PairingHubInterface_OnPairingSuccess_Call {
	_c.Run(run)
	return _c
}

// ServiceForFingerprint provides a mock function for the type PairingHubInterface
func (_mock *PairingHubInterface) ServiceForFingerprint(fingerprint string) *api.ServiceDetails {
	ret := _mock.Called(fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for ServiceForFingerprint")
	}

	var r0 *api.ServiceDetails
	if returnFunc, ok := ret.Get(0).(func(string) *api.ServiceDetails); ok {
		r0 = returnFunc(fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ServiceDetails)
		}
	}
	return r0
}

// PairingHubInterface_ServiceForFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceForFingerprint'
type PairingHubInterface_ServiceForFingerprint_Call struct {
	*mock.Call
}

// ServiceForFingerprint is a helper method to define mock.On call
//   - fingerprint string
func (_e *PairingHubInterface_Expecter) ServiceForFingerprint(fingerprint interface{}) *PairingHubInterface_ServiceForFingerprint_Call {
	return &PairingHubInterface_ServiceForFingerprint_Call{Call: _e.mock.On("ServiceForFingerprint", fingerprint)}
}

func (_c *PairingHubInterface_ServiceForFingerprint_Call) Run(run func(fingerprint string)) *PairingHubInterface_ServiceForFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PairingHubInterface_ServiceForFingerprint_Call) Return(serviceDetails *api.ServiceDetails) *PairingHubInterface_ServiceForFingerprint_Call {
	_c.Call.Return(serviceDetails)
	return _c
}

func (_c *PairingHubInterface_ServiceForFingerprint_Call) RunAndReturn(run func(fingerprint string) *api.ServiceDetails) *PairingHubInterface_ServiceForFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceForShipID provides a mock function for the type PairingHubInterface
func (_mock *PairingHubInterface) ServiceForShipID(shipID string) *api.ServiceDetails {
	ret := _mock.Called(shipID)

	if len(ret) == 0 {
		panic("no return value specified for ServiceForShipID")
	}

	var r0 *api.ServiceDetails
	if returnFunc, ok := ret.Get(0).(func(string) *api.ServiceDetails); ok {
		r0 = returnFunc(shipID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ServiceDetails)
		}
	}
	return r0
}

// PairingHubInterface_ServiceForShipID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceForShipID'
type PairingHubInterface_ServiceForShipID_Call struct {
	*mock.Call
}

// ServiceForShipID is a helper method to define mock.On call
//   - shipID string
func (_e *PairingHubInterface_Expecter) ServiceForShipID(shipID interface{}) *PairingHubInterface_ServiceForShipID_Call {
	return &PairingHubInterface_ServiceForShipID_Call{Call: _e.mock.On("ServiceForShipID", shipID)}
}

func (_c *PairingHubInterface_ServiceForShipID_Call) Run(run func(shipID string)) *PairingHubInterface_ServiceForShipID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PairingHubInterface_ServiceForShipID_Call) Return(serviceDetails *api.ServiceDetails) *PairingHubInterface_ServiceForShipID_Call {
	_c.Call.Return(serviceDetails)
	return _c
}

func (_c *PairingHubInterface_ServiceForShipID_Call) RunAndReturn(run func(shipID string) *api.ServiceDetails) *PairingHubInterface_ServiceForShipID_Call {
	_c.Call.Return(run)
	return _c
}
