// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewPairingServiceReaderInterface creates a new instance of PairingServiceReaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPairingServiceReaderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PairingServiceReaderInterface {
	mock := &PairingServiceReaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PairingServiceReaderInterface is an autogenerated mock type for the PairingServiceReaderInterface type
type PairingServiceReaderInterface struct {
	mock.Mock
}

type PairingServiceReaderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *PairingServiceReaderInterface) EXPECT() *PairingServiceReaderInterface_Expecter {
	return &PairingServiceReaderInterface_Expecter{mock: &_m.Mock}
}

// DeviceAutoTrustRemovedViaReplacementLogic provides a mock function for the type PairingServiceReaderInterface
func (_mock *PairingServiceReaderInterface) DeviceAutoTrustRemovedViaReplacementLogic(service *api.ServiceDetails, reason string) {
	_mock.Called(service, reason)
	return
}

// PairingServiceReaderInterface_DeviceAutoTrustRemovedViaReplacementLogic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceAutoTrustRemovedViaReplacementLogic'
type PairingServiceReaderInterface_DeviceAutoTrustRemovedViaReplacementLogic_Call struct {
	*mock.Call
}

// DeviceAutoTrustRemovedViaReplacementLogic is a helper method to define mock.On call
//   - service *api.ServiceDetails
//   - reason string
func (_e *PairingServiceReaderInterface_Expecter) DeviceAutoTrustRemovedViaReplacementLogic(service interface{}, reason interface{}) *PairingServiceReaderInterface_DeviceAutoTrustRemovedViaReplacementLogic_Call {
	return &PairingServiceReaderInterface_DeviceAutoTrustRemovedViaReplacementLogic_Call{Call: _e.mock.On("DeviceAutoTrustRemovedViaReplacementLogic", service, reason)}
}

func (_c *PairingServiceReaderInterface_DeviceAutoTrustRemovedViaReplacementLogic_Call) Run(run func(service *api.ServiceDetails, reason string)) *PairingServiceReaderInterface_DeviceAutoTrustRemovedViaReplacementLogic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.ServiceDetails
		if args[0] != nil {
			arg0 = args[0].(*api.ServiceDetails)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PairingServiceReaderInterface_DeviceAutoTrustRemovedViaReplacementLogic_Call) Return() *PairingServiceReaderInterface_DeviceAutoTrustRemovedViaReplacementLogic_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingServiceReaderInterface_DeviceAutoTrustRemovedViaReplacementLogic_Call) RunAndReturn(run func(service *api.ServiceDetails, reason string)) *PairingServiceReaderInterface_DeviceAutoTrustRemovedViaReplacementLogic_Call {
	_c.Run(run)
	return _c
}

// DeviceAutoTrustedViaServiceDetails provides a mock function for the type PairingServiceReaderInterface
func (_mock *PairingServiceReaderInterface) DeviceAutoTrustedViaServiceDetails(service *api.ServiceDetails) {
	_mock.Called(service)
	return
}

// PairingServiceReaderInterface_DeviceAutoTrustedViaServiceDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceAutoTrustedViaServiceDetails'
type PairingServiceReaderInterface_DeviceAutoTrustedViaServiceDetails_Call struct {
	*mock.Call
}

// DeviceAutoTrustedViaServiceDetails is a helper method to define mock.On call
//   - service *api.ServiceDetails
func (_e *PairingServiceReaderInterface_Expecter) DeviceAutoTrustedViaServiceDetails(service interface{}) *PairingServiceReaderInterface_DeviceAutoTrustedViaServiceDetails_Call {
	return &PairingServiceReaderInterface_DeviceAutoTrustedViaServiceDetails_Call{Call: _e.mock.On("DeviceAutoTrustedViaServiceDetails", service)}
}

func (_c *PairingServiceReaderInterface_DeviceAutoTrustedViaServiceDetails_Call) Run(run func(service *api.ServiceDetails)) *PairingServiceReaderInterface_DeviceAutoTrustedViaServiceDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.ServiceDetails
		if args[0] != nil {
			arg0 = args[0].(*api.ServiceDetails)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PairingServiceReaderInterface_DeviceAutoTrustedViaServiceDetails_Call) Return() *PairingServiceReaderInterface_DeviceAutoTrustedViaServiceDetails_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingServiceReaderInterface_DeviceAutoTrustedViaServiceDetails_Call) RunAndReturn(run func(service *api.ServiceDetails)) *PairingServiceReaderInterface_DeviceAutoTrustedViaServiceDetails_Call {
	_c.Run(run)
	return _c
}

// PairingServiceFailedForServiceDetails provides a mock function for the type PairingServiceReaderInterface
func (_mock *PairingServiceReaderInterface) PairingServiceFailedForServiceDetails(service *api.ServiceDetails, reason error) {
	_mock.Called(service, reason)
	return
}

// PairingServiceReaderInterface_PairingServiceFailedForServiceDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PairingServiceFailedForServiceDetails'
type PairingServiceReaderInterface_PairingServiceFailedForServiceDetails_Call struct {
	*mock.Call
}

// PairingServiceFailedForServiceDetails is a helper method to define mock.On call
//   - service *api.ServiceDetails
//   - reason error
func (_e *PairingServiceReaderInterface_Expecter) PairingServiceFailedForServiceDetails(service interface{}, reason interface{}) *PairingServiceReaderInterface_PairingServiceFailedForServiceDetails_Call {
	return &PairingServiceReaderInterface_PairingServiceFailedForServiceDetails_Call{Call: _e.mock.On("PairingServiceFailedForServiceDetails", service, reason)}
}

func (_c *PairingServiceReaderInterface_PairingServiceFailedForServiceDetails_Call) Run(run func(service *api.ServiceDetails, reason error)) *PairingServiceReaderInterface_PairingServiceFailedForServiceDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.ServiceDetails
		if args[0] != nil {
			arg0 = args[0].(*api.ServiceDetails)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PairingServiceReaderInterface_PairingServiceFailedForServiceDetails_Call) Return() *PairingServiceReaderInterface_PairingServiceFailedForServiceDetails_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingServiceReaderInterface_PairingServiceFailedForServiceDetails_Call) RunAndReturn(run func(service *api.ServiceDetails, reason error)) *PairingServiceReaderInterface_PairingServiceFailedForServiceDetails_Call {
	_c.Run(run)
	return _c
}
