// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewPairingServiceReaderInterface creates a new instance of PairingServiceReaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPairingServiceReaderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PairingServiceReaderInterface {
	mock := &PairingServiceReaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PairingServiceReaderInterface is an autogenerated mock type for the PairingServiceReaderInterface type
type PairingServiceReaderInterface struct {
	mock.Mock
}

type PairingServiceReaderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *PairingServiceReaderInterface) EXPECT() *PairingServiceReaderInterface_Expecter {
	return &PairingServiceReaderInterface_Expecter{mock: &_m.Mock}
}

// ServiceAutoTrustFailed provides a mock function for the type PairingServiceReaderInterface
func (_mock *PairingServiceReaderInterface) ServiceAutoTrustFailed(identity api.ServiceIdentity, reason error) {
	_mock.Called(identity, reason)
	return
}

// PairingServiceReaderInterface_ServiceAutoTrustFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceAutoTrustFailed'
type PairingServiceReaderInterface_ServiceAutoTrustFailed_Call struct {
	*mock.Call
}

// ServiceAutoTrustFailed is a helper method to define mock.On call
//   - identity api.ServiceIdentity
//   - reason error
func (_e *PairingServiceReaderInterface_Expecter) ServiceAutoTrustFailed(identity interface{}, reason interface{}) *PairingServiceReaderInterface_ServiceAutoTrustFailed_Call {
	return &PairingServiceReaderInterface_ServiceAutoTrustFailed_Call{Call: _e.mock.On("ServiceAutoTrustFailed", identity, reason)}
}

func (_c *PairingServiceReaderInterface_ServiceAutoTrustFailed_Call) Run(run func(identity api.ServiceIdentity, reason error)) *PairingServiceReaderInterface_ServiceAutoTrustFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PairingServiceReaderInterface_ServiceAutoTrustFailed_Call) Return() *PairingServiceReaderInterface_ServiceAutoTrustFailed_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingServiceReaderInterface_ServiceAutoTrustFailed_Call) RunAndReturn(run func(identity api.ServiceIdentity, reason error)) *PairingServiceReaderInterface_ServiceAutoTrustFailed_Call {
	_c.Run(run)
	return _c
}

// ServiceAutoTrustRemoved provides a mock function for the type PairingServiceReaderInterface
func (_mock *PairingServiceReaderInterface) ServiceAutoTrustRemoved(identity api.ServiceIdentity, reason string) {
	_mock.Called(identity, reason)
	return
}

// PairingServiceReaderInterface_ServiceAutoTrustRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceAutoTrustRemoved'
type PairingServiceReaderInterface_ServiceAutoTrustRemoved_Call struct {
	*mock.Call
}

// ServiceAutoTrustRemoved is a helper method to define mock.On call
//   - identity api.ServiceIdentity
//   - reason string
func (_e *PairingServiceReaderInterface_Expecter) ServiceAutoTrustRemoved(identity interface{}, reason interface{}) *PairingServiceReaderInterface_ServiceAutoTrustRemoved_Call {
	return &PairingServiceReaderInterface_ServiceAutoTrustRemoved_Call{Call: _e.mock.On("ServiceAutoTrustRemoved", identity, reason)}
}

func (_c *PairingServiceReaderInterface_ServiceAutoTrustRemoved_Call) Run(run func(identity api.ServiceIdentity, reason string)) *PairingServiceReaderInterface_ServiceAutoTrustRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PairingServiceReaderInterface_ServiceAutoTrustRemoved_Call) Return() *PairingServiceReaderInterface_ServiceAutoTrustRemoved_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingServiceReaderInterface_ServiceAutoTrustRemoved_Call) RunAndReturn(run func(identity api.ServiceIdentity, reason string)) *PairingServiceReaderInterface_ServiceAutoTrustRemoved_Call {
	_c.Run(run)
	return _c
}

// ServiceAutoTrusted provides a mock function for the type PairingServiceReaderInterface
func (_mock *PairingServiceReaderInterface) ServiceAutoTrusted(identity api.ServiceIdentity) {
	_mock.Called(identity)
	return
}

// PairingServiceReaderInterface_ServiceAutoTrusted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceAutoTrusted'
type PairingServiceReaderInterface_ServiceAutoTrusted_Call struct {
	*mock.Call
}

// ServiceAutoTrusted is a helper method to define mock.On call
//   - identity api.ServiceIdentity
func (_e *PairingServiceReaderInterface_Expecter) ServiceAutoTrusted(identity interface{}) *PairingServiceReaderInterface_ServiceAutoTrusted_Call {
	return &PairingServiceReaderInterface_ServiceAutoTrusted_Call{Call: _e.mock.On("ServiceAutoTrusted", identity)}
}

func (_c *PairingServiceReaderInterface_ServiceAutoTrusted_Call) Run(run func(identity api.ServiceIdentity)) *PairingServiceReaderInterface_ServiceAutoTrusted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceIdentity
		if args[0] != nil {
			arg0 = args[0].(api.ServiceIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PairingServiceReaderInterface_ServiceAutoTrusted_Call) Return() *PairingServiceReaderInterface_ServiceAutoTrusted_Call {
	_c.Call.Return()
	return _c
}

func (_c *PairingServiceReaderInterface_ServiceAutoTrusted_Call) RunAndReturn(run func(identity api.ServiceIdentity)) *PairingServiceReaderInterface_ServiceAutoTrusted_Call {
	_c.Run(run)
	return _c
}
