// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewPairingListenerInterface creates a new instance of PairingListenerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPairingListenerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PairingListenerInterface {
	mock := &PairingListenerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PairingListenerInterface is an autogenerated mock type for the PairingListenerInterface type
type PairingListenerInterface struct {
	mock.Mock
}

type PairingListenerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *PairingListenerInterface) EXPECT() *PairingListenerInterface_Expecter {
	return &PairingListenerInterface_Expecter{mock: &_m.Mock}
}

// GetListenerStatus provides a mock function for the type PairingListenerInterface
func (_mock *PairingListenerInterface) GetListenerStatus() *api.ListenerStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetListenerStatus")
	}

	var r0 *api.ListenerStatus
	if returnFunc, ok := ret.Get(0).(func() *api.ListenerStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ListenerStatus)
		}
	}
	return r0
}

// PairingListenerInterface_GetListenerStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListenerStatus'
type PairingListenerInterface_GetListenerStatus_Call struct {
	*mock.Call
}

// GetListenerStatus is a helper method to define mock.On call
func (_e *PairingListenerInterface_Expecter) GetListenerStatus() *PairingListenerInterface_GetListenerStatus_Call {
	return &PairingListenerInterface_GetListenerStatus_Call{Call: _e.mock.On("GetListenerStatus")}
}

func (_c *PairingListenerInterface_GetListenerStatus_Call) Run(run func()) *PairingListenerInterface_GetListenerStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PairingListenerInterface_GetListenerStatus_Call) Return(listenerStatus *api.ListenerStatus) *PairingListenerInterface_GetListenerStatus_Call {
	_c.Call.Return(listenerStatus)
	return _c
}

func (_c *PairingListenerInterface_GetListenerStatus_Call) RunAndReturn(run func() *api.ListenerStatus) *PairingListenerInterface_GetListenerStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessPendingEntries provides a mock function for the type PairingListenerInterface
func (_mock *PairingListenerInterface) ProcessPendingEntries(entries map[string]*api.ShipPairingTXT) error {
	ret := _mock.Called(entries)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPendingEntries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[string]*api.ShipPairingTXT) error); ok {
		r0 = returnFunc(entries)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PairingListenerInterface_ProcessPendingEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessPendingEntries'
type PairingListenerInterface_ProcessPendingEntries_Call struct {
	*mock.Call
}

// ProcessPendingEntries is a helper method to define mock.On call
//   - entries map[string]*api.ShipPairingTXT
func (_e *PairingListenerInterface_Expecter) ProcessPendingEntries(entries interface{}) *PairingListenerInterface_ProcessPendingEntries_Call {
	return &PairingListenerInterface_ProcessPendingEntries_Call{Call: _e.mock.On("ProcessPendingEntries", entries)}
}

func (_c *PairingListenerInterface_ProcessPendingEntries_Call) Run(run func(entries map[string]*api.ShipPairingTXT)) *PairingListenerInterface_ProcessPendingEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]*api.ShipPairingTXT
		if args[0] != nil {
			arg0 = args[0].(map[string]*api.ShipPairingTXT)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PairingListenerInterface_ProcessPendingEntries_Call) Return(err error) *PairingListenerInterface_ProcessPendingEntries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PairingListenerInterface_ProcessPendingEntries_Call) RunAndReturn(run func(entries map[string]*api.ShipPairingTXT) error) *PairingListenerInterface_ProcessPendingEntries_Call {
	_c.Call.Return(run)
	return _c
}

// StartListening provides a mock function for the type PairingListenerInterface
func (_mock *PairingListenerInterface) StartListening(ctx context.Context, secret api.PairingSecret) error {
	ret := _mock.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for StartListening")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.PairingSecret) error); ok {
		r0 = returnFunc(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PairingListenerInterface_StartListening_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartListening'
type PairingListenerInterface_StartListening_Call struct {
	*mock.Call
}

// StartListening is a helper method to define mock.On call
//   - ctx context.Context
//   - secret api.PairingSecret
func (_e *PairingListenerInterface_Expecter) StartListening(ctx interface{}, secret interface{}) *PairingListenerInterface_StartListening_Call {
	return &PairingListenerInterface_StartListening_Call{Call: _e.mock.On("StartListening", ctx, secret)}
}

func (_c *PairingListenerInterface_StartListening_Call) Run(run func(ctx context.Context, secret api.PairingSecret)) *PairingListenerInterface_StartListening_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 api.PairingSecret
		if args[1] != nil {
			arg1 = args[1].(api.PairingSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PairingListenerInterface_StartListening_Call) Return(err error) *PairingListenerInterface_StartListening_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PairingListenerInterface_StartListening_Call) RunAndReturn(run func(ctx context.Context, secret api.PairingSecret) error) *PairingListenerInterface_StartListening_Call {
	_c.Call.Return(run)
	return _c
}

// StopListening provides a mock function for the type PairingListenerInterface
func (_mock *PairingListenerInterface) StopListening() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopListening")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PairingListenerInterface_StopListening_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopListening'
type PairingListenerInterface_StopListening_Call struct {
	*mock.Call
}

// StopListening is a helper method to define mock.On call
func (_e *PairingListenerInterface_Expecter) StopListening() *PairingListenerInterface_StopListening_Call {
	return &PairingListenerInterface_StopListening_Call{Call: _e.mock.On("StopListening")}
}

func (_c *PairingListenerInterface_StopListening_Call) Run(run func()) *PairingListenerInterface_StopListening_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PairingListenerInterface_StopListening_Call) Return(err error) *PairingListenerInterface_StopListening_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PairingListenerInterface_StopListening_Call) RunAndReturn(run func() error) *PairingListenerInterface_StopListening_Call {
	_c.Call.Return(run)
	return _c
}
