// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewRingBufferPersistence creates a new instance of RingBufferPersistence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRingBufferPersistence(t interface {
	mock.TestingT
	Cleanup(func())
}) *RingBufferPersistence {
	mock := &RingBufferPersistence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RingBufferPersistence is an autogenerated mock type for the RingBufferPersistence type
type RingBufferPersistence struct {
	mock.Mock
}

type RingBufferPersistence_Expecter struct {
	mock *mock.Mock
}

func (_m *RingBufferPersistence) EXPECT() *RingBufferPersistence_Expecter {
	return &RingBufferPersistence_Expecter{mock: &_m.Mock}
}

// LoadRingBuffer provides a mock function for the type RingBufferPersistence
func (_mock *RingBufferPersistence) LoadRingBuffer() ([]api.DigestEntry, int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadRingBuffer")
	}

	var r0 []api.DigestEntry
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() ([]api.DigestEntry, int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []api.DigestEntry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.DigestEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() int); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RingBufferPersistence_LoadRingBuffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRingBuffer'
type RingBufferPersistence_LoadRingBuffer_Call struct {
	*mock.Call
}

// LoadRingBuffer is a helper method to define mock.On call
func (_e *RingBufferPersistence_Expecter) LoadRingBuffer() *RingBufferPersistence_LoadRingBuffer_Call {
	return &RingBufferPersistence_LoadRingBuffer_Call{Call: _e.mock.On("LoadRingBuffer")}
}

func (_c *RingBufferPersistence_LoadRingBuffer_Call) Run(run func()) *RingBufferPersistence_LoadRingBuffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RingBufferPersistence_LoadRingBuffer_Call) Return(digestEntrys []api.DigestEntry, n int, err error) *RingBufferPersistence_LoadRingBuffer_Call {
	_c.Call.Return(digestEntrys, n, err)
	return _c
}

func (_c *RingBufferPersistence_LoadRingBuffer_Call) RunAndReturn(run func() ([]api.DigestEntry, int, error)) *RingBufferPersistence_LoadRingBuffer_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRingBuffer provides a mock function for the type RingBufferPersistence
func (_mock *RingBufferPersistence) SaveRingBuffer(entries []api.DigestEntry, nextIndex int) error {
	ret := _mock.Called(entries, nextIndex)

	if len(ret) == 0 {
		panic("no return value specified for SaveRingBuffer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]api.DigestEntry, int) error); ok {
		r0 = returnFunc(entries, nextIndex)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RingBufferPersistence_SaveRingBuffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRingBuffer'
type RingBufferPersistence_SaveRingBuffer_Call struct {
	*mock.Call
}

// SaveRingBuffer is a helper method to define mock.On call
//   - entries []api.DigestEntry
//   - nextIndex int
func (_e *RingBufferPersistence_Expecter) SaveRingBuffer(entries interface{}, nextIndex interface{}) *RingBufferPersistence_SaveRingBuffer_Call {
	return &RingBufferPersistence_SaveRingBuffer_Call{Call: _e.mock.On("SaveRingBuffer", entries, nextIndex)}
}

func (_c *RingBufferPersistence_SaveRingBuffer_Call) Run(run func(entries []api.DigestEntry, nextIndex int)) *RingBufferPersistence_SaveRingBuffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []api.DigestEntry
		if args[0] != nil {
			arg0 = args[0].([]api.DigestEntry)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RingBufferPersistence_SaveRingBuffer_Call) Return(err error) *RingBufferPersistence_SaveRingBuffer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RingBufferPersistence_SaveRingBuffer_Call) RunAndReturn(run func(entries []api.DigestEntry, nextIndex int) error) *RingBufferPersistence_SaveRingBuffer_Call {
	_c.Call.Return(run)
	return _c
}
