// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	"github.com/enbility/ship-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewShipConnectionInterface creates a new instance of ShipConnectionInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipConnectionInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipConnectionInterface {
	mock := &ShipConnectionInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipConnectionInterface is an autogenerated mock type for the ShipConnectionInterface type
type ShipConnectionInterface struct {
	mock.Mock
}

type ShipConnectionInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipConnectionInterface) EXPECT() *ShipConnectionInterface_Expecter {
	return &ShipConnectionInterface_Expecter{mock: &_m.Mock}
}

// AbortPendingHandshake provides a mock function for the type ShipConnectionInterface
func (_mock *ShipConnectionInterface) AbortPendingHandshake() {
	_mock.Called()
	return
}

// ShipConnectionInterface_AbortPendingHandshake_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortPendingHandshake'
type ShipConnectionInterface_AbortPendingHandshake_Call struct {
	*mock.Call
}

// AbortPendingHandshake is a helper method to define mock.On call
func (_e *ShipConnectionInterface_Expecter) AbortPendingHandshake() *ShipConnectionInterface_AbortPendingHandshake_Call {
	return &ShipConnectionInterface_AbortPendingHandshake_Call{Call: _e.mock.On("AbortPendingHandshake")}
}

func (_c *ShipConnectionInterface_AbortPendingHandshake_Call) Run(run func()) *ShipConnectionInterface_AbortPendingHandshake_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipConnectionInterface_AbortPendingHandshake_Call) Return() *ShipConnectionInterface_AbortPendingHandshake_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipConnectionInterface_AbortPendingHandshake_Call) RunAndReturn(run func()) *ShipConnectionInterface_AbortPendingHandshake_Call {
	_c.Run(run)
	return _c
}

// ApprovePendingHandshake provides a mock function for the type ShipConnectionInterface
func (_mock *ShipConnectionInterface) ApprovePendingHandshake() {
	_mock.Called()
	return
}

// ShipConnectionInterface_ApprovePendingHandshake_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApprovePendingHandshake'
type ShipConnectionInterface_ApprovePendingHandshake_Call struct {
	*mock.Call
}

// ApprovePendingHandshake is a helper method to define mock.On call
func (_e *ShipConnectionInterface_Expecter) ApprovePendingHandshake() *ShipConnectionInterface_ApprovePendingHandshake_Call {
	return &ShipConnectionInterface_ApprovePendingHandshake_Call{Call: _e.mock.On("ApprovePendingHandshake")}
}

func (_c *ShipConnectionInterface_ApprovePendingHandshake_Call) Run(run func()) *ShipConnectionInterface_ApprovePendingHandshake_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipConnectionInterface_ApprovePendingHandshake_Call) Return() *ShipConnectionInterface_ApprovePendingHandshake_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipConnectionInterface_ApprovePendingHandshake_Call) RunAndReturn(run func()) *ShipConnectionInterface_ApprovePendingHandshake_Call {
	_c.Run(run)
	return _c
}

// CloseConnection provides a mock function for the type ShipConnectionInterface
func (_mock *ShipConnectionInterface) CloseConnection(safe bool, code int, reason string) {
	_mock.Called(safe, code, reason)
	return
}

// ShipConnectionInterface_CloseConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseConnection'
type ShipConnectionInterface_CloseConnection_Call struct {
	*mock.Call
}

// CloseConnection is a helper method to define mock.On call
//   - safe bool
//   - code int
//   - reason string
func (_e *ShipConnectionInterface_Expecter) CloseConnection(safe interface{}, code interface{}, reason interface{}) *ShipConnectionInterface_CloseConnection_Call {
	return &ShipConnectionInterface_CloseConnection_Call{Call: _e.mock.On("CloseConnection", safe, code, reason)}
}

func (_c *ShipConnectionInterface_CloseConnection_Call) Run(run func(safe bool, code int, reason string)) *ShipConnectionInterface_CloseConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShipConnectionInterface_CloseConnection_Call) Return() *ShipConnectionInterface_CloseConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipConnectionInterface_CloseConnection_Call) RunAndReturn(run func(safe bool, code int, reason string)) *ShipConnectionInterface_CloseConnection_Call {
	_c.Run(run)
	return _c
}

// DataHandler provides a mock function for the type ShipConnectionInterface
func (_mock *ShipConnectionInterface) DataHandler() api.WebsocketDataWriterInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DataHandler")
	}

	var r0 api.WebsocketDataWriterInterface
	if returnFunc, ok := ret.Get(0).(func() api.WebsocketDataWriterInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.WebsocketDataWriterInterface)
		}
	}
	return r0
}

// ShipConnectionInterface_DataHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataHandler'
type ShipConnectionInterface_DataHandler_Call struct {
	*mock.Call
}

// DataHandler is a helper method to define mock.On call
func (_e *ShipConnectionInterface_Expecter) DataHandler() *ShipConnectionInterface_DataHandler_Call {
	return &ShipConnectionInterface_DataHandler_Call{Call: _e.mock.On("DataHandler")}
}

func (_c *ShipConnectionInterface_DataHandler_Call) Run(run func()) *ShipConnectionInterface_DataHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipConnectionInterface_DataHandler_Call) Return(websocketDataWriterInterface api.WebsocketDataWriterInterface) *ShipConnectionInterface_DataHandler_Call {
	_c.Call.Return(websocketDataWriterInterface)
	return _c
}

func (_c *ShipConnectionInterface_DataHandler_Call) RunAndReturn(run func() api.WebsocketDataWriterInterface) *ShipConnectionInterface_DataHandler_Call {
	_c.Call.Return(run)
	return _c
}

// IsAlive provides a mock function for the type ShipConnectionInterface
func (_mock *ShipConnectionInterface) IsAlive() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAlive")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ShipConnectionInterface_IsAlive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAlive'
type ShipConnectionInterface_IsAlive_Call struct {
	*mock.Call
}

// IsAlive is a helper method to define mock.On call
func (_e *ShipConnectionInterface_Expecter) IsAlive() *ShipConnectionInterface_IsAlive_Call {
	return &ShipConnectionInterface_IsAlive_Call{Call: _e.mock.On("IsAlive")}
}

func (_c *ShipConnectionInterface_IsAlive_Call) Run(run func()) *ShipConnectionInterface_IsAlive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipConnectionInterface_IsAlive_Call) Return(b bool) *ShipConnectionInterface_IsAlive_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ShipConnectionInterface_IsAlive_Call) RunAndReturn(run func() bool) *ShipConnectionInterface_IsAlive_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteSKI provides a mock function for the type ShipConnectionInterface
func (_mock *ShipConnectionInterface) RemoteSKI() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteSKI")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ShipConnectionInterface_RemoteSKI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteSKI'
type ShipConnectionInterface_RemoteSKI_Call struct {
	*mock.Call
}

// RemoteSKI is a helper method to define mock.On call
func (_e *ShipConnectionInterface_Expecter) RemoteSKI() *ShipConnectionInterface_RemoteSKI_Call {
	return &ShipConnectionInterface_RemoteSKI_Call{Call: _e.mock.On("RemoteSKI")}
}

func (_c *ShipConnectionInterface_RemoteSKI_Call) Run(run func()) *ShipConnectionInterface_RemoteSKI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipConnectionInterface_RemoteSKI_Call) Return(s string) *ShipConnectionInterface_RemoteSKI_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ShipConnectionInterface_RemoteSKI_Call) RunAndReturn(run func() string) *ShipConnectionInterface_RemoteSKI_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type ShipConnectionInterface
func (_mock *ShipConnectionInterface) Run() {
	_mock.Called()
	return
}

// ShipConnectionInterface_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type ShipConnectionInterface_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *ShipConnectionInterface_Expecter) Run() *ShipConnectionInterface_Run_Call {
	return &ShipConnectionInterface_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *ShipConnectionInterface_Run_Call) Run(run func()) *ShipConnectionInterface_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipConnectionInterface_Run_Call) Return() *ShipConnectionInterface_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipConnectionInterface_Run_Call) RunAndReturn(run func()) *ShipConnectionInterface_Run_Call {
	_c.Run(run)
	return _c
}

// ShipHandshakeState provides a mock function for the type ShipConnectionInterface
func (_mock *ShipConnectionInterface) ShipHandshakeState() (model.ShipMessageExchangeState, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShipHandshakeState")
	}

	var r0 model.ShipMessageExchangeState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (model.ShipMessageExchangeState, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() model.ShipMessageExchangeState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(model.ShipMessageExchangeState)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShipConnectionInterface_ShipHandshakeState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShipHandshakeState'
type ShipConnectionInterface_ShipHandshakeState_Call struct {
	*mock.Call
}

// ShipHandshakeState is a helper method to define mock.On call
func (_e *ShipConnectionInterface_Expecter) ShipHandshakeState() *ShipConnectionInterface_ShipHandshakeState_Call {
	return &ShipConnectionInterface_ShipHandshakeState_Call{Call: _e.mock.On("ShipHandshakeState")}
}

func (_c *ShipConnectionInterface_ShipHandshakeState_Call) Run(run func()) *ShipConnectionInterface_ShipHandshakeState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipConnectionInterface_ShipHandshakeState_Call) Return(shipMessageExchangeState model.ShipMessageExchangeState, err error) *ShipConnectionInterface_ShipHandshakeState_Call {
	_c.Call.Return(shipMessageExchangeState, err)
	return _c
}

func (_c *ShipConnectionInterface_ShipHandshakeState_Call) RunAndReturn(run func() (model.ShipMessageExchangeState, error)) *ShipConnectionInterface_ShipHandshakeState_Call {
	_c.Call.Return(run)
	return _c
}
