// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewShipConnectionDataWriterInterface creates a new instance of ShipConnectionDataWriterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipConnectionDataWriterInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipConnectionDataWriterInterface {
	mock := &ShipConnectionDataWriterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipConnectionDataWriterInterface is an autogenerated mock type for the ShipConnectionDataWriterInterface type
type ShipConnectionDataWriterInterface struct {
	mock.Mock
}

type ShipConnectionDataWriterInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipConnectionDataWriterInterface) EXPECT() *ShipConnectionDataWriterInterface_Expecter {
	return &ShipConnectionDataWriterInterface_Expecter{mock: &_m.Mock}
}

// WriteShipMessageWithPayload provides a mock function for the type ShipConnectionDataWriterInterface
func (_mock *ShipConnectionDataWriterInterface) WriteShipMessageWithPayload(message []byte) {
	_mock.Called(message)
	return
}

// ShipConnectionDataWriterInterface_WriteShipMessageWithPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteShipMessageWithPayload'
type ShipConnectionDataWriterInterface_WriteShipMessageWithPayload_Call struct {
	*mock.Call
}

// WriteShipMessageWithPayload is a helper method to define mock.On call
//   - message []byte
func (_e *ShipConnectionDataWriterInterface_Expecter) WriteShipMessageWithPayload(message interface{}) *ShipConnectionDataWriterInterface_WriteShipMessageWithPayload_Call {
	return &ShipConnectionDataWriterInterface_WriteShipMessageWithPayload_Call{Call: _e.mock.On("WriteShipMessageWithPayload", message)}
}

func (_c *ShipConnectionDataWriterInterface_WriteShipMessageWithPayload_Call) Run(run func(message []byte)) *ShipConnectionDataWriterInterface_WriteShipMessageWithPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ShipConnectionDataWriterInterface_WriteShipMessageWithPayload_Call) Return() *ShipConnectionDataWriterInterface_WriteShipMessageWithPayload_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipConnectionDataWriterInterface_WriteShipMessageWithPayload_Call) RunAndReturn(run func(message []byte)) *ShipConnectionDataWriterInterface_WriteShipMessageWithPayload_Call {
	_c.Run(run)
	return _c
}
