// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	"github.com/enbility/ship-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewShipConnectionInfoProviderInterface creates a new instance of ShipConnectionInfoProviderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipConnectionInfoProviderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipConnectionInfoProviderInterface {
	mock := &ShipConnectionInfoProviderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipConnectionInfoProviderInterface is an autogenerated mock type for the ShipConnectionInfoProviderInterface type
type ShipConnectionInfoProviderInterface struct {
	mock.Mock
}

type ShipConnectionInfoProviderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipConnectionInfoProviderInterface) EXPECT() *ShipConnectionInfoProviderInterface_Expecter {
	return &ShipConnectionInfoProviderInterface_Expecter{mock: &_m.Mock}
}

// AllowWaitingForTrust provides a mock function for the type ShipConnectionInfoProviderInterface
func (_mock *ShipConnectionInfoProviderInterface) AllowWaitingForTrust(ski string) bool {
	ret := _mock.Called(ski)

	if len(ret) == 0 {
		panic("no return value specified for AllowWaitingForTrust")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(ski)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ShipConnectionInfoProviderInterface_AllowWaitingForTrust_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowWaitingForTrust'
type ShipConnectionInfoProviderInterface_AllowWaitingForTrust_Call struct {
	*mock.Call
}

// AllowWaitingForTrust is a helper method to define mock.On call
//   - ski string
func (_e *ShipConnectionInfoProviderInterface_Expecter) AllowWaitingForTrust(ski interface{}) *ShipConnectionInfoProviderInterface_AllowWaitingForTrust_Call {
	return &ShipConnectionInfoProviderInterface_AllowWaitingForTrust_Call{Call: _e.mock.On("AllowWaitingForTrust", ski)}
}

func (_c *ShipConnectionInfoProviderInterface_AllowWaitingForTrust_Call) Run(run func(ski string)) *ShipConnectionInfoProviderInterface_AllowWaitingForTrust_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_AllowWaitingForTrust_Call) Return(b bool) *ShipConnectionInfoProviderInterface_AllowWaitingForTrust_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_AllowWaitingForTrust_Call) RunAndReturn(run func(ski string) bool) *ShipConnectionInfoProviderInterface_AllowWaitingForTrust_Call {
	_c.Call.Return(run)
	return _c
}

// HandleConnectionClosed provides a mock function for the type ShipConnectionInfoProviderInterface
func (_mock *ShipConnectionInfoProviderInterface) HandleConnectionClosed(shipConnectionInterface api.ShipConnectionInterface, b bool) {
	_mock.Called(shipConnectionInterface, b)
	return
}

// ShipConnectionInfoProviderInterface_HandleConnectionClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleConnectionClosed'
type ShipConnectionInfoProviderInterface_HandleConnectionClosed_Call struct {
	*mock.Call
}

// HandleConnectionClosed is a helper method to define mock.On call
//   - shipConnectionInterface api.ShipConnectionInterface
//   - b bool
func (_e *ShipConnectionInfoProviderInterface_Expecter) HandleConnectionClosed(shipConnectionInterface interface{}, b interface{}) *ShipConnectionInfoProviderInterface_HandleConnectionClosed_Call {
	return &ShipConnectionInfoProviderInterface_HandleConnectionClosed_Call{Call: _e.mock.On("HandleConnectionClosed", shipConnectionInterface, b)}
}

func (_c *ShipConnectionInfoProviderInterface_HandleConnectionClosed_Call) Run(run func(shipConnectionInterface api.ShipConnectionInterface, b bool)) *ShipConnectionInfoProviderInterface_HandleConnectionClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ShipConnectionInterface
		if args[0] != nil {
			arg0 = args[0].(api.ShipConnectionInterface)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_HandleConnectionClosed_Call) Return() *ShipConnectionInfoProviderInterface_HandleConnectionClosed_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_HandleConnectionClosed_Call) RunAndReturn(run func(shipConnectionInterface api.ShipConnectionInterface, b bool)) *ShipConnectionInfoProviderInterface_HandleConnectionClosed_Call {
	_c.Run(run)
	return _c
}

// HandleShipHandshakeStateUpdate provides a mock function for the type ShipConnectionInfoProviderInterface
func (_mock *ShipConnectionInfoProviderInterface) HandleShipHandshakeStateUpdate(ski string, state model.ShipState) {
	_mock.Called(ski, state)
	return
}

// ShipConnectionInfoProviderInterface_HandleShipHandshakeStateUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleShipHandshakeStateUpdate'
type ShipConnectionInfoProviderInterface_HandleShipHandshakeStateUpdate_Call struct {
	*mock.Call
}

// HandleShipHandshakeStateUpdate is a helper method to define mock.On call
//   - ski string
//   - state model.ShipState
func (_e *ShipConnectionInfoProviderInterface_Expecter) HandleShipHandshakeStateUpdate(ski interface{}, state interface{}) *ShipConnectionInfoProviderInterface_HandleShipHandshakeStateUpdate_Call {
	return &ShipConnectionInfoProviderInterface_HandleShipHandshakeStateUpdate_Call{Call: _e.mock.On("HandleShipHandshakeStateUpdate", ski, state)}
}

func (_c *ShipConnectionInfoProviderInterface_HandleShipHandshakeStateUpdate_Call) Run(run func(ski string, state model.ShipState)) *ShipConnectionInfoProviderInterface_HandleShipHandshakeStateUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 model.ShipState
		if args[1] != nil {
			arg1 = args[1].(model.ShipState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_HandleShipHandshakeStateUpdate_Call) Return() *ShipConnectionInfoProviderInterface_HandleShipHandshakeStateUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_HandleShipHandshakeStateUpdate_Call) RunAndReturn(run func(ski string, state model.ShipState)) *ShipConnectionInfoProviderInterface_HandleShipHandshakeStateUpdate_Call {
	_c.Run(run)
	return _c
}

// IsAutoAcceptEnabled provides a mock function for the type ShipConnectionInfoProviderInterface
func (_mock *ShipConnectionInfoProviderInterface) IsAutoAcceptEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAutoAcceptEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ShipConnectionInfoProviderInterface_IsAutoAcceptEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAutoAcceptEnabled'
type ShipConnectionInfoProviderInterface_IsAutoAcceptEnabled_Call struct {
	*mock.Call
}

// IsAutoAcceptEnabled is a helper method to define mock.On call
func (_e *ShipConnectionInfoProviderInterface_Expecter) IsAutoAcceptEnabled() *ShipConnectionInfoProviderInterface_IsAutoAcceptEnabled_Call {
	return &ShipConnectionInfoProviderInterface_IsAutoAcceptEnabled_Call{Call: _e.mock.On("IsAutoAcceptEnabled")}
}

func (_c *ShipConnectionInfoProviderInterface_IsAutoAcceptEnabled_Call) Run(run func()) *ShipConnectionInfoProviderInterface_IsAutoAcceptEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_IsAutoAcceptEnabled_Call) Return(b bool) *ShipConnectionInfoProviderInterface_IsAutoAcceptEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_IsAutoAcceptEnabled_Call) RunAndReturn(run func() bool) *ShipConnectionInfoProviderInterface_IsAutoAcceptEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// IsRemoteServiceForSKIPaired provides a mock function for the type ShipConnectionInfoProviderInterface
func (_mock *ShipConnectionInfoProviderInterface) IsRemoteServiceForSKIPaired(ski string) bool {
	ret := _mock.Called(ski)

	if len(ret) == 0 {
		panic("no return value specified for IsRemoteServiceForSKIPaired")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(ski)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ShipConnectionInfoProviderInterface_IsRemoteServiceForSKIPaired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRemoteServiceForSKIPaired'
type ShipConnectionInfoProviderInterface_IsRemoteServiceForSKIPaired_Call struct {
	*mock.Call
}

// IsRemoteServiceForSKIPaired is a helper method to define mock.On call
//   - ski string
func (_e *ShipConnectionInfoProviderInterface_Expecter) IsRemoteServiceForSKIPaired(ski interface{}) *ShipConnectionInfoProviderInterface_IsRemoteServiceForSKIPaired_Call {
	return &ShipConnectionInfoProviderInterface_IsRemoteServiceForSKIPaired_Call{Call: _e.mock.On("IsRemoteServiceForSKIPaired", ski)}
}

func (_c *ShipConnectionInfoProviderInterface_IsRemoteServiceForSKIPaired_Call) Run(run func(ski string)) *ShipConnectionInfoProviderInterface_IsRemoteServiceForSKIPaired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_IsRemoteServiceForSKIPaired_Call) Return(b bool) *ShipConnectionInfoProviderInterface_IsRemoteServiceForSKIPaired_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_IsRemoteServiceForSKIPaired_Call) RunAndReturn(run func(ski string) bool) *ShipConnectionInfoProviderInterface_IsRemoteServiceForSKIPaired_Call {
	_c.Call.Return(run)
	return _c
}

// ReportServiceShipID provides a mock function for the type ShipConnectionInfoProviderInterface
func (_mock *ShipConnectionInfoProviderInterface) ReportServiceShipID(ski string, shipid string) {
	_mock.Called(ski, shipid)
	return
}

// ShipConnectionInfoProviderInterface_ReportServiceShipID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportServiceShipID'
type ShipConnectionInfoProviderInterface_ReportServiceShipID_Call struct {
	*mock.Call
}

// ReportServiceShipID is a helper method to define mock.On call
//   - ski string
//   - shipid string
func (_e *ShipConnectionInfoProviderInterface_Expecter) ReportServiceShipID(ski interface{}, shipid interface{}) *ShipConnectionInfoProviderInterface_ReportServiceShipID_Call {
	return &ShipConnectionInfoProviderInterface_ReportServiceShipID_Call{Call: _e.mock.On("ReportServiceShipID", ski, shipid)}
}

func (_c *ShipConnectionInfoProviderInterface_ReportServiceShipID_Call) Run(run func(ski string, shipid string)) *ShipConnectionInfoProviderInterface_ReportServiceShipID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_ReportServiceShipID_Call) Return() *ShipConnectionInfoProviderInterface_ReportServiceShipID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_ReportServiceShipID_Call) RunAndReturn(run func(ski string, shipid string)) *ShipConnectionInfoProviderInterface_ReportServiceShipID_Call {
	_c.Run(run)
	return _c
}

// SetupRemoteService provides a mock function for the type ShipConnectionInfoProviderInterface
func (_mock *ShipConnectionInfoProviderInterface) SetupRemoteService(ski string, writeI api.ShipConnectionDataWriterInterface) api.ShipConnectionDataReaderInterface {
	ret := _mock.Called(ski, writeI)

	if len(ret) == 0 {
		panic("no return value specified for SetupRemoteService")
	}

	var r0 api.ShipConnectionDataReaderInterface
	if returnFunc, ok := ret.Get(0).(func(string, api.ShipConnectionDataWriterInterface) api.ShipConnectionDataReaderInterface); ok {
		r0 = returnFunc(ski, writeI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.ShipConnectionDataReaderInterface)
		}
	}
	return r0
}

// ShipConnectionInfoProviderInterface_SetupRemoteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupRemoteService'
type ShipConnectionInfoProviderInterface_SetupRemoteService_Call struct {
	*mock.Call
}

// SetupRemoteService is a helper method to define mock.On call
//   - ski string
//   - writeI api.ShipConnectionDataWriterInterface
func (_e *ShipConnectionInfoProviderInterface_Expecter) SetupRemoteService(ski interface{}, writeI interface{}) *ShipConnectionInfoProviderInterface_SetupRemoteService_Call {
	return &ShipConnectionInfoProviderInterface_SetupRemoteService_Call{Call: _e.mock.On("SetupRemoteService", ski, writeI)}
}

func (_c *ShipConnectionInfoProviderInterface_SetupRemoteService_Call) Run(run func(ski string, writeI api.ShipConnectionDataWriterInterface)) *ShipConnectionInfoProviderInterface_SetupRemoteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 api.ShipConnectionDataWriterInterface
		if args[1] != nil {
			arg1 = args[1].(api.ShipConnectionDataWriterInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_SetupRemoteService_Call) Return(shipConnectionDataReaderInterface api.ShipConnectionDataReaderInterface) *ShipConnectionInfoProviderInterface_SetupRemoteService_Call {
	_c.Call.Return(shipConnectionDataReaderInterface)
	return _c
}

func (_c *ShipConnectionInfoProviderInterface_SetupRemoteService_Call) RunAndReturn(run func(ski string, writeI api.ShipConnectionDataWriterInterface) api.ShipConnectionDataReaderInterface) *ShipConnectionInfoProviderInterface_SetupRemoteService_Call {
	_c.Call.Return(run)
	return _c
}
