// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewShipConnectionDataReaderInterface creates a new instance of ShipConnectionDataReaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipConnectionDataReaderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipConnectionDataReaderInterface {
	mock := &ShipConnectionDataReaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipConnectionDataReaderInterface is an autogenerated mock type for the ShipConnectionDataReaderInterface type
type ShipConnectionDataReaderInterface struct {
	mock.Mock
}

type ShipConnectionDataReaderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipConnectionDataReaderInterface) EXPECT() *ShipConnectionDataReaderInterface_Expecter {
	return &ShipConnectionDataReaderInterface_Expecter{mock: &_m.Mock}
}

// HandleShipPayloadMessage provides a mock function for the type ShipConnectionDataReaderInterface
func (_mock *ShipConnectionDataReaderInterface) HandleShipPayloadMessage(message []byte) {
	_mock.Called(message)
	return
}

// ShipConnectionDataReaderInterface_HandleShipPayloadMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleShipPayloadMessage'
type ShipConnectionDataReaderInterface_HandleShipPayloadMessage_Call struct {
	*mock.Call
}

// HandleShipPayloadMessage is a helper method to define mock.On call
//   - message []byte
func (_e *ShipConnectionDataReaderInterface_Expecter) HandleShipPayloadMessage(message interface{}) *ShipConnectionDataReaderInterface_HandleShipPayloadMessage_Call {
	return &ShipConnectionDataReaderInterface_HandleShipPayloadMessage_Call{Call: _e.mock.On("HandleShipPayloadMessage", message)}
}

func (_c *ShipConnectionDataReaderInterface_HandleShipPayloadMessage_Call) Run(run func(message []byte)) *ShipConnectionDataReaderInterface_HandleShipPayloadMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ShipConnectionDataReaderInterface_HandleShipPayloadMessage_Call) Return() *ShipConnectionDataReaderInterface_HandleShipPayloadMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipConnectionDataReaderInterface_HandleShipPayloadMessage_Call) RunAndReturn(run func(message []byte)) *ShipConnectionDataReaderInterface_HandleShipPayloadMessage_Call {
	_c.Run(run)
	return _c
}
