// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewShipPairingServiceInterface creates a new instance of ShipPairingServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipPairingServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipPairingServiceInterface {
	mock := &ShipPairingServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipPairingServiceInterface is an autogenerated mock type for the ShipPairingServiceInterface type
type ShipPairingServiceInterface struct {
	mock.Mock
}

type ShipPairingServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipPairingServiceInterface) EXPECT() *ShipPairingServiceInterface_Expecter {
	return &ShipPairingServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateAnnouncer provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) CreateAnnouncer(localService *api.ServiceDetails) api.PairingAnnouncerInterface {
	ret := _mock.Called(localService)

	if len(ret) == 0 {
		panic("no return value specified for CreateAnnouncer")
	}

	var r0 api.PairingAnnouncerInterface
	if returnFunc, ok := ret.Get(0).(func(*api.ServiceDetails) api.PairingAnnouncerInterface); ok {
		r0 = returnFunc(localService)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.PairingAnnouncerInterface)
		}
	}
	return r0
}

// ShipPairingServiceInterface_CreateAnnouncer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAnnouncer'
type ShipPairingServiceInterface_CreateAnnouncer_Call struct {
	*mock.Call
}

// CreateAnnouncer is a helper method to define mock.On call
//   - localService *api.ServiceDetails
func (_e *ShipPairingServiceInterface_Expecter) CreateAnnouncer(localService interface{}) *ShipPairingServiceInterface_CreateAnnouncer_Call {
	return &ShipPairingServiceInterface_CreateAnnouncer_Call{Call: _e.mock.On("CreateAnnouncer", localService)}
}

func (_c *ShipPairingServiceInterface_CreateAnnouncer_Call) Run(run func(localService *api.ServiceDetails)) *ShipPairingServiceInterface_CreateAnnouncer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.ServiceDetails
		if args[0] != nil {
			arg0 = args[0].(*api.ServiceDetails)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ShipPairingServiceInterface_CreateAnnouncer_Call) Return(pairingAnnouncerInterface api.PairingAnnouncerInterface) *ShipPairingServiceInterface_CreateAnnouncer_Call {
	_c.Call.Return(pairingAnnouncerInterface)
	return _c
}

func (_c *ShipPairingServiceInterface_CreateAnnouncer_Call) RunAndReturn(run func(localService *api.ServiceDetails) api.PairingAnnouncerInterface) *ShipPairingServiceInterface_CreateAnnouncer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateListener provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) CreateListener(localService *api.ServiceDetails) api.PairingListenerInterface {
	ret := _mock.Called(localService)

	if len(ret) == 0 {
		panic("no return value specified for CreateListener")
	}

	var r0 api.PairingListenerInterface
	if returnFunc, ok := ret.Get(0).(func(*api.ServiceDetails) api.PairingListenerInterface); ok {
		r0 = returnFunc(localService)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.PairingListenerInterface)
		}
	}
	return r0
}

// ShipPairingServiceInterface_CreateListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateListener'
type ShipPairingServiceInterface_CreateListener_Call struct {
	*mock.Call
}

// CreateListener is a helper method to define mock.On call
//   - localService *api.ServiceDetails
func (_e *ShipPairingServiceInterface_Expecter) CreateListener(localService interface{}) *ShipPairingServiceInterface_CreateListener_Call {
	return &ShipPairingServiceInterface_CreateListener_Call{Call: _e.mock.On("CreateListener", localService)}
}

func (_c *ShipPairingServiceInterface_CreateListener_Call) Run(run func(localService *api.ServiceDetails)) *ShipPairingServiceInterface_CreateListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.ServiceDetails
		if args[0] != nil {
			arg0 = args[0].(*api.ServiceDetails)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ShipPairingServiceInterface_CreateListener_Call) Return(pairingListenerInterface api.PairingListenerInterface) *ShipPairingServiceInterface_CreateListener_Call {
	_c.Call.Return(pairingListenerInterface)
	return _c
}

func (_c *ShipPairingServiceInterface_CreateListener_Call) RunAndReturn(run func(localService *api.ServiceDetails) api.PairingListenerInterface) *ShipPairingServiceInterface_CreateListener_Call {
	_c.Call.Return(run)
	return _c
}

// GetPairingStatus provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) GetPairingStatus() *api.PairingServiceStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPairingStatus")
	}

	var r0 *api.PairingServiceStatus
	if returnFunc, ok := ret.Get(0).(func() *api.PairingServiceStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.PairingServiceStatus)
		}
	}
	return r0
}

// ShipPairingServiceInterface_GetPairingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPairingStatus'
type ShipPairingServiceInterface_GetPairingStatus_Call struct {
	*mock.Call
}

// GetPairingStatus is a helper method to define mock.On call
func (_e *ShipPairingServiceInterface_Expecter) GetPairingStatus() *ShipPairingServiceInterface_GetPairingStatus_Call {
	return &ShipPairingServiceInterface_GetPairingStatus_Call{Call: _e.mock.On("GetPairingStatus")}
}

func (_c *ShipPairingServiceInterface_GetPairingStatus_Call) Run(run func()) *ShipPairingServiceInterface_GetPairingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipPairingServiceInterface_GetPairingStatus_Call) Return(pairingServiceStatus *api.PairingServiceStatus) *ShipPairingServiceInterface_GetPairingStatus_Call {
	_c.Call.Return(pairingServiceStatus)
	return _c
}

func (_c *ShipPairingServiceInterface_GetPairingStatus_Call) RunAndReturn(run func() *api.PairingServiceStatus) *ShipPairingServiceInterface_GetPairingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// PairingStateFor provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) PairingStateFor(service *api.ServiceDetails) (*api.PairingStateDetail, error) {
	ret := _mock.Called(service)

	if len(ret) == 0 {
		panic("no return value specified for PairingStateFor")
	}

	var r0 *api.PairingStateDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*api.ServiceDetails) (*api.PairingStateDetail, error)); ok {
		return returnFunc(service)
	}
	if returnFunc, ok := ret.Get(0).(func(*api.ServiceDetails) *api.PairingStateDetail); ok {
		r0 = returnFunc(service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.PairingStateDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*api.ServiceDetails) error); ok {
		r1 = returnFunc(service)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShipPairingServiceInterface_PairingStateFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PairingStateFor'
type ShipPairingServiceInterface_PairingStateFor_Call struct {
	*mock.Call
}

// PairingStateFor is a helper method to define mock.On call
//   - service *api.ServiceDetails
func (_e *ShipPairingServiceInterface_Expecter) PairingStateFor(service interface{}) *ShipPairingServiceInterface_PairingStateFor_Call {
	return &ShipPairingServiceInterface_PairingStateFor_Call{Call: _e.mock.On("PairingStateFor", service)}
}

func (_c *ShipPairingServiceInterface_PairingStateFor_Call) Run(run func(service *api.ServiceDetails)) *ShipPairingServiceInterface_PairingStateFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.ServiceDetails
		if args[0] != nil {
			arg0 = args[0].(*api.ServiceDetails)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ShipPairingServiceInterface_PairingStateFor_Call) Return(pairingStateDetail *api.PairingStateDetail, err error) *ShipPairingServiceInterface_PairingStateFor_Call {
	_c.Call.Return(pairingStateDetail, err)
	return _c
}

func (_c *ShipPairingServiceInterface_PairingStateFor_Call) RunAndReturn(run func(service *api.ServiceDetails) (*api.PairingStateDetail, error)) *ShipPairingServiceInterface_PairingStateFor_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) Shutdown() {
	_mock.Called()
	return
}

// ShipPairingServiceInterface_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type ShipPairingServiceInterface_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *ShipPairingServiceInterface_Expecter) Shutdown() *ShipPairingServiceInterface_Shutdown_Call {
	return &ShipPairingServiceInterface_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *ShipPairingServiceInterface_Shutdown_Call) Run(run func()) *ShipPairingServiceInterface_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipPairingServiceInterface_Shutdown_Call) Return() *ShipPairingServiceInterface_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipPairingServiceInterface_Shutdown_Call) RunAndReturn(run func()) *ShipPairingServiceInterface_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ShipPairingServiceInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ShipPairingServiceInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *ShipPairingServiceInterface_Expecter) Start() *ShipPairingServiceInterface_Start_Call {
	return &ShipPairingServiceInterface_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *ShipPairingServiceInterface_Start_Call) Run(run func()) *ShipPairingServiceInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipPairingServiceInterface_Start_Call) Return(err error) *ShipPairingServiceInterface_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ShipPairingServiceInterface_Start_Call) RunAndReturn(run func() error) *ShipPairingServiceInterface_Start_Call {
	_c.Call.Return(run)
	return _c
}
