// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"

	model "github.com/enbility/ship-go/model"
)

// ShipServiceDataProvider is an autogenerated mock type for the ShipServiceDataProvider type
type ShipServiceDataProvider struct {
	mock.Mock
}

type ShipServiceDataProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipServiceDataProvider) EXPECT() *ShipServiceDataProvider_Expecter {
	return &ShipServiceDataProvider_Expecter{mock: &_m.Mock}
}

// AllowWaitingForTrust provides a mock function with given fields: _a0
func (_m *ShipServiceDataProvider) AllowWaitingForTrust(_a0 string) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AllowWaitingForTrust")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ShipServiceDataProvider_AllowWaitingForTrust_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowWaitingForTrust'
type ShipServiceDataProvider_AllowWaitingForTrust_Call struct {
	*mock.Call
}

// AllowWaitingForTrust is a helper method to define mock.On call
//   - _a0 string
func (_e *ShipServiceDataProvider_Expecter) AllowWaitingForTrust(_a0 interface{}) *ShipServiceDataProvider_AllowWaitingForTrust_Call {
	return &ShipServiceDataProvider_AllowWaitingForTrust_Call{Call: _e.mock.On("AllowWaitingForTrust", _a0)}
}

func (_c *ShipServiceDataProvider_AllowWaitingForTrust_Call) Run(run func(_a0 string)) *ShipServiceDataProvider_AllowWaitingForTrust_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ShipServiceDataProvider_AllowWaitingForTrust_Call) Return(_a0 bool) *ShipServiceDataProvider_AllowWaitingForTrust_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShipServiceDataProvider_AllowWaitingForTrust_Call) RunAndReturn(run func(string) bool) *ShipServiceDataProvider_AllowWaitingForTrust_Call {
	_c.Call.Return(run)
	return _c
}

// HandleConnectionClosed provides a mock function with given fields: _a0, _a1
func (_m *ShipServiceDataProvider) HandleConnectionClosed(_a0 api.ShipConnection, _a1 bool) {
	_m.Called(_a0, _a1)
}

// ShipServiceDataProvider_HandleConnectionClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleConnectionClosed'
type ShipServiceDataProvider_HandleConnectionClosed_Call struct {
	*mock.Call
}

// HandleConnectionClosed is a helper method to define mock.On call
//   - _a0 api.ShipConnection
//   - _a1 bool
func (_e *ShipServiceDataProvider_Expecter) HandleConnectionClosed(_a0 interface{}, _a1 interface{}) *ShipServiceDataProvider_HandleConnectionClosed_Call {
	return &ShipServiceDataProvider_HandleConnectionClosed_Call{Call: _e.mock.On("HandleConnectionClosed", _a0, _a1)}
}

func (_c *ShipServiceDataProvider_HandleConnectionClosed_Call) Run(run func(_a0 api.ShipConnection, _a1 bool)) *ShipServiceDataProvider_HandleConnectionClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.ShipConnection), args[1].(bool))
	})
	return _c
}

func (_c *ShipServiceDataProvider_HandleConnectionClosed_Call) Return() *ShipServiceDataProvider_HandleConnectionClosed_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipServiceDataProvider_HandleConnectionClosed_Call) RunAndReturn(run func(api.ShipConnection, bool)) *ShipServiceDataProvider_HandleConnectionClosed_Call {
	_c.Call.Return(run)
	return _c
}

// HandleShipHandshakeStateUpdate provides a mock function with given fields: _a0, _a1
func (_m *ShipServiceDataProvider) HandleShipHandshakeStateUpdate(_a0 string, _a1 model.ShipState) {
	_m.Called(_a0, _a1)
}

// ShipServiceDataProvider_HandleShipHandshakeStateUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleShipHandshakeStateUpdate'
type ShipServiceDataProvider_HandleShipHandshakeStateUpdate_Call struct {
	*mock.Call
}

// HandleShipHandshakeStateUpdate is a helper method to define mock.On call
//   - _a0 string
//   - _a1 model.ShipState
func (_e *ShipServiceDataProvider_Expecter) HandleShipHandshakeStateUpdate(_a0 interface{}, _a1 interface{}) *ShipServiceDataProvider_HandleShipHandshakeStateUpdate_Call {
	return &ShipServiceDataProvider_HandleShipHandshakeStateUpdate_Call{Call: _e.mock.On("HandleShipHandshakeStateUpdate", _a0, _a1)}
}

func (_c *ShipServiceDataProvider_HandleShipHandshakeStateUpdate_Call) Run(run func(_a0 string, _a1 model.ShipState)) *ShipServiceDataProvider_HandleShipHandshakeStateUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.ShipState))
	})
	return _c
}

func (_c *ShipServiceDataProvider_HandleShipHandshakeStateUpdate_Call) Return() *ShipServiceDataProvider_HandleShipHandshakeStateUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipServiceDataProvider_HandleShipHandshakeStateUpdate_Call) RunAndReturn(run func(string, model.ShipState)) *ShipServiceDataProvider_HandleShipHandshakeStateUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// IsRemoteServiceForSKIPaired provides a mock function with given fields: _a0
func (_m *ShipServiceDataProvider) IsRemoteServiceForSKIPaired(_a0 string) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for IsRemoteServiceForSKIPaired")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ShipServiceDataProvider_IsRemoteServiceForSKIPaired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRemoteServiceForSKIPaired'
type ShipServiceDataProvider_IsRemoteServiceForSKIPaired_Call struct {
	*mock.Call
}

// IsRemoteServiceForSKIPaired is a helper method to define mock.On call
//   - _a0 string
func (_e *ShipServiceDataProvider_Expecter) IsRemoteServiceForSKIPaired(_a0 interface{}) *ShipServiceDataProvider_IsRemoteServiceForSKIPaired_Call {
	return &ShipServiceDataProvider_IsRemoteServiceForSKIPaired_Call{Call: _e.mock.On("IsRemoteServiceForSKIPaired", _a0)}
}

func (_c *ShipServiceDataProvider_IsRemoteServiceForSKIPaired_Call) Run(run func(_a0 string)) *ShipServiceDataProvider_IsRemoteServiceForSKIPaired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ShipServiceDataProvider_IsRemoteServiceForSKIPaired_Call) Return(_a0 bool) *ShipServiceDataProvider_IsRemoteServiceForSKIPaired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShipServiceDataProvider_IsRemoteServiceForSKIPaired_Call) RunAndReturn(run func(string) bool) *ShipServiceDataProvider_IsRemoteServiceForSKIPaired_Call {
	_c.Call.Return(run)
	return _c
}

// ReportServiceShipID provides a mock function with given fields: _a0, _a1
func (_m *ShipServiceDataProvider) ReportServiceShipID(_a0 string, _a1 string) {
	_m.Called(_a0, _a1)
}

// ShipServiceDataProvider_ReportServiceShipID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportServiceShipID'
type ShipServiceDataProvider_ReportServiceShipID_Call struct {
	*mock.Call
}

// ReportServiceShipID is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *ShipServiceDataProvider_Expecter) ReportServiceShipID(_a0 interface{}, _a1 interface{}) *ShipServiceDataProvider_ReportServiceShipID_Call {
	return &ShipServiceDataProvider_ReportServiceShipID_Call{Call: _e.mock.On("ReportServiceShipID", _a0, _a1)}
}

func (_c *ShipServiceDataProvider_ReportServiceShipID_Call) Run(run func(_a0 string, _a1 string)) *ShipServiceDataProvider_ReportServiceShipID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ShipServiceDataProvider_ReportServiceShipID_Call) Return() *ShipServiceDataProvider_ReportServiceShipID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipServiceDataProvider_ReportServiceShipID_Call) RunAndReturn(run func(string, string)) *ShipServiceDataProvider_ReportServiceShipID_Call {
	_c.Call.Return(run)
	return _c
}

// SetupRemoteDevice provides a mock function with given fields: ski, writeI
func (_m *ShipServiceDataProvider) SetupRemoteDevice(ski string, writeI api.SpineDataConnection) api.SpineDataProcessing {
	ret := _m.Called(ski, writeI)

	if len(ret) == 0 {
		panic("no return value specified for SetupRemoteDevice")
	}

	var r0 api.SpineDataProcessing
	if rf, ok := ret.Get(0).(func(string, api.SpineDataConnection) api.SpineDataProcessing); ok {
		r0 = rf(ski, writeI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.SpineDataProcessing)
		}
	}

	return r0
}

// ShipServiceDataProvider_SetupRemoteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupRemoteDevice'
type ShipServiceDataProvider_SetupRemoteDevice_Call struct {
	*mock.Call
}

// SetupRemoteDevice is a helper method to define mock.On call
//   - ski string
//   - writeI api.SpineDataConnection
func (_e *ShipServiceDataProvider_Expecter) SetupRemoteDevice(ski interface{}, writeI interface{}) *ShipServiceDataProvider_SetupRemoteDevice_Call {
	return &ShipServiceDataProvider_SetupRemoteDevice_Call{Call: _e.mock.On("SetupRemoteDevice", ski, writeI)}
}

func (_c *ShipServiceDataProvider_SetupRemoteDevice_Call) Run(run func(ski string, writeI api.SpineDataConnection)) *ShipServiceDataProvider_SetupRemoteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(api.SpineDataConnection))
	})
	return _c
}

func (_c *ShipServiceDataProvider_SetupRemoteDevice_Call) Return(_a0 api.SpineDataProcessing) *ShipServiceDataProvider_SetupRemoteDevice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShipServiceDataProvider_SetupRemoteDevice_Call) RunAndReturn(run func(string, api.SpineDataConnection) api.SpineDataProcessing) *ShipServiceDataProvider_SetupRemoteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// NewShipServiceDataProvider creates a new instance of ShipServiceDataProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipServiceDataProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipServiceDataProvider {
	mock := &ShipServiceDataProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
