// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SpineDataConnection is an autogenerated mock type for the SpineDataConnection type
type SpineDataConnection struct {
	mock.Mock
}

type SpineDataConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *SpineDataConnection) EXPECT() *SpineDataConnection_Expecter {
	return &SpineDataConnection_Expecter{mock: &_m.Mock}
}

// WriteSpineMessage provides a mock function with given fields: message
func (_m *SpineDataConnection) WriteSpineMessage(message []byte) {
	_m.Called(message)
}

// SpineDataConnection_WriteSpineMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteSpineMessage'
type SpineDataConnection_WriteSpineMessage_Call struct {
	*mock.Call
}

// WriteSpineMessage is a helper method to define mock.On call
//   - message []byte
func (_e *SpineDataConnection_Expecter) WriteSpineMessage(message interface{}) *SpineDataConnection_WriteSpineMessage_Call {
	return &SpineDataConnection_WriteSpineMessage_Call{Call: _e.mock.On("WriteSpineMessage", message)}
}

func (_c *SpineDataConnection_WriteSpineMessage_Call) Run(run func(message []byte)) *SpineDataConnection_WriteSpineMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *SpineDataConnection_WriteSpineMessage_Call) Return() *SpineDataConnection_WriteSpineMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *SpineDataConnection_WriteSpineMessage_Call) RunAndReturn(run func([]byte)) *SpineDataConnection_WriteSpineMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewSpineDataConnection creates a new instance of SpineDataConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpineDataConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpineDataConnection {
	mock := &SpineDataConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
