// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewWebsocketDataWriterInterface creates a new instance of WebsocketDataWriterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebsocketDataWriterInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebsocketDataWriterInterface {
	mock := &WebsocketDataWriterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WebsocketDataWriterInterface is an autogenerated mock type for the WebsocketDataWriterInterface type
type WebsocketDataWriterInterface struct {
	mock.Mock
}

type WebsocketDataWriterInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *WebsocketDataWriterInterface) EXPECT() *WebsocketDataWriterInterface_Expecter {
	return &WebsocketDataWriterInterface_Expecter{mock: &_m.Mock}
}

// CloseDataConnection provides a mock function for the type WebsocketDataWriterInterface
func (_mock *WebsocketDataWriterInterface) CloseDataConnection(closeCode int, reason string) {
	_mock.Called(closeCode, reason)
	return
}

// WebsocketDataWriterInterface_CloseDataConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseDataConnection'
type WebsocketDataWriterInterface_CloseDataConnection_Call struct {
	*mock.Call
}

// CloseDataConnection is a helper method to define mock.On call
//   - closeCode int
//   - reason string
func (_e *WebsocketDataWriterInterface_Expecter) CloseDataConnection(closeCode interface{}, reason interface{}) *WebsocketDataWriterInterface_CloseDataConnection_Call {
	return &WebsocketDataWriterInterface_CloseDataConnection_Call{Call: _e.mock.On("CloseDataConnection", closeCode, reason)}
}

func (_c *WebsocketDataWriterInterface_CloseDataConnection_Call) Run(run func(closeCode int, reason string)) *WebsocketDataWriterInterface_CloseDataConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WebsocketDataWriterInterface_CloseDataConnection_Call) Return() *WebsocketDataWriterInterface_CloseDataConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *WebsocketDataWriterInterface_CloseDataConnection_Call) RunAndReturn(run func(closeCode int, reason string)) *WebsocketDataWriterInterface_CloseDataConnection_Call {
	_c.Run(run)
	return _c
}

// InitDataProcessing provides a mock function for the type WebsocketDataWriterInterface
func (_mock *WebsocketDataWriterInterface) InitDataProcessing(websocketDataReaderInterface api.WebsocketDataReaderInterface) {
	_mock.Called(websocketDataReaderInterface)
	return
}

// WebsocketDataWriterInterface_InitDataProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitDataProcessing'
type WebsocketDataWriterInterface_InitDataProcessing_Call struct {
	*mock.Call
}

// InitDataProcessing is a helper method to define mock.On call
//   - websocketDataReaderInterface api.WebsocketDataReaderInterface
func (_e *WebsocketDataWriterInterface_Expecter) InitDataProcessing(websocketDataReaderInterface interface{}) *WebsocketDataWriterInterface_InitDataProcessing_Call {
	return &WebsocketDataWriterInterface_InitDataProcessing_Call{Call: _e.mock.On("InitDataProcessing", websocketDataReaderInterface)}
}

func (_c *WebsocketDataWriterInterface_InitDataProcessing_Call) Run(run func(websocketDataReaderInterface api.WebsocketDataReaderInterface)) *WebsocketDataWriterInterface_InitDataProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.WebsocketDataReaderInterface
		if args[0] != nil {
			arg0 = args[0].(api.WebsocketDataReaderInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WebsocketDataWriterInterface_InitDataProcessing_Call) Return() *WebsocketDataWriterInterface_InitDataProcessing_Call {
	_c.Call.Return()
	return _c
}

func (_c *WebsocketDataWriterInterface_InitDataProcessing_Call) RunAndReturn(run func(websocketDataReaderInterface api.WebsocketDataReaderInterface)) *WebsocketDataWriterInterface_InitDataProcessing_Call {
	_c.Run(run)
	return _c
}

// IsDataConnectionClosed provides a mock function for the type WebsocketDataWriterInterface
func (_mock *WebsocketDataWriterInterface) IsDataConnectionClosed() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDataConnectionClosed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WebsocketDataWriterInterface_IsDataConnectionClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDataConnectionClosed'
type WebsocketDataWriterInterface_IsDataConnectionClosed_Call struct {
	*mock.Call
}

// IsDataConnectionClosed is a helper method to define mock.On call
func (_e *WebsocketDataWriterInterface_Expecter) IsDataConnectionClosed() *WebsocketDataWriterInterface_IsDataConnectionClosed_Call {
	return &WebsocketDataWriterInterface_IsDataConnectionClosed_Call{Call: _e.mock.On("IsDataConnectionClosed")}
}

func (_c *WebsocketDataWriterInterface_IsDataConnectionClosed_Call) Run(run func()) *WebsocketDataWriterInterface_IsDataConnectionClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebsocketDataWriterInterface_IsDataConnectionClosed_Call) Return(b bool, err error) *WebsocketDataWriterInterface_IsDataConnectionClosed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *WebsocketDataWriterInterface_IsDataConnectionClosed_Call) RunAndReturn(run func() (bool, error)) *WebsocketDataWriterInterface_IsDataConnectionClosed_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMessageToWebsocketConnection provides a mock function for the type WebsocketDataWriterInterface
func (_mock *WebsocketDataWriterInterface) WriteMessageToWebsocketConnection(bytes []byte) error {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for WriteMessageToWebsocketConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WebsocketDataWriterInterface_WriteMessageToWebsocketConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMessageToWebsocketConnection'
type WebsocketDataWriterInterface_WriteMessageToWebsocketConnection_Call struct {
	*mock.Call
}

// WriteMessageToWebsocketConnection is a helper method to define mock.On call
//   - bytes []byte
func (_e *WebsocketDataWriterInterface_Expecter) WriteMessageToWebsocketConnection(bytes interface{}) *WebsocketDataWriterInterface_WriteMessageToWebsocketConnection_Call {
	return &WebsocketDataWriterInterface_WriteMessageToWebsocketConnection_Call{Call: _e.mock.On("WriteMessageToWebsocketConnection", bytes)}
}

func (_c *WebsocketDataWriterInterface_WriteMessageToWebsocketConnection_Call) Run(run func(bytes []byte)) *WebsocketDataWriterInterface_WriteMessageToWebsocketConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WebsocketDataWriterInterface_WriteMessageToWebsocketConnection_Call) Return(err error) *WebsocketDataWriterInterface_WriteMessageToWebsocketConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WebsocketDataWriterInterface_WriteMessageToWebsocketConnection_Call) RunAndReturn(run func(bytes []byte) error) *WebsocketDataWriterInterface_WriteMessageToWebsocketConnection_Call {
	_c.Call.Return(run)
	return _c
}
