// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewWebsocketDataReaderInterface creates a new instance of WebsocketDataReaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebsocketDataReaderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebsocketDataReaderInterface {
	mock := &WebsocketDataReaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WebsocketDataReaderInterface is an autogenerated mock type for the WebsocketDataReaderInterface type
type WebsocketDataReaderInterface struct {
	mock.Mock
}

type WebsocketDataReaderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *WebsocketDataReaderInterface) EXPECT() *WebsocketDataReaderInterface_Expecter {
	return &WebsocketDataReaderInterface_Expecter{mock: &_m.Mock}
}

// HandleIncomingWebsocketMessage provides a mock function for the type WebsocketDataReaderInterface
func (_mock *WebsocketDataReaderInterface) HandleIncomingWebsocketMessage(bytes []byte) {
	_mock.Called(bytes)
	return
}

// WebsocketDataReaderInterface_HandleIncomingWebsocketMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleIncomingWebsocketMessage'
type WebsocketDataReaderInterface_HandleIncomingWebsocketMessage_Call struct {
	*mock.Call
}

// HandleIncomingWebsocketMessage is a helper method to define mock.On call
//   - bytes []byte
func (_e *WebsocketDataReaderInterface_Expecter) HandleIncomingWebsocketMessage(bytes interface{}) *WebsocketDataReaderInterface_HandleIncomingWebsocketMessage_Call {
	return &WebsocketDataReaderInterface_HandleIncomingWebsocketMessage_Call{Call: _e.mock.On("HandleIncomingWebsocketMessage", bytes)}
}

func (_c *WebsocketDataReaderInterface_HandleIncomingWebsocketMessage_Call) Run(run func(bytes []byte)) *WebsocketDataReaderInterface_HandleIncomingWebsocketMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WebsocketDataReaderInterface_HandleIncomingWebsocketMessage_Call) Return() *WebsocketDataReaderInterface_HandleIncomingWebsocketMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *WebsocketDataReaderInterface_HandleIncomingWebsocketMessage_Call) RunAndReturn(run func(bytes []byte)) *WebsocketDataReaderInterface_HandleIncomingWebsocketMessage_Call {
	_c.Run(run)
	return _c
}

// ReportConnectionError provides a mock function for the type WebsocketDataReaderInterface
func (_mock *WebsocketDataReaderInterface) ReportConnectionError(err error) {
	_mock.Called(err)
	return
}

// WebsocketDataReaderInterface_ReportConnectionError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportConnectionError'
type WebsocketDataReaderInterface_ReportConnectionError_Call struct {
	*mock.Call
}

// ReportConnectionError is a helper method to define mock.On call
//   - err error
func (_e *WebsocketDataReaderInterface_Expecter) ReportConnectionError(err interface{}) *WebsocketDataReaderInterface_ReportConnectionError_Call {
	return &WebsocketDataReaderInterface_ReportConnectionError_Call{Call: _e.mock.On("ReportConnectionError", err)}
}

func (_c *WebsocketDataReaderInterface_ReportConnectionError_Call) Run(run func(err error)) *WebsocketDataReaderInterface_ReportConnectionError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WebsocketDataReaderInterface_ReportConnectionError_Call) Return() *WebsocketDataReaderInterface_ReportConnectionError_Call {
	_c.Call.Return()
	return _c
}

func (_c *WebsocketDataReaderInterface_ReportConnectionError_Call) RunAndReturn(run func(err error)) *WebsocketDataReaderInterface_ReportConnectionError_Call {
	_c.Run(run)
	return _c
}
