# .mockery.yaml
inpackage: false
dir: ../mocks/ 
structname: "{{.InterfaceName}}"
pkgname: "mocks"
filename: "{{.InterfaceName}}.go"
all: true
template: testify
packages:
  github.com/enbility/ship-go/api:
